- id: '1679267547167'
  alias: V-KC Vacuum Starts to Clean Kitchen When People Finished Meal
  description: 'trigger if Stay inside for 1 hour, wait until outside for 5 min, if
    vacuum is not cleaning, start the kitchen cleaning. disable this automation, and
    enable the interrupt automation.

    '
  trigger:
  - platform: state
    entity_id:
    - input_select.kitchen_occupancy
    to: Stayed Inside
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition: []
  action:
  - wait_for_trigger:
    - platform: state
      entity_id:
      - input_select.kitchen_occupancy
      to: Outside
      for:
        hours: 0
        minutes: 5
        seconds: 0
  - condition: not
    conditions:
    - condition: state
      entity_id: vacuum.x1
      state: cleaning
  - service: media_player.play_media
    target:
      entity_id: media_player.kitchen_echo
    data:
      media_content_type: routine
      media_content_id: X1CleanKitchen
  mode: single
- id: '1680642219209'
  alias: auto-set-master-room
  description: ''
  trigger:
  - platform: time_pattern
    seconds: '0'
  condition: []
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id:
      - media_player.master_room_tv
      - light.master_room_lamp_1
      - light.master_room_leds
      - light.master_room_lamp_2
      - light.master_toilet_ceiling_light
      - switch.master_toilet_floor_led
  - service: light.turn_on
    data:
      brightness: 255
    target:
      entity_id: light.master_room_ceiling_light
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_on
    data:
      brightness: 255
    target:
      entity_id: light.master_room_ceiling_light
  - service: light.turn_on
    data:
      flash: short
    target:
      entity_id:
      - light.master_room_bed_led
      - light.master_room_tv_led
      - light.master_room_drawer_led
  mode: single
- id: '1680644672859'
  alias: New Automation
  description: ''
  trigger:
  - platform: state
    entity_id:
    - automation.auto_set_master_room
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.auto_set_master_room
  mode: single
- id: '1692481937669'
  alias: Test automation 123
  description: ''
  trigger:
  - platform: zone
    entity_id: person.tai
    zone: zone.home
    event: leave
    id: people_left_home
  - platform: state
    entity_id:
    - group.master_room_motion
    to: 'Off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
    id: people_left_room
  - platform: time
    at:
    - '21:00:00'
    - '23:00:00'
    - 01:00:00
    id: hit_time
  condition:
  - condition: state
    entity_id: binary_sensor.master_room_balcony_door
    state: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 10
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - people_left_home
        - people_left_room
      sequence:
      - service: script.do_nothing
        data: {}
    - conditions:
      - condition: trigger
        id:
        - hit_time
      sequence:
      - service: script.do_nothing
        data: {}
  mode: single
