- id: '1673648567928'
  alias: 离开家里，但窗未关
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.tais_iphone_13_pro_max
    zone: zone.home
    event: leave
  condition:
  - condition: state
    entity_id: binary_sensor.qian_jie_window
    state: 'on'
  action:
  - service: notify.mobile_app_tais_iphone_13_pro_max
    data:
      title: 窗未关哦~
      message: 你好像出门了，是故意把厕所窗开着的吗？
  mode: single
