- id: '1640433634902'
  alias: B-ER En-suite Room Wall Switch Double Press - Turn off all appliances
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.en_suite_room_ceiling_light_wall_button
    to: double
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id:
      - light.en_suite_room_ceiling_light
      - light.kes_desk_lamps
      - light.tais_desk_lamps
  - service: switch.turn_off
    target:
      entity_id:
      - switch.tais_desk_screen_led
      - switch.kes_desk_screen_led
  mode: single
- id: '1640434716346'
  alias: Guest Toilet Single Press - Turn Off- Ceiling light
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.guest_toilet_light_wall_button
    to: single
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.guest_room_ceiling_light
  mode: single
- id: '1640436701769'
  alias: 'First Corridor Wall Button Single - Turn off ground floor all appliances '
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.first_corridor_light_switch_wall_button
    to: button_1_single
  - platform: state
    entity_id: sensor.first_corridor_light_switch_wall_button
    to: button_2_single
  condition: []
  action:
  - service: automation.trigger
    target:
      entity_id:
      - automation.living_room_wall_switch_double_press_turn_off_all_appliances
      - automation.b_kc_kitchen_light_right_double_press_turn_off_all_kitchen_lights_and_appliance
  mode: single
