# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


# TODO:
# !!!!! En-suite Toilet Door Has the wrong device !!!
# * bedside lights colour control by button
# * master room bed lights colour control by day in the week/mode/sleep etc
# * [HW] Fixed the living room light switches possibly by replacing a new smart switch
# * change all bedroom light colour on the time (using light state off->on as trigger)
# * blueprint instance for heating automation
# * Master room lamps with localtuya to support colour mode
# * Replace living room LED with a working controller
# * Garden bike shed sensor can be easily triggered by grass movement. Move it to a proper place to avoid that. Currently disabled this sensor.

homeassistant:
  customize: !include           customize.yaml
  packages:  !include_dir_named _packages/
  
  
automation gui: !include automations.yaml
script gui:     !include scripts.yaml


# Database logging config
recorder:
  purge_keep_days: 1
  auto_purge: true
  commit_interval: 15 # updates log every 15s
  #db_url: mysql://hass_user:hass_pass@core-mariadb/homeassistant?charset=utf8mb4

# En-suite Room PIR
# TODO: waiting for HA update to use this syntax
#template:
#  - binary_sensor:
#      - name: En-suite Room Whole Room Motion Sensor Motion
#        state: >
#          {{    is_state('binary_sensor.en_suite_room_motion_sensor_motion', 'on')
#             or is_state('binary_sensor.kes_desk_motion_sensor_motion', 'on')
#             or is_state('binary_sensor.tais_desk_motion_sensor_motion ', 'on')
#          }}
           
# HA_On_VMs does not have BLE (bluetooth v4)
  # Xiaomi BLE Round Fast Update Temperature Sensor
#sensor xiaomi_ble_fast:      
#  - platform: mitemp_bt
#    period: 10 # seconds for refresh interval
#    sensor_names:
#      '58:2d:34:3b:6a:27': 'Kitchen Hob Temperature Sensor'



#xiaomi_aqara:
#  discovery_retry: 5
#  gateways: # XiaoMi Gateway
#    - key: 153EEFE707B24CFB
#      mac: 34CE008D7558
       
# Debug Homekit Integration
#logger:
#  default: warning
#  logs:
##    homeassistant.components.homekit: debug
#    homeassistant.components.tado: debug
#    pyhap: debug


# Install Mini Media Player
#resources:
#  - url: /local/mini-media-player-bundle.js?v=1.11.0
#    type: module       

###########################################
# Light/Cover/Switch Groups
###########################################
# HA does not have switch group so have to use group as a workaround
#group tais_switch_group:
#  kitchen_wall_lights:
#    name: Kitchen Wall Lights
#    entities:
#      - light.kitchen_ceiling_light
#      - switch.kitchen_dining_light
#      - switch.kitchen_floor_led
#  kitchen_worktop_lights:
#    name: Kitchen Worktop Lights
#    entities:
#      - switch.kitchen_worktop_led_left
#      - switch.kitchen_worktop_led_right
#  master_room_ceiling_lights:
#    name: Master Room Ceiling Lights
#    entities:
#      - switch.master_room_bed_ceiling_light
#      - switch.master_room_landing_ceiling_light


#  # XiaoMi BLE Temperature Sensor
#sensor xiaomi_ble_slow:      
#  - platform: mitemp_bt
#    period: 60
#    encryptors:
#               # En-suite Room Temperature Sensor
#               'A4:C1:38:B0:EB:53': '71d88c34719d0708221d348fd14873dd'
#               # En-suite Toilet Temperature Sensor
#               'A4:C1:38:C2:C8:7A': '46244a59383e1183953324aed271cc32'
#               # Guest Room Temperature Sensor
#               'A4:C1:38:8C:F9:84': '996b9535497ced8bc997d5b6e209e74c'
#               # Master Room Temperature Sensor
#               #'A4:C1:38:CF:C7:01': ''
#               # Kitchen Temperature Sensor
#               #'A4:C1:38:0E:91:A7': 'f9696fa47ac23090eea383b520ff9a10'
#               # Living Room Temperature Sensor
#               'A4:C1:38:EC:DB:BA': '1b535cbb3e68651bd67157ee0775e5cb'
#               # Kitchen Worktop Temperature Sensor
#               #'58:2d:34:3b:6a:27'



    
