# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# TODO:
# * Replace emulated hue integration with the emulated hue addon - providing more ability to port lights to hue app
# use native alexa integration or matter

# Bug Fix (priority)
#   home assistant thinks it's offline because the wifi connection has a ping long latency

homeassistant:
  customize:    !include customize.yaml
  #######################################################
  # MOST OF CONFIGURATIONS ARE IN THE PACKAGE DIRECTORY #
  #######################################################
  packages:     !include_dir_named packages/
  internal_url: https://homeassistant.local:8123
  external_url: !secret duckdns_url

automation gui: !include automations.yaml
script gui:     !include scripts.yaml

# Front-end
frontend:
  themes: !include_dir_merge_named themes
  # Performance fix for card-mod card
  extra_module_url:
    - /config/www/community/lovelace-card-mod/card-mod.js

# Scene
scene: !include scenes.yaml


# check living room TV lost wifi for a while


# Render out list of automation that is on

# action: automation.turn_off
# target:
#  entity_id: 
#    {% for state in states.automation if state.state == 'on' %}
#    - {{ state.entity_id }}
#    {% endfor %}


