# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# TODO:
# !!!!! En-suite Toilet Door Has the wrong device !!!
# * bedside lights colour control by button
# * master room bed lights colour control by day in the week/mode/sleep etc
# * [HW] Fixed the living room light switches possibly by replacing a new smart switch
# * change all bedroom light colour on the time (using light state off->on as trigger)
# * blueprint instance for heating automation

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named _packages/
  internal_url: http://homeassistant.local:8123
  external_url: !secret duckdns_url


automation gui: !include automations.yaml
script gui: !include scripts.yaml


# Front-end
frontend:
  themes: !include_dir_merge_named themes

# Scene
scene: !include scenes.yaml



# HA_On_VMs needs to enable USB->Bluetooh
# Xiaomi BLE Round Fast Update Temperature Sensor
#sensor xiaomi_ble_fast:
#  - platform: mitemp_bt
#    period: 10 # seconds for refresh interval
#    sensor_names:
#      '58:2d:34:3b:6a:27': 'Kitchen Hob Temperature Sensor'

#xiaomi_aqara:
#  discovery_retry: 5
#  gateways: # XiaoMi Gateway
#    - key: 153EEFE707B24CFB
#      mac: 34CE008D7558

# Debug Homekit Integration
#logger:
#  default: warning
#  logs:
#    homeassistant.components.emulated_hue: debug
#    
# Install Mini Media Player
#resources:
#  - url: /local/mini-media-player-bundle.js?v=1.11.0
#    type: module

###########################################
# Light/Cover/Switch Groups
###########################################
# HA does not have switch group so have to use group as a workaround
#group tais_switch_group:
#  kitchen_wall_lights:
#    name: Kitchen Wall Lights
#    entities:
#      - light.kitchen_ceiling_light
#      - switch.kitchen_dining_light
#      - switch.kitchen_floor_led
#  kitchen_worktop_lights:
#    name: Kitchen Worktop Lights
#    entities:
#      - switch.kitchen_worktop_led_left
#      - switch.kitchen_worktop_led_right
#  master_room_ceiling_lights:
#    name: Master Room Ceiling Lights
#    entities:
#      - switch.master_room_bed_ceiling_light
#      - switch.master_room_landing_ceiling_light

#  # XiaoMi BLE Temperature Sensor
#sensor xiaomi_ble_slow:
#  - platform: mitemp_bt
#    encryptors:
#      # En-suite Room Temperature Sensor
#      'A4:C1:38:B0:EB:53': '71d88c34719d0708221d348fd14873dd'
#               
#               # En-suite Toilet Temperature Sensor
#               'A4:C1:38:C2:C8:7A': '46244a59383e1183953324aed271cc32'
#               # Guest Room Temperature Sensor
#               'A4:C1:38:8C:F9:84': '996b9535497ced8bc997d5b6e209e74c'
#               # Master Room Temperature Sensor
#               #'A4:C1:38:CF:C7:01': ''
#               # Kitchen Temperature Sensor
#               #'A4:C1:38:0E:91:A7': 'f9696fa47ac23090eea383b520ff9a10'
#               # Living Room Temperature Sensor
#               'A4:C1:38:EC:DB:BA': '1b535cbb3e68651bd67157ee0775e5cb'
#               # Kitchen Worktop Temperature Sensor
#               #'58:2d:34:3b:6a:27'

#  NAME:     Master Room Temperature Sensor 2 Xiaomi
#  ID:       blt.3.1467pp0eg5c00
#  BLE KEY:  5C9DA96F6F339A9D000C37749B2FE09A
#  TOKEN:    00A475CA3A37D4B4DACE8407
#  MODEL:    miaomiaoce.sensor_ht.t2
#  ---------
#  NAME:     En-suite Room Temperature Sensor
#  ID:       blt.3.146api6dklk00
#  BLE KEY:  BB13EF8420698DD987C97F9A7FF32536
#  TOKEN:    E8532EF2107F5241C0FAC84F
#  MODEL:    miaomiaoce.sensor_ht.t2
#  ---------
#  NAME:     Master Room Temperature Sensor 1 Xiaomi
#  ID:       blt.3.14b0ck638e000
#  BLE KEY:  3A7C3675CB8094BB1241D3E224F663CB
#  TOKEN:    4587BB420439B8967E86E403
#  MODEL:    miaomiaoce.sensor_ht.t2
#  ---------
#  NAME:     温湿度计3
#  ID:       blt.3.14b1d2obkeg01
#  BLE KEY:  d75f4a31ea1b2bfb1257f432b9bf1711
#  TOKEN:    470522e3206fb14df129b831
#  MODEL:    miaomiaoce.sensor_ht.t2
#  ---------
#  NAME:     Living Room Temperature Sensor Xiaomi
#  ID:       blt.3.14b4dbro4e800
#  BLE KEY:  7C0EA966C9A6E90024FC1D29710B4EE0
#  TOKEN:    C6A64B4F58A621797D158E58
#  MODEL:    miaomiaoce.sensor_ht.t2
#  ---------
#  NAME:     温湿度计2
#  ID:       blt.3.14c9qafe45s00
#  BLE KEY:  74bdbf1be34fcd5f16f44e8e99c1589c
#  TOKEN:    6c13db63db5724ee4473099e
#  MODEL:    miaomiaoce.sensor_ht.t2



