# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# TODO:
# * En-suite Toilet Door Has the wrong device
# * bedside lights colour control by button
# * master room bed lights colour control by day in the week/mode/sleep etc
# * [HW] Fixed the living room light switches possibly by replacing a new smart switch
# * change all bedroom light colour on the time (using light state off->on as trigger)
# * update heating blueprint so that mannual override in the first 2 mintues are not overwritten later
# * wall switch button double press - to shut down room applicances
# * en_suite room going to dark - turn on bed led
# * turn on/off guest room light based on motion sensor
# * Replace emulated hue integration with the emulated hue addon - providing more ability to port lights to hue app
#   - this does not support latest Hue app API V2


# Bug Fix (priority)
# * [YEELIGHT BAD WIFI MODULE] automatically turns off and back on for the wall switch lights to reset yeelight light state when
#   home assistant thinks it's offline because the wifi connection has a ping long latency
# * Guest Toilet light cannot be turned off by wall swtich at the moment (localtuya works as long as wifi is good)
# * Guest room light is not detected by motion sensor
# * Master Toilet Light colour is too white in the daytime
# * Living Room Temperature Sensor is out-of-order
# * En-suite Toilet Light group is unavaialble
# * light meter is broken - replace with sun as workaround for now [DONE]

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages/
  internal_url: https://homeassistant.local:8123
  external_url: !secret duckdns_url

automation gui: !include automations.yaml
script gui: !include scripts.yaml

# Front-end
frontend:
  themes: !include_dir_merge_named themes

# Scene
scene: !include scenes.yaml
# HA_On_VMs needs to enable USB->Bluetooh
# Xiaomi BLE Round Fast Update Temperature Sensor
#sensor xiaomi_ble_fast:
#  - platform: mitemp_bt
#    period: 10 # seconds for refresh interval
#    sensor_names:
#      '58:2d:34:3b:6a:27': 'Kitchen Hob Temperature Sensor'

#xiaomi_aqara:
#  discovery_retry: 5
#  gateways: # XiaoMi Gateway
#    - key: 153EEFE707B24CFB
#      mac: 34CE008D7558

# Debug Homekit Integration
#logger:
#  default: warning
#  logs:
#    homeassistant.components.emulated_hue: debug
#
