
#-------------------
# Last Alexa Sensor
#-------------------
group:
  all_echos:
    name: All Echos
    entities:
      - media_player.master_room_echo
      - media_player.kitchen_echo
      - media_player.living_room_echo

template:
  - sensor:
      - name: Last Alexa
        # entity_id: last_alexa
        state: >
          {{ expand('group.all_echos') | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first | replace('media_player.','') | replace('_echo','') }}
        availability: >
          {{ expand('group.all_echos') | selectattr('attributes.last_called','eq',True) | first is defined }}

#----------------
# Alexa entities
#----------------
group alexa:
  living_room_floor_light:
    name: Living Room Floor Light
    entities:
      - light.living_room_floor_light_1
      - light.living_room_floor_light_2
      - switch.living_room_floor_light_3

#----------------
# Emulated Hue
#----------------
#emulated_hue:
#  listen_port: 80
#  expose_by_default: false
#  # Make sure "hidden:false" is always attached - otherwise HA would not be found the devices
#  # N.B.
#  # As per Emulated Hue documentation, ONLY UP TO 49 DEVICES can be supported by this integration.
#  # There are 29 devices below + 11 physical devices on Hue bridge
#  entities:
#    ###################################
#    # HA script - using a fake light brightness to call scripts - 1 devices
#    ###################################
#    light.emulated_hue_ha_script_index_from_alexa:
#      name: "HA Script Index From Alexa"
#      hidden: false
#    ###################################
#    # Non-light Devices - 0 devices
#    ###################################
#    ###################################
#    # Master Room  - 8 devices
#    ###################################
#    # Alexa, set the Master Room Thermostat to 23
#    light.master_room_lamp_1:
#      name: "Master Room Left Lamp"
#      hidden: false
#    light.master_room_lamp_2:
#      name: "Master Room Right Lamp"
#      hidden: false
#    light.master_room_ceiling_lights:
#      name: "Master Room Ceiling Light"
#      hidden: false
#    light.master_room_leds:
#      name: "Master Room LED"
#      hidden: false
#    switch.master_room_dressing_table_light:
#      name: "Master Room Dressing Table Light"
#      hidden: false
#    ###################################
#    # Master Toilet  - 2 devices
#    ###################################
#    light.master_toilet_ceiling_light:
#      name: "Master Toilet Ceiling Light"
#      hidden: false
#    switch.master_toilet_floor_led:
#      name: "Master Toilet Floor LED"
#      hidden: false
#    ###################################
#    # Guest Room  - 1 devices
#    ###################################
#    light.guest_room_ceiling_light:
#      name: "Guest Room Ceiling Light"
#      hidden: false
#    ###################################
#    # Living Room - 4 devices
#    ###################################
#    light.living_room_led:
#      name: "Living Room LED"
#      hidden: false
#    group.living_room_floor_light:
#      name: "Living Room Floor Light"
#      hidden: false
#    light.living_room_ceiling_light:
#      name: "Living Room Ceiling Light"
#      hidden: false
#    # Garden
#    switch.garden_wall_light:
#      name: "Garden Light"
#      hidden: false
#    ###################################
#    # Kitchen - 5 devices
#    ###################################
#    light.kitchen_ceiling_light:
#      name: "Kitchen Ceiling Light"
#      hidden: false
#    light.kitchen_dining_light:
#      name: "Kitchen Dining Light"
#      hidden: false
#    switch.kitchen_floor_led:
#      name: "Kitchen Floor LED"
#      hidden: false
#    ###################################
#    # Ground Toilet - 1 devices
#    ###################################
#    #light.ground_toilet_ceiling_light:
#    #  name: "Ground Toilet Ceiling Light"
#    #  hidden: false
#    ###################################
#    # Study - 1 devices
#    ###################################
#    light.study_ceiling_light:
#      name: "Study Ceiling Light"
#      hidden: false
#    ###################################
#    # En-suite Room - 6 devices
#    ###################################
#    light.en_suite_room_ceiling_light:
#      name: "En-suite Room Ceiling Light"
#      hidden: false
#    light.en_suite_room_bed_led:
#      name: "En-suite Room Bed LED"
#      hidden: false
#    light.en_suite_room_lamp_2:
#      name: "En-suite Room Left Lamp"
#      hidden: false
#    light.en_suite_room_lamp_1:
#      name: "En-suite Room Right Lamp"
#      hidden: false

cloud:
  alexa:
    filter:
      include_entities:
      - light.master_room_lamp_1
      - light.master_room_lamp_2
      - light.master_room_ceiling_light
      - light.master_room_leds
      - switch.master_room_dressing_table_light
      - cover.master_room_curtain
      - cover.master_room_blind
        ###################################
        # Master Toilet  - 2 devices
        ###################################
      - light.master_toilet_ceiling_light
      - switch.master_toilet_floor_led
        ###################################
        # Guest Room  - 1 devices
        ###################################
      - light.guest_room_ceiling_light
        ###################################
        # Living Room - 4 devices
        ###################################
      - light.living_room_led
      - light.living_room_floor_light_1
      - light.living_room_floor_light_2
      - light.living_room_ceiling_light
      - switch.living_room_floor_light_3
      - switch.tais_desk_screen_led
      - switch.garden_wall_light
        ###################################
        # Kitchen - 5 devices
        ###################################
      - light.kitchen_ceiling_light
      - light.kitchen_dining_light
      - group.kitchen_worktop_leds
      - switch.kitchen_floor_led
      - cover.kitchen_curtain
        ###################################
        # Ground Toilet - 1 devices
        ###################################
        #light.ground_toilet_ceiling_light:
        #  name: "Ground Toilet Ceiling Light"
        ###################################
        # Study - 1 devices
        ###################################
      - light.study_ceiling_light
        ###################################
        # En-suite Room - 6 devices
        ###################################
      - light.en_suite_room_ceiling_light
      - light.en_suite_room_bed_led
      - light.en_suite_room_lamp_2
      - light.en_suite_room_lamp_1
      - cover.en_suite_room_curtain
    entity_config:
      light.emulated_hue_ha_script_index_from_alexa:
        name: "HA Script Index From Alexa"
      # Alexa, set the Master Room Thermostat to 23
      light.master_room_lamp_1:
        name: "Master Room Left Lamp"
      light.master_room_lamp_2:
        name: "Master Room Right Lamp"
      light.en_suite_room_lamp_2:
        name: "En-suite Room Left Lamp"
      light.en_suite_room_lamp_1:
        name: "En-suite Room Right Lamp"
  
automation:
  - alias: E- Emulated Hue Alexa->HA Script
    id: "1939270046562"
    trigger:
      #- platform: state
      #  entity_id: light.emulated_hue_ha_script_index_from_alexa
      #  from: "off"
      #  to: "on"
      - platform: state
        entity_id: light.emulated_hue_ha_script_index_from_alexa
        attribute: brightness
    mode: single
    action:
      # Delay for a bit for the brightness value to be up-to-date
      - delay: "00:00:02"

      - service: pyscript.alexa_call_ha_script
        data:
          # when alexa sets brightness less than 89, HA needs to round up
          # any decimal points of brightness to up despite it's less than 0.5
          script_index: "{{ ((state_attr('light.emulated_hue_ha_script_index_from_alexa', 'brightness')*100/255))|round(0, 'ceil')}}"

      # Restore the default value and delay for a bit
      - delay: "00:00:02"
      - service: light.turn_on
        entity_id: light.emulated_hue_ha_script_index_from_alexa
        data:
          brightness_pct: 1
      - service: light.turn_off
        entity_id: light.emulated_hue_ha_script_index_from_alexa

# Switches for Emulated Hue
switch emulated_hue:
  - platform: template
    switches:
      master_room_blind:
        value_template: "{{ is_state('cover.master_room_blind', 'open') }}"
        turn_on:
          service: cover.open_cover
          target:
            entity_id: cover.master_room_blind
        turn_off:
          service: cover.close_cover
          target:
            entity_id: cover.master_room_blind

      master_room_curtain:
        value_template: "{{ is_state('cover.master_room_curtain', 'open') }}"
        turn_on:
          service: cover.open_cover
          target:
            entity_id: cover.master_room_curtain
        turn_off:
          service: cover.close_cover
          target:
            entity_id: cover.master_room_curtain

# Fake Light - using its brightness to call scripts from customized Alexa commands
light:
  - platform: template
    lights:
      emulated_hue_ha_script:
        friendly_name: "Emulated Hue HA Script 1"
        turn_on:
          service: script.do_nothing
        turn_off:
          service: script.do_nothing
        set_level:
          service: script.do_nothing
        set_temperature:
          service: script.do_nothing
        #set_white_value:
        #  service: script.do_nothing
        set_color:
          service: script.do_nothing

  # Sometimes HA script Light Needs to be re-instantiated
  - platform: group
    name: Emulated Hue HA Script Index From Alexa
    entities:
      #- light.emulated_hue_ha_script
      - light.tuya_virtual_light
#script:
#  alexa_set_tv_brightness_to_dynamic:
#    sequence:
#      - service: pyscript.alexa_set_tv
#        data:
#          action: "brightness"
#          brightness: "Dynamic"
#
#  alexa_set_tv_brightness_to_standard:
#    sequence:
#      - service: pyscript.alexa_set_tv
#        data:
#          action: "brightness"
#          brightness: "Standard"
#
#  alexa_set_tv_brightness_to_natural:
#    sequence:
#      - service: pyscript.alexa_set_tv
#        data:
#          action: "brightness"
#          brightness: "Natural"
#
#  alexa_set_tv_brightness_to_movie:
#    sequence:
#      - service: pyscript.alexa_set_tv
#        data:
#          action: "brightness"
#          brightness: "Movie"
#
#  turn_on_gaming_pc:
#    sequence:
#      - service: switch.turn_on
#        entity_id: switch.gaming_pc
#
#  turn_off_gaming_pc:
#    sequence:
#      - service: switch.turn_off
#        entity_id: switch.gaming_pc
#
#  turn_on_old_laptop:
#    sequence:
#      - service: switch.turn_on
#        entity_id: switch.old_laptop
#
#  turn_off_old_laptop:
#    sequence:
#      - service: switch.turn_off
#        entity_id: switch.old_laptop
#
#  doorbell_notify_ha_users:
#    sequence:
#      - service: script.do_nothing #TODO
#
#  alexa_turn_off_tv:
#    sequence:
#      - service: pyscript.alexa_set_tv
#        data:
#          action: "power"
#          power: "off"
#
#  alexa_turn_on_tv:
#    sequence:
#      - service: pyscript.alexa_set_tv
#        data:
#          action: "power"
#          power: "on"

