
automation:
#    - alias: H-Downstairs Zone Heating On When Heating Required
#      id: downstairs_zone_heating_on
#      trigger:
#        - platform: state
#          entity_id:
#            - group.downstairs_heating_required
#        - minutes: /5
#          platform: time_pattern
#      condition:
#        - condition: state
#          entity_id: group.downstairs_heating_required
#          state: "on"
#      action:
#        - service: switch.turn_on
#          entity_id: switch.downstairs_heating
#
#    - alias: H-Downstairs Zone Heating Off When No Heating Required
#      id: downstairs_zone_heating_off
#      trigger:
#        - platform: state
#          entity_id:
#            - group.downstairs_heating_required
#        - minutes: /5
#          platform: time_pattern
#      condition:
#        - condition: and
#          conditions:
#            - condition: state
#              entity_id: group.downstairs_heating_required
#              state: "off"
#              # Reduce the frequency of turning off the boiler - to increase lifetime of the boiler
#              for: '00:10:00'
#      action:
#        - service: switch.turn_off
#          entity_id: switch.downstairs_heating
#
#    - alias: H-Upstairs Zone Heating On When Heating Required
#      id: upstairs_zone_heating_on
#      trigger:
#        - platform: state
#          entity_id:
#            - group.upstairs_heating_required
#        - minutes: /5
#          platform: time_pattern
#      condition:
#        - condition: state
#          entity_id: group.upstairs_heating_required
#          state: "on"
#      action:
#        - service: switch.turn_on
#          entity_id: switch.upstairs_heating
#
#    - alias: H-Upstairs Zone Heating Off When No Heating Required
#      id: upstairs_zone_heating_off
#      trigger:
#        - platform: state
#          entity_id:
#            - group.upstairs_heating_required
#        - minutes: /5
#          platform: time_pattern
#      condition:
#        - condition: and
#          conditions:
#            - condition: state
#              entity_id: group.upstairs_heating_required
#              state: "off"
#              # Reduce the frequency of turning off the valve - to increase lifetime of the valve
#              for: '00:10:00'
#      action:
#        - service: switch.turn_off
#          entity_id: switch.upstairs_heating
#

# Downstairs valves stopped working, using upstairs to work around

    - alias: H-Workaround Upstairs/Downstair Zone Heating Off When No Heating Required
      id: workaround_zone_heating_off
      trigger:
        - platform: state
          entity_id:
          - group.upstairs_heating_required
          - group.downstairs_heating_required
        - minutes: /5
          platform: time_pattern
      condition:
      - condition: and
        conditions:
        - condition: state
          entity_id:
            - group.downstairs_heating_required
          state: "off"
          # Reduce the frequency of turning off the valve - to increase lifetime of the valve
          for: '02:00:00'
        - condition: state
          entity_id:
            - group.upstairs_heating_required
          state: "off"
          for: '02:00:00'
      action:
        - service: switch.turn_off
          entity_id: switch.upstairs_heating

    - alias: H-Workaround Upstairs/Downstairs Zone Heating On When Heating Required
      id: workaround_zone_heating_on
      trigger:
        - platform: state
          entity_id:
          - group.upstairs_heating_required
          - group.downstairs_heating_required
        - minutes: /5
          platform: time_pattern
      condition:
      - condition: or
        conditions:
        - condition: state
          entity_id: group.upstairs_heating_required
          state: "on"
        - condition: state
          entity_id: group.downstairs_heating_required
          state: "on"
      action:
        - service: switch.turn_on
          entity_id: switch.upstairs_heating

  ###############################################
  # Water Heating Automation based on motion sensors
  ###############################################
    - alias: W-DS Water Heater Start For 2 Hour And Schedule On If People Back From Journey
      id: "1600016351670"
      description: "automation.water_heater_start_and_schedule_on_if_people_back_from_journey"
      trigger:
        - platform: state
          to: "on"
          entity_id: group.indoor_motion
      condition: []
      mode: single
      action:
        - service: automation.turn_off
          entity_id: automation.water_heater_start_and_schedule_on_if_people_back_from_journey
          data:
            stop_actions: false
        - service: switch.turn_on
          entity_id: switch.water_heater
        # Delay turning on the scheudle so the water heater
        # does not get turn off by schedule until the water
        # has been heated for 2 hours
        - delay: 02:00:00
        - service: switch.turn_on
          entity_id: switch.schedule_water_heater

    - alias: W-DS Water Heater Schedule Off If People On Journey
      id: "1600016351671"
      description: ""
      trigger:
        - minutes: /5
          platform: time_pattern
      condition:
        - condition: state
          state: "off"
          for: 23:30:00
          entity_id: group.indoor_motion
      action:
        - service: switch.turn_off
          entity_id: switch.schedule_water_heater
        - service: automation.turn_on
          entity_id: automation.water_heater_start_and_schedule_on_if_people_back_from_journey
