#
# - service: script.notify_alexa_speakers_and_phones
#   data:
#     tts_message: 'hello'
#     notify_tai: yes
#     notify_ke: yes
#     notify_alvaro: yes
#     alexa_speaker_list:
#     - media_player.kitchen_echo
#     - media_player.living_room_echo
#

script:
  notify_alexa_speakers_and_phones:
    fields:
      tts_message:
        example: "test"
      alexa_speaker_list:
        default: no
        example: "- media_player.kitchen_echo"
      notify_tai:
        default: no
        example: "yes"
      notify_ke:
        default: no
      notify_guest_room_tenant:
        default: no
      notify_en_suite_room_tenant:
        default: no
    sequence:
      - parallel:
          - if:
              - "{{alexa_speaker_list != no and alexa_speaker_list != 'no'}}"
            then:
              - service: notify.alexa_media
                data:
                  message: "{{tts_message}}"
                  target: "{{alexa_speaker_list}}"
                  title: Home Assistant Message
                  data:
                    method: all
                    type: announce
          - if:
              - "{{notify_kes_dad == 'yes'}}"
            then:
              - if:
                  - condition: state
                    entity_id: input_boolean.kes_dad_notification_enable
                    state: "on"
                then:
                  - service: notify.mobile_app_ke_ba_ba_shou_ji
                    data:
                      message: "{{tts_message}}"
                      data:
                        push:
                          name: default
                          critical: 1
                          volume: 1
          - if:
              - "{{notify_kes_mom == 'yes'}}"
            then:
              - if:
                  - condition: state
                    entity_id: input_boolean.kes_notification_enable
                    state: "on"
                then:
                  - service: notify.mobile_app_ke_ma_ma_shou_ji
                    data:
                      message: "{{tts_message}}"
                      data:
                        push:
                          name: default
                          critical: 1
                          volume: 1
          - if:
              - "{{notify_tai == 'yes'}}"
            then:
              - if:
                  - condition: state
                    entity_id: input_boolean.tais_notification_enable
                    state: "on"
                then:
                  - service: notify.mobile_app_tais_iphone_14_pro_max
                    data:
                      message: "{{tts_message}}"
                      data:
                        push:
                          name: default
                          critical: 1
                          volume: 1
          - if:
              - "{{notify_ke == 'yes'}}"
            then:
              - if:
                  - condition: state
                    entity_id: input_boolean.kes_notification_enable
                    state: "on"
                then:
                  - service: notify.mobile_app_kes_iphone_14_pro_max
                    data:
                      message: "{{tts_message}}"
                      data:
                        push:
                          name: default
                          critical: 1
                          volume: 1
          - if:
              - "{{notify_guest_room_tenant == 'yes'}}"
            then:
              - service: notify.mobile_app_rotom
                data:
                  message: "{{tts_message}}"
                  data:
                    push:
                      name: default
                      critical: 1
                      volume: 1
          - if:
              - "{{notify_en_suite_room_tenant == 'yes'}}"
            then:
              - service: notify.mobile_app_fares_pixel_5
                data:
                  message: "{{tts_message}}"
                  data:
                    push:
                      name: default
                      critical: 1
                      volume: 1

input_boolean:
  tais_notification_enable:
    name: "Tai's Notification Enable"
  kes_notification_enable:
    name: "Ke's Notification Enable"
  kes_mom_notification_enable:
    name: "Ke's Mom Notification Enable"
  kes_dad_notification_enable:
    name: "Ke's Dad Notification Enable"

automation:
  - alias: "N- Reminding Washing Machine Completed - Tai/Ke/Amazon Speaker"
    id: "1679255860573"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.washing_machine_power
        from: "on"
        to: "off"
        for:
          hours: 0
          minutes: 3
          seconds: 0
    condition: []
    action:
      - service: script.notify_alexa_speakers_and_phones
        data:
          tts_message: 洗衣机里的衣服洗好了。Washing machine cycle completed!
          notify_tai: "yes"
          notify_kes_dad: "yes"
          notify_kes_mom: "yes"
          notify_ke: "yes"
          notify_guest_room_tenant: "yes"
          notify_en_suite_room_tenant: "yes"
          alexa_speaker_list:
            - media_player.kitchen_echo
    mode: single

  - alias: "N- Reminding Turn Off Feeding Bottle Warmer"
    id: "fdasjklfdjkslafjkldsakgvbnkfdanbklfd"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.feeding_bottle_warmer
        from: "off"
        to: "on"
        for:
          hours: 0
          minutes: 20
          seconds: 0
    action:
      - service: script.notify_alexa_speakers_and_phones
        data:
          tts_message: 暖奶器已经工作了20分钟。已经自动关闭。如果需要长时间暖奶，不需要自动关闭，和李泰说让他只提醒你但不关闭。
          notify_tai: "yes"
          notify_kes_dad: "yes"
          #notify_kes_mom: "yes"
          notify_ke: "yes"
      - service: switch.turn_off
        entity_id: switch.feeding_bottle_warmer
      - delay: "00:00:01"
      - service: switch.turn_on
        entity_id: switch.feeding_bottle_warmer
    mode: single

  - alias: "N- Alert - Ring Doorbell Baterry Low"
    id: "9324832fjkdlsa302"
    trigger:
      - platform: time
        at: "19:00:00"
    condition:
      - condition: numeric_state
        entity_id: sensor.front_door_battery
        below: 20
    action:
      - service: script.notify_alexa_speakers_and_phones
        data:
          tts_message: 门铃电量低于20%。Ring Doorbell Baterry Low! Please charge it.
          notify_tai: "yes"
          notify_kes_dad: "yes"
          notify_kes_mom: "yes"
          notify_ke: "yes"
          notify_guest_room_tenant: "yes"
          notify_en_suite_room_tenant: "yes"
          #alexa_speaker_list:
          #  - media_player.master_room_echo
    mode: single

  #  - alias: "N- Reminder - Take folic acid"
  #    id: "16794325560571"
  #    trigger:
  #      - platform: time
  #        at: "11:00:00"
  #    action:
  #      - service: script.notify_alexa_speakers_and_phones
  #        data:
  #          tts_message: Take folic acid
  #          #notify_tai: "yes"
  #          notify_ke: "yes"
  #          #alexa_speaker_list:
  #          #  - media_player.master_room_echo
  #    mode: single

  - alias: "N- Doorbell is pressed - Tai/Ke's family"
    id: "fdasjfkldaslfjdlsajfkldsakljfdklsjflkdjk43298432980483902"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door_ding
        from: "off"
        to: "on"
    action:
      - service: script.notify_alexa_speakers_and_phones
        data:
          tts_message: 有人按门铃。Someone rang the doorbell.
          #notify_tai: "yes"
          notify_kes_dad: "yes"
          notify_kes_mom: "yes"
          notify_ke: "yes"
          notify_guest_room_tenant: "yes"
          notify_en_suite_room_tenant: "yes"
    mode: single

  - alias: "N- Alert - Hot water schedule is not working - Tai"
    id: "16794321343213"
    trigger:
      - platform: time
        at: "05:05:00"
      - platform: time
        at: "16:05:00"
    action:
      - condition: state
        state: "off"
        entity_id: switch.water_heater
      - service: script.notify_alexa_speakers_and_phones
        data:
          tts_message: Hot water schedule is not working. Manually turning it on.
          notify_tai: "yes"
          #notify_ke: "yes"
          #alexa_speaker_list:
          #  - media_player.master_room_echo
      - service: switch.turn_on
        entity_id: switch.water_heater
      - delay: "01:00:00"
      - service: switch.turn_off
        entity_id: switch.water_heater

  - alias: "N- Reminding Bin Collection - Tai/Ke/Amazon Speaker"
    id: bin_collect_reminder
    description: ""
    trigger:
      - platform: calendar
        event: start
        offset: "-12:0:0"
        entity_id: calendar.bins_schedule
    condition: []
    action:
      - wait_for_trigger:
          - platform: state
            entity_id:
              - group.corridor_motion_group
              - group.master_room_motion_group
              - group.master_toilet_motion_group
              - group.living_room_motion_group
              - group.kitchen_motion_group
            to: "on"
        timeout:
          hours: 9
          minutes: 0
          seconds: 0
          milliseconds: 0
      - service: script.notify_alexa_speakers_and_phones
        data:
          tts_message: |
            明天是{% if state_attr('calendar.bins_schedule', 'message') == 'Black Bin Collection' %}黑色不可回收垃圾桶回收日{% else %}蓝色可回收垃圾桶回收日{% endif %}。Tomorrow is {{state_attr('calendar.bins_schedule', 'message')}} date.
          #notify_tai: "yes"
          notify_kes_dad: "yes"
          notify_kes_mom: "yes"
          notify_ke: "yes"
          notify_tai: "yes"
          notify_guest_room_tenant: "yes"
          notify_en_suite_room_tenant: "yes"
          alexa_speaker_list:
            - media_player.kitchen_echo
            - media_player.living_room_echo
            - media_player.master_room_echo
            - media_player.master_toilet_echo
    mode: single
