# Helper sensors for detecting requirement for downstairs/upstairs heating

group:
  upstairs_heating_required:
    name: "Upstairs Heating Required"
    entities:
      - binary_sensor.master_toilet_heating_required
      - binary_sensor.master_room_heating_required
      - binary_sensor.guest_toilet_heating_required
      - binary_sensor.guest_room_heating_required
      - binary_sensor.en_suite_toilet_heating_required
      - binary_sensor.en_suite_room_heating_required
      - binary_sensor.study_heating_required

  downstairs_heating_required:
    name: "Downstairs Heating Required"
    entities:
      - binary_sensor.kitchen_heating_required
      - binary_sensor.living_room_heating_required
      - binary_sensor.ground_toilet_heating_required
      - binary_sensor.corridor_heating_required

binary_sensor:
  - platform: group
    name: "Tado Battery States"
    entities:
      - binary_sensor.va0395514880_battery_state
      - binary_sensor.va0429069312_battery_state
      - binary_sensor.va0781390848_battery_state
      - binary_sensor.va0932385792_battery_state
      - binary_sensor.va1049826304_battery_state
      - binary_sensor.va1167266816_battery_state
      - binary_sensor.va1217598464_battery_state
      - binary_sensor.va2241008640_battery_state
      - binary_sensor.va2282557696_battery_state
      - binary_sensor.va2895320064_battery_state
      - binary_sensor.va3314750464_battery_state
      - binary_sensor.va3767669760_battery_state
      - binary_sensor.va4111274240_battery_state
      - binary_sensor.va4136768512_battery_state
      
# Temperature Sensor
#template:
#  - sensor:
#      - name: "Living Room Button Template"
#        state: >
#          {{ states('sensor.living_room_button') }}  
  
      #      - name: "Master Room Temperature Sensor Backup1"
      #        unit_of_measurement: "°C"
      #        state: >
      #          {{ states('sensor.582d343b6a27_temperature') | float | round(1) }}
      #
      #      - name: "Master Room Temperature Sensor Backup2"
      #        unit_of_measurement: "°C"
      #        state: >
      #          {{ states('sensor.a4c138ecdbba_temperature') | float | round(1) }}

      #      - name: "Master Room Temperature Sensor"
      #        unit_of_measurement: "°C"
      #        state: >
      #          {% if   states('sensor.master_room_temperature_sensor_backup1') != 'unavailable' and
      #                  states('sensor.master_room_temperature_sensor_backup2') == 'unavailable'     %}
      #                 {{states('sensor.master_room_temperature_sensor_backup1')}}
      #          {% elif states('sensor.master_room_temperature_sensor_backup2') == 'unavailable' and
      #                  states('sensor.master_room_temperature_sensor_backup2') != 'unavailable'     %}
      #                {{states('sensor.master_room_temperature_sensor_backup2')}}
      #          {% else %}
      #              {% set sensor_1 = states('sensor.master_room_temperature_sensor_backup1') | float | round(1) %}
      #              {% set sensor_2 = states('sensor.master_room_temperature_sensor_backup2') | float | round(1) %}
      #              {% if sensor_1 < 1.0 or sensor_2 < 1.0 or (sensor_1 + sensor_2) < 1.0 %}
      #                    22.0
      #              {% else %}
      #                   {{ ((sensor_1 + sensor_2) / 2) | round(1) }}
      #              {% endif %}
      #          {% endif %}

#      - name: "Kitchen Temperature Sensor"
#        unit_of_measurement: "°C"
#        state: >
#          {{ states('sensor.temp_sensor_2_a4c1380e91a7_temperature') | float | round(1) }}

#      - name: "Living Room Temperature Sensor"
#        unit_of_measurement: "°C"
#        state: >
#          {{ states('sensor.temperature_humidity_sensor_2ab7_temperature') | float | round(1) }}#

