automation:
  #  - alias: T-KC Kitchen Vacuum Starts At 4am
  #    id: 3r2u9fjefkjdisofjoidsaklds
  #    description: ""
  #    trigger:
  #      - at: 04:00:00
  #        platform: time
  #    condition:
  #    action:
  #      - service: vacuum.start
  #        entity_id: vacuum.xiaomi_vacuum_cleaner

  - alias: VN-KC Remember to Refill Kitchen Vacuum Water when Going to Kitchen
    id: nvdiasojfoewnfdjsaf
    mode: single
    trigger:
      - platform: state
        entity_id:
          - group.kitchen_motion_group
          - group.living_room_motion_group
    condition:
      - condition: state
        entity_id: sensor.x1_last_error
        state: "301"
    action:
      - service: script.notify_alexa_speakers_and_phones
        data:
          tts_message: Clean Water in the Vacuum Robot Dock Has Run Out. 扫地机器人清水用完了，记得加清水。
          notify_tai: "yes"
          notify_ke_ba_ba: "yes"
          notify_ke_ma_ma: "yes"
          notify_ke: "yes"
          #notify_alvaro: "yes"
          alexa_speaker_list:
            - media_player.kitchen_echo
            - media_player.living_room_echo
      - delay: "04:00:00"

  - alias: V-KC Ask X1 To Return To Dock If Stuck
    id: 3902jgfrngfd89bvfdsjkfdjiafuew
    description: ""
    trigger:
      - platform: time_pattern
        minutes: "10"
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: vacuum.x1
            state: idle
            for: "00:05:00"
          - condition: state
            entity_id: vacuum.x1
            state: unknown
            for: "00:05:00"
          - condition: state
            entity_id: vacuum.x1
            state: paused
            for: "00:05:00"
          - condition: state
            entity_id: vacuum.x1
            state: unavailable
            for: "00:05:00"
    action:
      - service: vacuum.return_to_base
        data: {}
        target:
          entity_id: vacuum.x1
    mode: single

  - alias: VB-KC Kitchen Vacuum Toggle by Pressing The Rightmost 2 Buttons
    id: 3492849032uriojewjfreau8fef
    mode: single
    trigger:
      - platform: state
        entity_id:
          - sensor.kitchen_wall_button
        to: button_both_23_single
    condition: []
    action:
      - if:
          - condition: state
            entity_id: vacuum.x1
            state: cleaning
        then:
          - service: vacuum.stop
            target:
              entity_id: vacuum.x1
          - delay: "00:00:01"
          - service: vacuum.return_to_base
            target:
              entity_id: vacuum.x1
        else:
          # Clean Kitchen
          - service: vacuum.send_command
            target:
              entity_id: vacuum.x1
            data:
              command: spot_area
              params:
                rooms: 0
                cleanings: 1
#script:
#  kitchen_window_left_open_critical_notification:
#    alias: Kitchen Window Left Open Critical Notification
#    sequence:
#      - service: notify.mobile_app_tais_iphone_13_pro_max
#        data:
#          message: Kitchen Window Left Open
#          data:
#            push:
#              name: default
#              critical: 1
#              volume: 1
#

