def default_entity_interface():
  return {
    "automation_list": [],
    "entity_declarations": {},
    "input_select_dict": {},
    "sensor_list": [],
    "group_dict": {},
    "timer_dict": {},
    "button_list": [],
    "input_boolean_dict": {},
    "input_datetime_dict": {},
    "input_number_dict": {},
    "script_dict": {},
    "switch_list": [],
    "cover_list": [],
    "template_list": [],
    "climate_list": [],
    "binary_sensor_list": [],
    "event_list": [],
    "lock_list": [],
    "light_list": [],
    "room_cards": [],
    "views": [],
    "dashboard_type": None,
    "header_card_list": [],
    "main_card_list": [],
    "tail_card_list": [],
    "al_light_list": [],
    "gui_ctl_entity_list": [],
    "customize_dict": {},
  }


def build_entity_declarations(
  al_light_list,
  automation_list,
  input_select_dict,
  input_boolean_dict,
  input_datetime_dict,
  input_number_dict,
  sensor_list,
  timer_dict,
  button_list,
  switch_list,
  cover_list,
  climate_list,
  template_list,
  binary_sensor_list,
  event_list,
  lock_list,
  light_list,
  group_dict,
):
  return {
    "adaptive_lighting": al_light_list,
    'automation': automation_list,
    "input_select": input_select_dict,
    "input_boolean": input_boolean_dict,
    "input_datetime": input_datetime_dict,
    "input_number": input_number_dict,
    "sensor": sensor_list,
    "timer": timer_dict,
    "button": button_list,
    "switch": switch_list,
    "cover": cover_list,
    "climate": climate_list,
    "template": template_list,
    "binary_sensor": binary_sensor_list,
    "event": event_list,
    "lock": lock_list,
    "light": light_list,
    'group': group_dict,
  }
