alias: New Automation 45324321
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.0x04cf8cdf3c797717_0x04cf8cdf3c797717_action
    id: button_2_single
    to: button_2_single
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - button_2_single
        sequence:
          - service: light.toggle
            metadata: {}
            data: {}
            target:
              entity_id: light.study_ceiling_light
mode: single
