description: ""
mode: restart
trigger:
  - platform: state
    entity_id: input_boolean.ground_toilet_heating_override
    from: "off"
    to: "on"
action:
  - delay:
      hours: 3
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: homeassistant.turn_off
    entity_id: input_boolean.ground_toilet_heating_override
