
timer:
  study_auto_off_suspended_timer:
    name: Study Auto Off Suspended Timer
    duration: "03:00:00"   

input_boolean:
  study_auto_off_suspended:
    name: Study Auto Off Suspended
    icon: mdi:timer-sand    

automation:
  - alias: Timer control from input boolean
    mode: single
    trigger:
      - platform: state
        entity_id: input_boolean.study_auto_off_suspended
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.study_auto_off_suspended
                state: "on"
            sequence:
              - service: timer.start
                target:
                  entity_id: timer.study_auto_off_suspended_timer
          - conditions:
              - condition: state
                entity_id: input_boolean.study_auto_off_suspended
                state: "off"
            sequence:
              - service: timer.pause
                target:
                  entity_id: timer.study_auto_off_suspended_timer


  - alias: Sync input boolean with timer state
    mode: single
    trigger:
      - platform: state
        entity_id: timer.study_auto_off_suspended_timer
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: timer.study_auto_off_suspended_timer
                state: "active"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.study_auto_off_suspended
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: timer.study_auto_off_suspended_timer
                    state: "paused"
                  - condition: state
                    entity_id: timer.study_auto_off_suspended_timer
                    state: "idle"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.study_auto_off_suspended
