alias: test - living room button
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.living_room_wall_button
    to:
      - "1"
      - single
      - single_left
      - single_right
      - single_center
      - button_1_single
      - button_2_single
      - button_3_single
action:
  - if:
      - condition: state
        entity_id: light.living_room_ceiling_light
        state: unavailable
    then:
      - service: homeassistant.toggle
        entity_id: switch.living_room_wall_switch
    else:
      - service: homeassistant.toggle
        entity_id: light.living_room_ceiling_light
