blueprint:
  name: Test blueprint
  domain: automation
  input:
    binary_sensor_motion_sensor_list:
      name: Motion sensor list
#    extra_steps:
#      name: extra steps


trigger:
  - entity_id: 
      !input binary_sensor_motion_sensor_list
    platform: state
    from: "off"
    to: "on"

action:    
  - service:   light.turn_on
    entity_id: light.master_room_leds  