# En-suite Room
# En-suite Toilet
# - Lighting/Heating automation
# - Lighting automation based on motion sensors
# - Lighting automation based on buttons
# - Maintaince on bedroom automation based on presence

###############################################
#
# Heating Automation based on motion sensors
#
###############################################

# En-suite Room
- alias: HL-ER En-suite Room Lights/Heating Off If No Person
  id: '1603640029651'
  description: ''
  trigger:
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:15:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: or
    conditions:
    # IF - in daytime, turn off lighting/heating if no person for 15 min
    - condition: and
      conditions:
      - after:  '10:00:00'
        before: '22:00:00'
        condition: time
      - condition: state
        entity_id: binary_sensor.en_suite_room_motion_sensor_motion
        for: 00:15:00
        state: 'off'
    # ELSEIF - in nighttime, if no people live in the room,
    #          turn off lighting/heating if no person for 15 min
    - condition: and
      conditions:
      - after:  '22:00:00'
        before: '10:00:00'
        condition: time
      - condition: state
        entity_id: binary_sensor.en_suite_room_motion_sensor_motion
        state: 'off'
        for: 00:15:00
      - condition: state
        entity_id: input_boolean.en_suite_room_guests_use_this_room
        state: 'off'
    # ELSEIF - in nighttime, if people live in the room
    #          turn off lighting/heating if no person for 2 hours
    - condition: and
      conditions:
      - after:  '22:00:00'
        before: '10:00:00'
        condition: time
      - condition: state
        entity_id: binary_sensor.en_suite_room_motion_sensor_motion
        state: 'off'
        for: 02:00:00
      - condition: state
        entity_id: input_boolean.en_suite_room_guests_use_this_room
        state: 'on'
  action:
  # Turn Off Lights and Turn On Auto Lights-up
  - service: script.en_suite_room_all_lights_turn_off
  - service: automation.turn_on
    entity_id: automation.en_suite_room_lights_on_if_person_present
  # Clear flags
  - service: input_boolean.turn_off
    entity_id: input_boolean.en_suite_room_short_presence
  # Turn Off Room Thermostat and Turn On Auto Heating
  - service: climate.set_temperature
    entity_id: climate.en_suite_room_thermostat
    data:
      temperature: 10
  - service: automation.turn_on
    entity_id: automation.en_suite_room_heating_on_if_person_present
    
      
- alias: H-ER En-suite Room Heating On If Person Present
  id: '1599909943111'
  description: 'automation.en_suite_room_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  # Queued mode guarentees race condition are in series
  mode: queued
  action:
    # Resolve race on multiple triggers - only execute instances that
    # turned on heating and turned off the automation.
    - condition: state
      entity_id: automation.en_suite_room_heating_on_if_person_present
      state: "on"
    # Turn on heating on repeated short presence or longer presence
    - choose:
        # IF - first time entering, set the flag
        #      Longer presence will turn on heating
        - conditions:
            # Wait for 1.5 min if it is the first time of presence
            - condition: state
              entity_id: input_boolean.en_suite_room_short_presence
              state: "off"
          sequence:
            # set the short presence flag
            - service: input_boolean.turn_on
              entity_id: input_boolean.en_suite_room_short_presence
            # Delay 1.5 min and test motion sensor
            - delay: 00:01:45
            - condition: state
              entity_id: binary_sensor.en_suite_room_bed_motion_sensor_motion
              state: "on"
            # Longer presence will turn on heating
            - service: script.en_suite_room_set_heating_temp_with_state_maintaince
      # ELSE - Repeated short presence will turn on heating
      default:
        - service: script.en_suite_room_set_heating_temp_with_state_maintaince



# En-suite Room with Custom Thermostat
- alias: H-ER En-suite Room Thermostat Switch Turns On/Off the Tado Valve
  trigger:
    - platform: state
      entity_id: input_boolean.en_suite_room_valve_switch
      to:
        - "off"
        - "on"
    - minutes: /5
      platform: time_pattern
  condition: []
  action:
    - data:
        hvac_mode: heat
      entity_id: climate.en_suite_room
      service: climate.set_hvac_mode
    - data:
        # Set tado temperature based on outdoor temperatures
        temperature: >
          {% if states('input_boolean.en_suite_room_valve_switch') == 'off' %}
            5
          {% else %}
            25
          {% endif %}
      entity_id: climate.en_suite_room
      service: climate.set_temperature



# En-suite Toilet
- alias: H-ER En-suite Toilet Heating On If Person Present
  id: '1599909943194'
  description: 'automation.en_suite_toilet_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  # Queued mode guarentees race condition are in series
  mode: queued
  action:
    # Resolve race on multiple triggers - only execute instances that
    # turned on heating and turned off the automation.
    - condition: state
      entity_id: automation.en_suite_toilet_heating_on_if_person_present
      state: "on"
    # Turn on heating on repeated short presence or longer presence
    - choose:
        # IF - first time entering, set the flag
        #      Longer presence will turn on heating
        - conditions:
            # Wait for 1.5 min if it is the first time of presence
            - condition: state
              entity_id: input_boolean.en_suite_toilet_short_presence
              state: "off"
          sequence:
            # set the short presence flag
            - service: input_boolean.turn_on
              entity_id: input_boolean.en_suite_toilet_short_presence
            # Delay 1.5 min and test motion sensor
            - delay: 00:01:45
            - condition: state
              entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
              state: "on"
            # Longer presence will turn on heating
            - service: script.en_suite_toilet_set_heating_temp_with_state_maintaince
      # ELSE - Repeated short presence will turn on heating
      default:
        - service: script.en_suite_toilet_set_heating_temp_with_state_maintaince



- alias: H-ET En-suite Toilet Heating Off If No Person
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:05:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    for: 00:05:00
    state: 'off'
  action:
  # Clear flags
  - service: input_boolean.turn_off
    entity_id: input_boolean.en_suite_toilet_short_presence
  # Turn Off Room Tado and Turn On Auto Heating
  - service: climate.set_temperature
    entity_id: climate.en_suite_toilet
    data:
      temperature: 5
  - service: automation.turn_on
    entity_id: automation.en_suite_toilet_heating_on_if_person_present


###############################################
#
# Lighting Automation based on motion sensors
#
###############################################


# En-suite Room Lights
- alias: L-ER En-suite Room Lights On If Person Present
  id: '1603640029650'
  description: 'automation.en_suite_room_lights_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    condition: state
    state: 'on'
  - entity_id: sensor.en_suite_room_motion_sensor_light
    condition: numeric_state
    below: '40'
  action:
  - data: {}
    service: script.en_suite_room_all_lights_turn_on
  - data: {}
    entity_id: automation.en_suite_room_lights_on_if_person_present
    service: automation.turn_off




# En-suite Toilet Lights
- alias: L-ET En-suite Toilet Lights On If Person Present and Dark
  id: '1603640030013'
  description: ''
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    condition: state
    state: 'on'
  - entity_id: sensor.en_suite_toilet_motion_sensor_light
    condition: numeric_state
    below: '30'
  action:
  - data: {}
    entity_id: switch.en_suite_toilet_light
    service: switch.turn_on




- alias: L-ET En-suite Toilet Lights Off If No Person For 10 Min
  id: '1603640030014'
  description: ''
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    state: 'off'
    for: 00:10:00
  action:
  - data: {}
    entity_id: switch.en_suite_toilet_light
    service: switch.turn_off



- alias: L-ET En-suite Toilet Lights Off If No Person For 2 Min And Door Open
  id: '1603640030015'
  description: ''
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:02:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: and
    conditions:
    - entity_id: binary_sensor.en_suite_toilet_door
      condition: state
      state: 'on'
    - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
      condition: state
      state: 'off'
      for: 00:02:00
  action:
  - data: {}
    entity_id: switch.en_suite_toilet_light
    service: switch.turn_off




###############################################
#
# Lighting Automation based on buttons
#
###############################################

# En-suite Room
- alias: B-MR En-suite Room Wall Switch - Single Press - Turn On En-suite Room Lights/Turn Off All Lights
  trigger:
  - platform: state
    entity_id: sensor.en_suite_room_ceiling_light_wall_button
    to: single
  action:
  - choose:
    # IF - all lights off - turn on ceiling light
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: switch.en_suite_room_ceiling_light
          state: 'off'
        - condition: state
          entity_id: switch.en_suite_room_bedside_lamp
          state: 'off'
        - condition: state
          entity_id: switch.en_suite_toilet_light
          state: 'off'
      sequence:
        - service: switch.turn_on
          entity_id: switch.en_suite_room_ceiling_light
    # ELSE - some lights on - turn off all lights
    default:
      - service: switch.turn_off
        entity_id: 
        - switch.en_suite_room_ceiling_light
        - switch.en_suite_room_bedside_lamp
        - switch.en_suite_toilet_light


- alias: B-MR En-suite Room Bed Button  - Single Press - Toggle Ceiling Lights
  trigger:
  - platform: state
    entity_id: sensor.en_suite_room_bedside_button
    to: single
  action:
  - service:   switch.toggle
    entity_id: switch.en_suite_room_ceiling_light


- alias: B-MR En-suite Room Bed Button - Double Press - Toggle Bedside Lamp
  trigger:
  - platform: state
    entity_id: sensor.en_suite_room_bedside_button
    to: double
  action:
  - service:   switch.toggle
    entity_id: switch.en_suite_room_bedside_lamp


######################################################
#
# Maintaince on bedroom automation based on presence
#
######################################################

- alias: P-ER En-suite Room Disable The Entering Room Automation If People Present
  trigger:
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - delay: 00:00:30
  - service: automation.turn_off
    entity_id:
     - automation.en_suite_room_lights_on_if_person_present
  # Short presence machanism requires to turn off auto-heating late     
  - delay: 00:03:00
  - service: automation.turn_off
    entity_id:
     - automation.en_suite_room_heating_on_if_person_present


