# Misc Automations
# - TV controls
# - Sonos Music state mantainance
# - Restart HA
# - Turn Off Raditor if outdoor temperature is high

- alias: Turn Off All TVs at 2.3.4.5am
  id: '1602117522624'
  description: ''
  trigger:
  - at: 02:00:00
    platform: time
  - at: 03:00:00
    platform: time
  - at: 04:00:00
    platform: time
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: media_player.living_room_tv
    service: media_player.turn_off

- alias: turn on tv - DOES NOT WORK - NEED WAKE-ON-LAN
  id: '1602118134986'
  description: ''
  trigger:
  - at: '12:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: media_player.living_room_tv
    service: media_player.turn_on


- alias: Living Room TV Off If No Person For 20 Min
  id: '1602118737375'
  description: ''
  trigger:
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
    for: 00:20:00
    state: 'off'
  action:
  - data:
      entity_id: media_player.living_room_tv
    service: media_player.turn_off





- alias: 'Restart HA at 5am After All Devices Restarted '
  id: '1602722452776'
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - data: {}
    service: homeassistant.restart



###############################################
#
# Sonos Music state mantainance
#
###############################################
- alias: S- Set Music Master Speaker When The Only One Is Playing
  trigger:
  - platform: state
    entity_id:
      - media_player.living_room_sonos
      - media_player.master_room_sonos
      - media_player.kitchen_sonos
      - media_player.first_corridor_sonos
    to:
      - "idle"
      - "playing"
      - "paused"
      - "off"
  - minutes: /5
    platform: time_pattern      
  condition: []
  action:
  - choose:
    # IF - only kitchen sonos is playing - set it as master speaker
    - conditions:
      - condition: state
        state:     "playing"
        entity_id: media_player.kitchen_sonos
      - condition: not
        conditions:
        - condition: state
          state:     "playing"
          entity_id: media_player.living_room_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.master_room_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.first_corridor_sonos          
      sequence:
        - service: input_select.select_option
          entity_id: input_select.music_controller
          data:
            option:  kitchen_sonos
    # ELIF only living room sonos is playing music instead of TV - set it as master speaker
    - conditions:
      - condition: template
        value_template: >
          {% if state_attr('media_player.living_room_sonos', 'media_title') != 'TV' %}
            true
          {% else %}
            false
          {% endif %}
      - condition: state
        state:     "playing"
        entity_id: media_player.living_room_sonos
      - condition: not
        conditions:
        - condition: state
          state:     "playing"
          entity_id: media_player.kitchen_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.master_room_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.first_corridor_sonos                 
      sequence:
        - service: input_select.select_option
          entity_id: input_select.music_controller
          data:
            option:  living_room_sonos
    # ELIF only master room sonos is playing - set it as master speaker
    - conditions:
      - condition: state
        state:     "playing"
        entity_id: media_player.master_room_sonos
      - condition: not
        conditions:
        - condition: state
          state:     "playing"
          entity_id: media_player.living_room_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.kitchen_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.first_corridor_sonos                 
      sequence:
        - service: input_select.select_option
          entity_id: input_select.music_controller
          data:
            option:  master_room_sonos
    # ELIF only first corridor sonos is playing - set it as master speaker
    - conditions:
      - condition: state
        state:     "playing"
        entity_id: media_player.first_corridor_sonos
      - condition: not
        conditions:
        - condition: state
          state:     "playing"
          entity_id: media_player.living_room_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.kitchen_sonos
        - condition: state
          state:     "playing"
          entity_id: media_player.master_room_sonos                 
      sequence:
        - service: input_select.select_option
          entity_id: input_select.music_controller
          data:
            option:  first_corridor_sonos


## Update Flux colour temperature
#- alias: L-GR Guest Room Fluxer Update
#  trigger:
#    - platform: time_pattern
#      seconds: "/30"
#  action:
#    - service: switch.fluxer_update

- alias: Enable/Disable Logging By The State of The Log Enable
  id: '1607918439986'
  trigger:
    - platform: time_pattern
      minutes: "/5"
    - platform: state
      entity_id: input_boolean.log_enable
      to:
        - "on"
        - "off"
  action:
    - service: >
        {% if states('input_boolean.log_enable') == 'on' %}
          recorder.enable
        {% else %}
          recorder.disable
        {% endif %}   
      
#- alias: H- Turn On/Off Raditors/Aircon Mode Based On Outdoor Temperature
#  id: '1607918454986'
#  description: ''
#  trigger:
#  - minutes: /5
#    platform: time_pattern
#  condition: []
#  action:
#  - condition: numeric_state
#    entity_id: sensor.kitchen_temperature_sensor
#    above: "23"
#  - condition: numeric_state
#    entity_id: sensor.cambridge_city_airport_temperature
#    above: "17"
#  - data: {}
#    entity_id: media_player.living_room_tv
#    service: media_player.turn_on
#  - condition: numeric_state
#    entity_id: sensor.master_room_light_meter
#    above: "100"

