###########################################
#
# Custom Entities
#
###########################################
light:
  - platform: group
    name: En-suite Toilet Ceiling Light
    entities:
      - light.en_suite_toilet_spotlight_bulb_1
      - light.en_suite_toilet_spotlight_bulb_2
      - light.en_suite_toilet_spotlight_bulb_3

# Custom Variables
input_boolean:

  # First Time Presence in a Room
  en_suite_toilet_short_presence:
    name: "En-suite Toilet Short Presence"
    initial: "off"
    
###############################################
#
# Scripts
#
###############################################  
script:
  en_suite_toilet_all_lights_turn_on:
    alias: En-suite Toilet All Lights Turn On
    mode: parallel
    max: 100
    sequence:
      - entity_id: light.en_suite_toilet_ceiling_light
        service: light.turn_on

  en_suite_toilet_all_lights_turn_off:
    alias: En-suite Toilet All Lights Turn Off
    mode: parallel
    max: 100
    sequence:
      - entity_id: light.en_suite_toilet_ceiling_light
        service: light.turn_off

  en_suite_toilet_set_bright_cool_light:
    alias: En-suite Toilet Set Bright Cool Light
    mode: single
    sequence:
      - service: light.turn_on
        entity_id: light.en_suite_toilet_ceiling_light
        data:
          brightness: 255
          kelvin: 4000

  en_suite_toilet_set_dark_warm_light:
    alias: En-suite Toilet Set Bright Cool Light
    mode: single
    sequence:
      - service: light.turn_on
        entity_id: light.en_suite_toilet_ceiling_light
        data:
          brightness: 1
          kelvin: 3000


  en_suite_toilet_set_heating_temp_with_state_maintaince:
    alias: En-suite Toilet Set Heating Temperature With State Maintaince
    mode: restart
    sequence:
      # clear the short presence flag
      - service: input_boolean.turn_off
        entity_id: input_boolean.en_suite_toilet_short_presence
      # turn on heating
      - data:
          hvac_mode: heat
        entity_id: climate.en_suite_toilet
        service: climate.set_hvac_mode
      - data:
          temperature: 21
        entity_id: climate.en_suite_toilet
        service: climate.set_temperature
      - data:
          stop_actions: false
        entity_id: automation.en_suite_toilet_heating_on_if_people_present
        service: automation.turn_off




###############################################
#
# Automations:
# - Heating Automation based on motion sensors
# - Lighting Automation based on motion sensors
# - Actions based on buttons
#
###############################################
automation:

###############################################
# Heating Automation based on motion sensors
###############################################
- alias: H-ET En-suite Toilet Heating Off If No Person
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:05:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    for: 00:05:00
    state: 'off'
  action:
  # Clear flags
  - service: input_boolean.turn_off
    entity_id: input_boolean.en_suite_toilet_short_presence
  # Turn Off Room Tado and Turn On Auto Heating
  - service: climate.set_temperature
    entity_id: climate.en_suite_toilet
    data:
      temperature: 5
  - service: automation.turn_on
    entity_id: automation.en_suite_toilet_heating_on_if_person_present


# En-suite Toilet
- alias: H-ER En-suite Toilet Heating On If Person Present
  id: '1599909943194'
  description: 'automation.en_suite_toilet_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  # Queued mode guarentees race condition are in series
  mode: queued
  action:
    # Resolve race on multiple triggers - only execute instances that
    # turned on heating and turned off the automation.
    - condition: state
      entity_id: automation.en_suite_toilet_heating_on_if_person_present
      state: "on"
    # Turn on heating on repeated short presence or longer presence
    - choose:
        # IF - first time entering, set the flag
        #      Longer presence will turn on heating
        - conditions:
            # Wait for 1.5 min if it is the first time of presence
            - condition: state
              entity_id: input_boolean.en_suite_toilet_short_presence
              state: "off"
          sequence:
            # set the short presence flag
            - service: input_boolean.turn_on
              entity_id: input_boolean.en_suite_toilet_short_presence
            # Delay 1.5 min and test motion sensor
            - delay: 00:01:45
            - condition: state
              entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
              state: "on"
            # Longer presence will turn on heating
            - service: script.en_suite_toilet_set_heating_temp_with_state_maintaince
      # ELSE - Repeated short presence will turn on heating
      default:
        - service: script.en_suite_toilet_set_heating_temp_with_state_maintaince




###############################################
# Lighting Automation based on motion sensors
###############################################
# En-suite Toilet Lights
- alias: L-ET En-suite Toilet Lights On If Person Present and Dark
  id: '1603640030013'
  description: ''
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    condition: state
    state: 'on'
  - entity_id: sensor.en_suite_toilet_motion_sensor_light
    condition: numeric_state
    below: '250'
  action:
  - entity_id: light.en_suite_toilet_ceiling_light
    service: light.turn_on



- alias: L-ET En-suite Toilet Lights Off If No Person For 10 Min
  id: '1603640030014'
  description: ''
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:10:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    state: 'off'
    for: 00:10:00
  action:
  - data: {}
    entity_id: light.en_suite_toilet_ceiling_light
    service: light.turn_off



- alias: L-ET En-suite Toilet Lights Off If No Person For 2 Min And Door Open
  id: '1603640030015'
  description: ''
  trigger:
  - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:02:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: and
    conditions:
    - entity_id: binary_sensor.en_suite_toilet_door
      condition: state
      state: 'on'
    - entity_id: binary_sensor.en_suite_toilet_motion_sensor_motion
      condition: state
      state: 'off'
      for: 00:02:00
  action:
  - data: {}
    entity_id: light.en_suite_toilet_ceiling_light
    service: light.turn_off


###############################################
# Actions based on buttons
###############################################

- alias: B-ET En-suite Toilet Wall Button - Single Press - Toggle Toilet Lights
  trigger:
  - platform: state
    entity_id: sensor.en_suite_toilet_light_wall_button
    to: single
  action:
  - service:   light.toggle
    entity_id: light.en_suite_toilet_ceiling_light

