###########################################
#
# Integration Instantiated in yaml
#
###########################################

# Added MagicHome LEDs
# This is a third-party custom component on flux_led
# instead of the official one from HA
light magic_home:
   - platform: flux_led
     devices:  
       192.168.1.54:
         name: En-suite Room Bed LED Flux LED
         mode: "rgb"  

###########################################
#
# Custom Entities
#
###########################################
# Custom Thermostat
climate:
  - platform: generic_thermostat
    name: En-suite Room Thermostat
    heater: input_boolean.en_suite_room_valve_switch
    target_sensor: sensor.en_suite_room_temperature_sensor
    precision: 0.5
    min_temp: 7
    max_temp: 25
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    initial_hvac_mode: "heat"

  - platform: generic_thermostat
    name: En-suite Room Air Conditioner
    heater: switch.air_conditioner
    ac_mode: true
    target_sensor: sensor.en_suite_room_temperature_sensor
    precision: 0.5
    min_temp: 10
    max_temp: 25
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    initial_hvac_mode: "off"

# Custom Variables
input_boolean:
  # Spare Room Usage
  en_suite_room_guests_use_this_room:
    name: "En-suite Room Guests Use This Room"

  # Custom Thermostat Switch
  en_suite_room_valve_switch:
    name: "En-suite Room Valve Switch"

  # First Time Presence in a Room
  en_suite_room_short_presence:
    name: "En-suite Room Short Presence"
    initial: "off"

  # Use for detecting if there is an outstanding setting update scheduled
  en_suite_room_outstanding_setting_update:
    name: "En-suite Room Outstanding Setting Update"
    initial: "off"

###############################################
#
# Scripts
#
###############################################  
script:
  en_suite_room_all_lights_turn_on:
    alias: En-suite Room All Light Turn On
    mode: parallel
    max: 100
    sequence:
      - service: light.turn_on
        entity_id:
          - light.en_suite_room_ceiling_light
          - light.en_suite_room_bed_led          
          #- switch.en_suite_room_bedside_lamp

  en_suite_room_all_lights_turn_off:
    alias: En-suite Room All Light Turn Off
    mode: parallel
    max: 100
    sequence:
      - service: light.turn_off
        entity_id:
          - light.en_suite_room_ceiling_light
          - light.en_suite_room_bed_led
          #- switch.en_suite_room_bedside_lamp
          
  en_suite_room_set_heating_temp_with_state_maintaince:
    alias: En-suite Room Set Heating Temperature With State Maintaince
    mode: restart
    sequence:
      # clear the short presence flag
      - service: input_boolean.turn_off
        entity_id: input_boolean.en_suite_room_short_presence
      # turn on heating
      - data:
          hvac_mode: heat
        entity_id: climate.en_suite_room_thermostat
        service: climate.set_hvac_mode
      - data:
          temperature: 22.5
        entity_id: climate.en_suite_room_thermostat
        service: climate.set_temperature
      - data:
          stop_actions: false
        entity_id: automation.en_suite_room_heating_on_if_people_present
        service: automation.turn_off


###############################################
#
# Automations:
# - Lighting/Heating automation based on motion sensors
# - Actions based on buttons
# - Maintaince on bedroom automation based on presence
#
###############################################

automation:
###############################################
# Heating Automation based on motion sensors
###############################################
- alias: HL-ER En-suite Room Lights/Heating Off If No Person
  id: '1603640029651'
  description: ''
  trigger:
  - entity_id: 
     - binary_sensor.en_suite_room_motion_sensor_motion
     - binary_sensor.kes_desk_motion_sensor_motion
     - binary_sensor.tais_desk_motion_sensor_motion
    platform: state
    from: 'on'
    to: 'off'
    for: 00:15:00
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: or
    conditions:
    # IF - in daytime, turn off lighting/heating if no person for 15 min
    - condition: and
      conditions:
      - after:  '10:00:00'
        before: '22:00:00'
        condition: time
      - condition: state
        entity_id: 
         - binary_sensor.en_suite_room_motion_sensor_motion
         - binary_sensor.kes_desk_motion_sensor_motion
         - binary_sensor.tais_desk_motion_sensor_motion
        for: 00:15:00
        state: 'off'
    # ELSEIF - in nighttime, if no people live in the room,
    #          turn off lighting/heating if no person for 15 min
    - condition: and
      conditions:
      - after:  '22:00:00'
        before: '10:00:00'
        condition: time
      - condition: state
        entity_id: 
         - binary_sensor.en_suite_room_motion_sensor_motion
         - binary_sensor.kes_desk_motion_sensor_motion
         - binary_sensor.tais_desk_motion_sensor_motion
        state: 'off'
        for: 00:15:00
      - condition: state
        entity_id: input_boolean.en_suite_room_guests_use_this_room
        state: 'off'
    # ELSEIF - in nighttime, if people live in the room
    #          turn off lighting/heating if no person for 2 hours
    - condition: and
      conditions:
      - after:  '22:00:00'
        before: '10:00:00'
        condition: time
      - condition: state
        entity_id: 
         - binary_sensor.en_suite_room_motion_sensor_motion
         - binary_sensor.kes_desk_motion_sensor_motion
         - binary_sensor.tais_desk_motion_sensor_motion
        state: 'off'
        for: 02:00:00
      - condition: state
        entity_id: input_boolean.en_suite_room_guests_use_this_room
        state: 'on'
  action:
  # Turn Off Lights and Turn On Auto Lights-up
  - service: script.en_suite_room_all_lights_turn_off
  - service: automation.turn_on
    entity_id: automation.en_suite_room_lights_on_if_person_present
  # Clear flags
  - service: input_boolean.turn_off
    entity_id: input_boolean.en_suite_room_short_presence
  # Turn Off Room Thermostat and Turn On Auto Heating
  - service: climate.set_temperature
    entity_id: climate.en_suite_room_thermostat
    data:
      temperature: 10
  - service: automation.turn_on
    entity_id: automation.en_suite_room_heating_on_if_person_present
    
      
- alias: H-ER En-suite Room Heating On If Person Present
  id: '1599909943111'
  description: 'automation.en_suite_room_heating_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  # Queued mode guarentees race condition are in series
  mode: queued
  action:
    # Resolve race on multiple triggers - only execute instances that
    # turned on heating and turned off the automation.
    - condition: state
      entity_id: automation.en_suite_room_heating_on_if_person_present
      state: "on"
    # Turn on heating on repeated short presence or longer presence
    - choose:
        # IF - first time entering, set the flag
        #      Longer presence will turn on heating
        - conditions:
            # Wait for 1.5 min if it is the first time of presence
            - condition: state
              entity_id: input_boolean.en_suite_room_short_presence
              state: "off"
          sequence:
            # set the short presence flag
            - service: input_boolean.turn_on
              entity_id: input_boolean.en_suite_room_short_presence
            # Delay 1.5 min and test motion sensor
            - delay: 00:01:45
            - condition: state
              entity_id: binary_sensor.en_suite_room_bed_motion_sensor_motion
              state: "on"
            # Longer presence will turn on heating
            - service: script.en_suite_room_set_heating_temp_with_state_maintaince
      # ELSE - Repeated short presence will turn on heating
      default:
        - service: script.en_suite_room_set_heating_temp_with_state_maintaince



# En-suite Room with Custom Thermostat
- alias: H-ER En-suite Room Thermostat Switch Turns On/Off the Tado Valve
  id: '1596909943139'
  trigger:
    - platform: state
      entity_id: input_boolean.en_suite_room_valve_switch
      to:
        - "off"
        - "on"
    - minutes: /5
      platform: time_pattern
  condition: []
  action:
    - data:
        hvac_mode: heat
      entity_id: climate.en_suite_room
      service: climate.set_hvac_mode
    - data:
        # Set tado temperature based on outdoor temperatures
        temperature: >
          {% if states('input_boolean.en_suite_room_valve_switch') == 'off' %}
            5
          {% else %}
            25
          {% endif %}
      entity_id: climate.en_suite_room
      service: climate.set_temperature


###############################################
# Lighting Automation based on motion sensors
###############################################
# En-suite Room Lights
- alias: L-ER En-suite Room Lights On If Person Present
  id: '1603640029650'
  description: 'automation.en_suite_room_lights_on_if_person_present'
  trigger:
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    condition: state
    state: 'on'
  - entity_id: sensor.en_suite_room_motion_sensor_light
    condition: numeric_state
    below: '40'
  action:
  - service: script.en_suite_room_all_lights_turn_on
  - entity_id: automation.en_suite_room_lights_on_if_person_present
    service: automation.turn_off





###############################################
# Actions based on buttons
###############################################

# En-suite Room
#- alias: B-ER En-suite Room Wall Switch - Single Press - Turn On En-suite Room Lights/Turn Off All Lights
#  trigger:
#  - platform: state
#    entity_id: sensor.en_suite_room_ceiling_light_wall_button
#    to: single
#  action:
#  - choose:
#    # IF - all lights off - turn on ceiling light
#    - conditions:
#      - condition: and
#        conditions:
#        - condition: state
#          entity_id: switch.en_suite_room_ceiling_light
#          state: 'off'
#        - condition: state
#          entity_id: switch.en_suite_room_bedside_lamp
#          state: 'off'
#        - condition: state
#          entity_id: light.en_suite_toilet_ceiling_light
#          state: 'off'
#      sequence:
#        - service: switch.turn_on
#          entity_id: switch.en_suite_room_ceiling_light
#    # ELSE - some lights on - turn off all lights
#    default:
#      - service: switch.turn_off
#        entity_id: 
#        - switch.en_suite_room_ceiling_light
#        - switch.en_suite_room_bedside_lamp
#      - service: light.turn_off
#        entity_id: 
#        - light.en_suite_toilet_ceiling_light


- alias: B-ER En-suite Room Wall/Bed Button  - Single Press - Toggle Ceiling Lights
  trigger:
  - platform: state
    entity_id: 
     - sensor.en_suite_room_bedside_button
     - sensor.en_suite_room_ceiling_light_wall_button     
    to: single
  action:
  - service:   light.toggle
    entity_id: 
      - light.en_suite_room_ceiling_light
     


- alias: B-ER En-suite Room Bed Button - Double Press - Toggle Bedside Lamp
  trigger:
  - platform: state
    entity_id: sensor.en_suite_room_bedside_button
    to: double
  action:
  - service:   switch.toggle
    entity_id: switch.en_suite_room_bedside_lamp


######################################################
# Maintaince on bedroom automation based on presence
######################################################
- alias: P-ER En-suite Room Disable The Entering Room Automation If People Present
  trigger:
  - entity_id: binary_sensor.en_suite_room_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - delay: 00:00:30
  - service: automation.turn_off
    entity_id:
     - automation.en_suite_room_lights_on_if_person_present
  # Short presence machanism requires to turn off auto-heating late     
  - delay: 00:03:00
  - service: automation.turn_off
    entity_id:
     - automation.en_suite_room_heating_on_if_person_present


