###########################################
#
# Integration Instantiated in yaml
#
###########################################
# Added MagicHome LEDs
# This is a third-party custom component on flux_led
# instead of the official one from HA
light magic_home:
   - platform: flux_led
     devices:
       192.168.1.53:
         name: Living Room TV LED
         mode: "rgb"

       192.168.1.55:
         name: Living Room Sofa LED
         mode: "rgb"
       

###########################################
#
# Custom Entities
#
###########################################
light:
  - platform: group
    name: Living Room Landing Light
    entities:
      - light.living_room_landing_light_bulb_1
      - light.living_room_landing_light_bulb_2

# Custom Variables
input_boolean:
  # First Time Presence in a Room
  living_room_short_presence: # done
    name: "Living Room Short Presence"
    initial: "off"
  
###############################################
#
# Scripts
#
###############################################  
script:
  living_room_landing_lights_turn_off:
    alias: Living Room Landing Lights Turn Off
    max: 100
    mode: parallel
    sequence:
      - entity_id: light.living_room_landing_light
        service: light.turn_off

  living_room_landing_lights_turn_on:
    alias: Living Room Landing Lights Turn On
    max: 100
    mode: parallel
    sequence:
      - entity_id: light.living_room_landing_light
        service: light.turn_on

  living_room_landing_lights_toggle:
    alias: Living Room Landing Lights Toggle
    mode: parallel
    max: 100
    sequence:
      - entity_id: light.living_room_landing_light
        service: light.toggle

  living_room_all_lights_turn_on:
    alias: Living Room Ceiling All Lights Turn On
    mode: parallel
    max: 100
    sequence:
      - service: switch.turn_on
        entity_id:
          - switch.living_room_ceiling_light
          - switch.living_room_tree_light
      - service: script.living_room_landing_lights_turn_on

  living_room_all_lights_turn_off:
    alias: Living Room All Lights Turn Off
    mode: parallel
    max: 100
    sequence:
      - service: switch.turn_off
        entity_id:
          - switch.living_room_ceiling_light
          - switch.garden_light
      - service: script.living_room_landing_lights_turn_off
      - service: light.turn_off
        entity_id:
          - light.living_room_tv_led
          - light.living_room_sofa_led
          
  living_room_set_heating_temp_with_state_maintaince:
    alias: Living Room Set Heating Temperature With State Maintaince
    mode: restart
    sequence:
      # clear the short presence flag
      - service: input_boolean.turn_off
        entity_id: input_boolean.living_room_short_presence
      # turn on heating
      - data:
          hvac_mode: heat
        entity_id: climate.living_room
        service: climate.set_hvac_mode
      - data:
          temperature: 22
        entity_id: climate.living_room
        service: climate.set_temperature
      - data:
          stop_actions: false
        entity_id: automation.living_room_heating_on_if_people_present
        service: automation.turn_off





###############################################
#
# Automations:
# - Heating automation
# - Lighting automation based on motion sensors
# - Actions based on buttons
# - Sonos Speakers Grouping/Ungrouping Based On Motion Sensor
# - TV auto turn-off based on motion sensors
#
###############################################
automation:
###############################################
# Heating Automation based on motion sensors
###############################################
- alias: H-LR Living Room Heating Set to 22 If Person Present
  id: "1599611100701"
  description: "automation.living_room_heating_on_if_people_present"
  trigger:
    - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
      platform: state
      from: "off"
      to: "on"
  # Queued mode guarentees race condition are in series
  mode: queued
  action:
    # Resolve race on multiple triggers - only execute instances that
    # turned on heating and turned off the automation.
    - condition: state
      entity_id: automation.living_room_heating_on_if_people_present
      state: "on"
    # Turn on heating on repeated short presence or longer presence
    - choose:
        # IF - first time entering, set the flag
        #      Longer presence will turn on heating
        - conditions:
            # Wait for 1.5 min if it is the first time of presence
            - condition: state
              entity_id: input_boolean.living_room_short_presence
              state: "off"
          sequence:
            # set the short presence flag
            - service: input_boolean.turn_on
              entity_id: input_boolean.living_room_short_presence
            # Delay 1.5 min and test motion sensor
            - delay: 00:01:45
            - condition: state
              entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
              state: "on"
            # Longer presence will turn on heating
            - service: script.living_room_set_heating_temp_with_state_maintaince
      # ELSE - Repeated short presence will turn on heating
      default:
        - service: script.living_room_set_heating_temp_with_state_maintaince

- alias: H-LR Living Room Heating Off If No Person
  id: "1599611453836"
  description: "automation.living_room_heating_off_if_no_people"
  trigger:
    - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
      platform: state
      from: "on"
      to: "off"
      for: 00:05:00
    - minutes: /5
      platform: time_pattern
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
      for: 00:05:00
      state: "off"
  action:
    # turn off heating
    - service: climate.set_hvac_mode
      entity_id: climate.living_room
      data:
        hvac_mode: auto
    - data: {}
      entity_id: automation.living_room_heating_on_if_people_present
      service: automation.turn_on
    # clear the short presence flag
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_room_short_presence


###############################################
# Lighting Automation based on motion sensors
###############################################
# Gardens
- alias: L-LR Garden and Corridor Lights On If Person Present Around Door
  description: ""
  trigger:
    - entity_id:
        - binary_sensor.garden_sliding_door_motion_sensor_motion
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: and
      conditions:
        - entity_id: binary_sensor.garden_sliding_door_motion_sensor_motion
          condition: state
          state: "on"
        - entity_id: sensor.garden_sliding_door_motion_sensor_light
          condition: numeric_state
          below: "30"
  action:
    - service: switch.turn_on
      entity_id: switch.garden_wall_light
    - service: script.living_room_landing_lights_turn_on
    - service: script.corridor_lights_turn_on

- alias: L-LR Garden and Floor Lights On If Person Present Around Bike Shed
  description: ''
  trigger:
  - entity_id:
      - binary_sensor.garden_bike_shed_motion_sensor_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    - condition: and
      conditions:
      - entity_id: binary_sensor.garden_bike_shed_motion_sensor_motion
        condition: state
        state: 'on'
      - entity_id: sensor.master_room_light_meter
        condition: numeric_state
        below: '100'
  action:
  - service: switch.turn_on
    entity_id: switch.garden_wall_light

- alias: L-LR Garden Lights Off If No Person Present For 5 Min
  description: ""
  trigger:
    - entity_id:
        - binary_sensor.garden_sliding_door_motion_sensor_motion
        - binary_sensor.garden_bike_shed_motion_sensor_motion
      platform: state
      from: "on"
      to: "off"
      for: 00:05:00
    - minutes: /5
      platform: time_pattern
  condition:
    - entity_id:
        - binary_sensor.garden_sliding_door_motion_sensor_motion
        - binary_sensor.garden_bike_shed_motion_sensor_motion
      condition: state
      state: "off"
      for: 00:05:00
  action:
    - service: switch.turn_off
      entity_id: switch.garden_wall_light

# Living Room
- alias: L-LR Living Room Lights On If Person Present
  id: "1603640031661"
  description: "automation.l_lr_living_room_lights_on_if_person_present"
  trigger:
    - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
      platform: state
      from: "off"
      to: "on"
    - entity_id: binary_sensor.living_room_tv_motion_sensor_motion
      platform: state
      from: "off"
      to: "on"
  condition:
    - condition: or
      conditions:
        # Sofa Motion Sensor with Dark Room
        - condition: and
          conditions:
            - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
              condition: state
              state: "on"
            - entity_id: sensor.living_room_sofa_motion_sensor_light
              condition: numeric_state
              below: "40"
        # TV Motion Sensor with Dark Outside
        - condition: and
          conditions:
            - entity_id: binary_sensor.living_room_tv_motion_sensor_motion
              condition: state
              state: "on"
            - entity_id: sensor.master_room_light_meter
              condition: numeric_state
              below: "100"
  action:
    - service: script.living_room_landing_lights_turn_on


- alias: L-LR Living Room Lights Off If No Person For 10 Min
  id: "1603640031662"
  description: ""
  trigger:
    - entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
      platform: state
      from: "on"
      to: "off"
      for: 00:10:00
    - entity_id: binary_sensor.living_room_tv_motion_sensor_motion
      platform: state
      from: "on"
      to: "off"
      for: 00:10:00
    - minutes: /5
      platform: time_pattern
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_sofa_motion_sensor_motion
      for: 00:10:00
      state: "off"
    - condition: state
      entity_id: binary_sensor.living_room_tv_motion_sensor_motion
      for: 00:10:00
      state: "off"
  action:
    - service: script.living_room_all_lights_turn_off


- alias: L-LR Boiler Room Lights On If Door Opens
  id: "1603640041661"
  trigger:
    - entity_id: binary_sensor.boiler_room_door
      platform: state
      from: "off"
      to: "on"
  action:
    - service:   light.turn_on
      entity_id: light.boiler_room_light

- alias: L-LR Boiler Room Lights Off If No Movemenet on Door 
  id: "1603640041662"
  trigger:
    - entity_id: binary_sensor.boiler_room_door
      platform: state
      to: "off"
      for: 00:02:00
    - entity_id: binary_sensor.boiler_room_door
      platform: state
      to: "on"
      for: 00:15:00
    - minutes: /5
      platform: time_pattern      
  condition:
    - condition: or
      conditions:
      - entity_id: binary_sensor.boiler_room_door
        condition: state
        state: "off"
        for: "00:02:00"
      - entity_id: binary_sensor.boiler_room_door
        condition: state
        state: "on"
        for: "00:15:00"
  action:
    - service:   light.turn_off
      entity_id: light.boiler_room_light

###############################################
# Actions based on buttons
###############################################  

- alias: B-LR Living Room Wall/Sofa - Single Press - Toggle Landing Lights
  id: "1603641040070"
  trigger:
    - platform: state
      entity_id: sensor.living_room_sofa_button
      to: single
    - platform: state
      entity_id: sensor.living_room_ceiling_light_button
      to: single
  action:
    - service: script.living_room_landing_lights_toggle

- alias: B-LR Living Room Wall Switch - Double Press - Turn Off All Lights
  trigger:
    - platform: state
      entity_id: sensor.living_room_ceiling_light_button
      to: double
  action:
    - service: script.living_room_all_lights_turn_off

- alias: B-LR Living Room Sofa - Double Press - Toggle Ceiling Lights
  id: "1603641040071"
  trigger:
    - platform: state
      entity_id: sensor.living_room_sofa_button
      to: double
  action:
    #- entity_id: switch.living_room_ceiling_light
    #  service: switch.toggle
    - service: light.toggle
      entity_id:
        - light.living_room_tv_led
        - light.living_room_sofa_led
        
- alias: B-LR Living Room Sofa - Tripple Press - Turn off lights - Movie Scene For 2 Hours
  id: "1603641040072"
  trigger:
    - platform: state
      entity_id: sensor.living_room_sofa_button
      to: triple
  action:
    - choose:
        # IF movie scene is off, turn off lights and its automation for 2 hours for movie scene
        - conditions:
            - condition: state
              entity_id: automation.l_lr_living_room_lights_on_if_person_present
              state: "on"
          sequence:
            # Turn off auto light automation and lights
            - service: automation.turn_off
              entity_id: automation.l_lr_living_room_lights_on_if_person_present
            - service: script.living_room_landing_lights_turn_off
            - entity_id: switch.living_room_ceiling_light
              service: switch.turn_off
            # Delay of some time and turn on back auto lights up
            - delay: "02:00:00"
            - service: automation.turn_on
              entity_id: automation.l_lr_living_room_lights_on_if_person_present

      # ELSE - if movie scene is on, turn off movie scene and turn on lights and its automation
      default:
        - service: script.living_room_landing_lights_turn_on
        - service: automation.turn_on
          entity_id: automation.l_lr_living_room_lights_on_if_person_present
  mode: restart


# Linked Switches
- alias: B-LR Garden Wall Lights ON Controls Floor Spotlights
  id: "1603641040170"
  trigger:
    - platform: state
      to: "on"
      entity_id:
        - switch.garden_wall_light
  action:
    - service: switch.turn_on
      entity_id: switch.garden_spotlight            

- alias: B-LR Garden Wall Lights OFF Controls Floor Spotlights
  id: "1603641040171"
  trigger:
    - platform: state
      to: "off"
      entity_id:
        - switch.garden_wall_light
  action:
    - service: switch.turn_off
      entity_id: switch.garden_spotlight         

- alias: B-LR Garden Decro Wall Switch ON Controls Decro Lights
  id: "1603641040172"
  trigger:
    - platform: state
      to: "on"
      entity_id:
        switch.garden_decro_wall_switch
  action:
    - service: switch.turn_on
      entity_id: 
      - switch.garden_extension_lead_switch_2
      - switch.garden_extension_lead_switch_3

- alias: B-LR Garden Decro Wall Switch OFF Controls Decro Lights
  id: "1603641040173"
  trigger:
    - platform: state
      to: "off"
      entity_id:
        switch.garden_decro_wall_switch
  action:
    - service: switch.turn_off
      entity_id: 
      - switch.garden_extension_lead_switch_2
      - switch.garden_extension_lead_switch_3

#################################################################
# Sonos Speakers Grouping/Ungrouping Based On Motion Sensor
#################################################################
- alias: S-LR Living Room Group Its Speaker If People Present
  trigger:
    - platform: state
      from: "off"
      to: "on"
      entity_id:
        - binary_sensor.living_room_sofa_motion_sensor_motion
        - binary_sensor.living_room_tv_motion_sensor_motion
  condition:
    - condition: state
      entity_id: input_boolean.follow_music
      state: "on"
    # The controller player must be playing music (not paused)
    - condition: template
      value_template: >
        {% if states('media_player.' + states('input_select.music_controller')) == 'playing' %}
          true
        {% else %}
          false
        {% endif %}
  action:
    # Add this room speaker into the group
    - service: script.add_sonos_into_speaker_group
      data:
        target_player: media_player.living_room_sonos

- alias: S-LR Living Room Ungroup/Pause Its Speaker If No People
  trigger:
    - platform: state
      from: "on"
      to: "off"
      for: 00:10:00
      entity_id:
        - binary_sensor.living_room_sofa_motion_sensor_motion
        - binary_sensor.living_room_tv_motion_sensor_motion
    - minutes: /5
      platform: time_pattern
  condition:
    - condition: state
      entity_id:
        - binary_sensor.living_room_sofa_motion_sensor_motion
        - binary_sensor.living_room_tv_motion_sensor_motion
      for: 00:10:00
      state: "off"
  action:
    - choose:
        # IF - music follower is on
        - conditions:
            - condition: state
              entity_id: input_boolean.follow_music
              state: "on"
          sequence:
            # Remove this room speaker from the group
            - service: script.remove_sonos_from_speaker_group
              data:
                target_player: media_player.living_room_sonos
    # Pause this room speaker in case it is the last item in the group
    # or music follower is off
    # Remove this room speaker from the group
    - service: script.pause_sonos_if_sole_speaker_group
      data:
        target_player: media_player.living_room_sonos

- alias: S-LR Living Room Sonos Night Mode On In the Night
  trigger:
    - at: "21:00:00"
      platform: time
  action:
    - service: sonos.set_option
      data:
        night_sound: true
        entity_id: media_player.living_room_sonos
    

- alias: S-LR Living Room Sonos Night Mode Off In the Morning
  trigger:
    - at: "09:00:00"
      platform: time
  action:
    - service: sonos.set_option
      data:
        night_sound: false
        entity_id: media_player.living_room_sonos
        
#################################################################
# TV auto turn-off based on motion sensors
#################################################################
#- alias: TV-LR Living Room Turn Off TV If No Person
#  trigger:
#    - platform: state
#      from: "on"
#      to: "off"
#      for: 00:20:00
#      entity_id:
#        - binary_sensor.living_room_sofa_motion_sensor_motion
#        - binary_sensor.living_room_tv_motion_sensor_motion
#    - minutes: /5
#      platform: time_pattern
#  condition:
#    - condition: state
#      entity_id:
#        - binary_sensor.living_room_sofa_motion_sensor_motion
#        - binary_sensor.living_room_tv_motion_sensor_motion
#      for: 00:20:00
#      state: "off"
#  action:
#    # Switch Off TV
#    - service: switch.turn_off
#      entity_id: switch.living_room_tv


