###########################################
#
# Custom Entities
#
###########################################

# Custom Variables
input_boolean:

  log_enable:
    name: "Log Enable"
    initial: "off"


# Lights Temperature Changed for Flux
#switch flux:
#  - platform: flux
#    lights:
#      - light.guest_room_lamp_left
#      - light.guest_room_lamp_right
#      - light.guest_room_ceiling_light
#      - light.study_lamp_left
#      - light.study_lamp_right
#      - light.study_ceiling_light
#    name: Fluxer
#    start_time: "6:00"
#    stop_time: "23:00"
#    start_colortemp: 6000
#    sunset_colortemp: 5000
#    stop_colortemp: 3000
#    mode: mired
#    transition: 30
#    interval: 60


## Avoid race condition with /5 time pattern trigger
#input_datetime:
#  toilet_daytime_early_start:
#    name: Toilet Daytime Early Start
#    has_date: false
#    has_time: true 
#    initial: "06:01:00"   
#
#  toilet_daytime_late_start:
#    name: Toilet Daytime Late Start
#    has_date: false
#    has_time: true 
#    initial: "10:01:00"   
#
#  toilet_nighttime_start:
#    name: Toilet Nighttime Start
#    has_date: false
#    has_time: true 
#    initial: "18:01:00"   
#
#  toilet_midnight_start:
#    name: Toilet Midnight Start
#    has_date: false
#    has_time: true 
#    initial: "00:01:00"   




###############################################
#
# Scripts
#
###############################################  
script:
  hassio_restart:
    alias: Restart Home Assistant
    sequence:
      - service: homeassistant.restart

###############################################
#
# Automations:
# - Non-bedroom light colour design
# - Restart HA on time
# - Log Enable
#
###############################################
automation:
########################################################################################################################
# Non-bedroom light colour design
# 1. T- (10am-6pm) Starting from daylight, uses 4000k white, full brightness
# 2. T- (6pm-11pm)  Starting from nighttime, uses 3000k white, full brightness
# 3. B- (6pm-11pm)  During nighttime, Switch to 4000k white (with floor led off if possible) if mirror light is on 
# 4. B- (6pm-11pm)  During nighttime, Switch to 3000k white (with floor led on  if possible) if mirror light is off
# 5. T- (11pm-10am) Starting from midnight, uses 3000k white, 1% brightness
########################################################################################################################
- alias: T- Set light starting from early daylight, uses 4000k white, full brightness
  trigger:
    - at: "05:59:50"
      platform: time
  action:
    - service: light.turn_on
      entity_id: 
       - light.kitchen_ceiling_light
       - light.kitchen_dining_light
       - light.en_suite_toilet_ceiling_light
       - light.guest_toilet_ceiling_light
       - light.ground_toilet_ceiling_light
       - light.guest_room_lamps
       - light.study_lamps
       - light.ground_corridor_ble_light
       - light.first_corridor_ble_light             
      data:
        brightness: 255
        kelvin: 4000

- alias: T- Set light starting from late daylight, uses 4000k white, full brightness
  trigger:
    - at: "09:59:50"
      platform: time
  action:
    - service: light.turn_on
      entity_id: 
       - light.master_toilet_ceiling_light
       - light.master_toilet_dressing_room_light
      data:
        brightness: 255
        kelvin: 4000

- alias: T- Set light starting from nighttime, uses 3000k white, full brightness
  trigger:
    - at: "17:59:50"
      platform: time
  action:
    - service: light.turn_on
      entity_id: 
      - light.kitchen_ceiling_light
      - light.kitchen_dining_light
      - light.master_toilet_ceiling_light
      - light.en_suite_toilet_ceiling_light
      - light.guest_toilet_ceiling_light
      - light.ground_toilet_ceiling_light
      - light.master_toilet_dressing_room_light
      - light.guest_room_lamps
      - light.study_lamps
      - light.ground_corridor_ble_light
      - light.first_corridor_ble_light            
      data:
        brightness: 255
        kelvin: 3000


- alias: T- Set light starting from nighttime, uses 3000k white, 1% brightness
  trigger:
    - at: "22:59:50"
      platform: time
  action:
    - service: light.turn_on
      entity_id: 
       - light.kitchen_ceiling_light
       - light.kitchen_dining_light
       - light.master_toilet_ceiling_light
       - light.en_suite_toilet_ceiling_light
       - light.guest_toilet_ceiling_light
       - light.ground_toilet_ceiling_light
       - light.master_toilet_dressing_room_light
       #- light.guest_room_lamps
       #- light.study_lamps
       - light.first_corridor_ble_light          
      data:
        brightness: 1
        kelvin: 3000
    - service: light.turn_on
      entity_id: 
      - light.ground_corridor_ble_light
      data:
        brightness: 76
        kelvin: 3000

# - Restart HA on time
- alias: 'Restart HA at 4am and 5am'
  id: '1602722452776'
  description: ''
  trigger:
  - at: 04:00:00
    platform: time
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - service: homeassistant.restart


# - Log Enable
- alias: Enable/Disable Logging By The State of The Log Enable
  id: '1607918439986'
  trigger:
    - platform: time_pattern
      minutes: "/5"
    - platform: state
      entity_id: input_boolean.log_enable
      to:
        - "on"
        - "off"
  action:
    - service: >
        {% if states('input_boolean.log_enable') == 'on' %}
          recorder.enable
        {% else %}
          recorder.disable
        {% endif %}           