###########################################
#
# Custom Entities
#
###########################################
sensor time:
  # Time
  - platform: time_date
    display_options:
      - "time"
      - "date"

# Custom Variables
input_boolean:
  log_enable:
    name: "Log Enable"

  always_off_constant:
    name: "Always Off Constant"
    initial: "off"

  always_on_constant:
    name: "Always On Constant"
    initial: "on"

  placeholder:
    name: "Placeholder"
    initial: "off"

input_select:
  indoor_brightness:
    name: Indoor Brightness
    options:
      - dark
      - dimmed
      - bright

## Avoid race condition with /5 time pattern trigger
#input_datetime:
#  toilet_daytime_early_start:
#    name: Toilet Daytime Early Start
#    has_date: false
#    has_time: true
#    initial: "06:01:00"
#
#  toilet_daytime_late_start:
#    name: Toilet Daytime Late Start
#    has_date: false
#    has_time: true
#    initial: "10:01:00"
#
#  toilet_beginning_of_evening:
#    name: Toilet Nighttime Start
#    has_date: false
#    has_time: true
#    initial: "18:01:00"
#
#  toilet_beginning_of_midnight:
#    name: Toilet Midnight Start
#    has_date: false
#    has_time: true
#    initial: "00:01:00"

###############################################
#
# Scripts
#
###############################################
script:
  hassio_restart:
    alias: Restart Home Assistant
    sequence:
      - service: homeassistant.restart

  do_nothing:
    alias: Do nothing
    sequence:

###############################################
#
# Automations:
# - Non-bedroom light colour design
# - Restart HA on time
# - Log Enable
#
###############################################
automation:
  - alias: Do nothing
    id: "1596919926917"
    trigger:
    action:
  # All living room Router/AP/Hubs (tado/hue/LR gateway 3/Xiaomi AP)
  # will be restart at 4.30am by a timer plug.
  # HA instance and other AP/hubs (AQ/MR gateway/TPlink AP) will be
  # restarted by the instance below.
  #
  # WOL sometimes stuck at sending magic packets and required to restart HA
  - alias: Restart HA at midnight
    id: "1602722452776"
    description: ""
    trigger:
      - at: 04:00:00
        platform: time
    action:
      # Restart hubs in other rooms
      - delay: "00:01:00"
      - service: homeassistant.restart

  # Air cond automation
  #  - alias: H-MR Master Room Thermostat State Are Mutually Exclusive From Aircon
  #    id: "1596916933135"
  #    description: "automation.master_room_thermostat_state_are_mutually_exclusive_from_aircon"
  #    trigger:
  #      - platform: state
  #        entity_id: climate.master_room
  #        to:
  #          - "off"
  #          - "heat"
  #      - platform: state
  #        entity_id: climate.en_suite_room_thermostat
  #        to:
  #          - "off"
  #          - "heat"
  #    action:
  #      - service: automation.turn_off
  #        entity_id: automation.master_room_aircon_state_are_mutually_exclusive_from_thermostat
  #      - entity_id:
  #          - climate.master_room_air_conditioner
  #          - climate.en_suite_room_air_conditioner
  #        service: climate.set_hvac_mode
  #        data:
  #          hvac_mode: >
  #            {% if states('climate.master_room') == 'heat' %}
  #              off
  #            {% elif states('climate.en_suite_room_thermostat') == 'heat' %}
  #              off
  #            {% else %}
  #              cool
  #            {% endif %}
  #      - service: automation.turn_on
  #        entity_id: automation.master_room_aircon_state_are_mutually_exclusive_from_thermostat

  #  - alias: H-MR Master Room Aircon State Are Mutually Exclusive From Thermostat
  #    id: "1596916933136"
  #    description: "automation.master_room_aircon_state_are_mutually_exclusive_from_thermostat"
  #    trigger:
  #      - platform: state
  #        entity_id: climate.master_room_air_conditioner
  #        to:
  #          - "off"
  #          - "cool"
  #      - platform: state
  #        entity_id: climate.en_suite_room_air_conditioner
  #        to:
  #          - "off"
  #          - "cool"
  #    action:
  #      - service: automation.turn_on
  #        entity_id: automation.master_room_thermostat_state_are_mutually_exclusive_from_aircon
  #      - entity_id:
  #          - climate.master_room
  #          - climate.en_suite_room_thermostat
  #        service: climate.set_hvac_mode
  #        data:
  #          hvac_mode: >
  #            {% if states('climate.master_room_air_conditioner') == 'cool' %}
  #              off
  #            {% elif states('climate.en_suite_room_air_conditioner') == 'cool' %}
  #              off
  #            {% else %}
  #              heat
  #            {% endif %}
  #      - service: automation.turn_on
  #        entity_id: automation.master_room_thermostat_state_are_mutually_exclusive_from_aircon

  ####################################################
  #
  # Restart HA if certain entities becomes unavailable
  #
  ####################################################
  - alias: T- Restart HA When Some Devices Are Offline
    id: "1599910317895"
    description: ""
    trigger:
      - minutes: /10
        platform: time_pattern
    action:
      - choose:
          # Check LR Zigbee
          - conditions:
              - condition: state
                entity_id: binary_sensor.ground_toilet_motion_sensor_motion
                state: "unavailable"
            sequence:
              - service: notify.notify
                data:
                  title: "Restarting HA in 1 Min"
                  message: "LR Ground Toilet Sensor Is Offline. Restarting HA"
              - delay: "00:01:00"
              - service: homeassistant.restart
          # Check MR Zigbee
          - conditions:
              - condition: state
                entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
                state: "unavailable"
            sequence:
              - service: notify.notify
                data:
                  title: "Restarting HA in 1 Min"
                  message: "MR Master Toilet Sensor Is Offline. Restarting HA"
              - delay: "00:01:00"
              - service: homeassistant.restart
          # Check BLE devices
          - conditions:
              - condition: state
                entity_id: light.master_room_entrance_led_light
                state: "unavailable"
            sequence:
              - service: notify.notify
                data:
                  title: "Restarting HA in 1 Min"
                  message: "BLE Master Room Entrance Light Is Offline. Restarting HA"
              - delay: "00:01:00"
              - service: homeassistant.restart

automation brightness:
  - alias: L- Set up Indoor Brightness Based On Sun
    id: "1679065359421"
    trigger:
      - entity_id: sun.sun
        platform: state
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.indoor_brightness
        data:
          option: >
            {% if states('sun.sun') == 'below_horizon' %}
              dark
            {% else %}
              bright
            {% endif %}

automation alarm:
  - alias: A- Sound Alarm When Break-in Detected If No One Is Home
    id: "1679216351420"
    trigger:
      - platform: state
        to: "on"
        entity_id: group.alarm_motion
    condition:
      - condition: state
        entity_id: input_boolean.home_alarm
        for: 00:02:00
        state: "on"
    action:
      - service: notify.mobile_app_tais_iphone
        data:
          message: Break-in detected. Start to sound alarm in 30 seconds
          data:
            push:
              name: default
              critical: 1
              volume: 1
      - service: notify.mobile_app_kes_iphone11
        data:
          message: Break-in detected. Start to sound alarm in 30 seconds
          data:
            push:
              name: default
              critical: 1
              volume: 1

      - delay: "00:00:30"
      - condition: state
        entity_id: input_boolean.home_alarm
        for: 00:02:00
        state: "on"

      - service: media_player.play_media
        target:
          entity_id: media_player.master_toilet_echo
        data:
          media_content_type: routine
          media_content_id: Break in Pre Countdown Step One

      - delay: "00:00:15"
      - condition: state
        entity_id: input_boolean.home_alarm
        for: 00:02:00
        state: "on"

      - service: media_player.play_media
        target:
          entity_id: media_player.master_toilet_echo
        data:
          media_content_type: routine
          media_content_id: Break in Pre Countdown Step Two

      - delay: "00:00:10"
      - condition: state
        entity_id: input_boolean.home_alarm
        for: 00:02:00
        state: "on"

      - service: media_player.play_media
        target:
          entity_id: media_player.master_toilet_echo
        data:
          media_content_type: routine
          media_content_id: Break in Countdown

      - delay: "00:00:20"
      - condition: state
        entity_id: input_boolean.home_alarm
        for: 00:02:00
        state: "on"

      - service: media_player.play_media
        target:
          entity_id: media_player.master_toilet_echo
        data:
          media_content_type: routine
          media_content_id: Break in Post Countdown
