###########################################
#
# Custom Entities
#
###########################################
light:
  - platform: group
    name: Tais Desk Lamps
    entities:
      - light.tais_desk_lamp_1
      - light.tais_desk_lamp_2

  - platform: group
    name: Kes Desk Lamps
    entities:
      - light.kes_desk_lamp_1
      - light.kes_desk_lamp_2


input_boolean:
  # Use for detecting if there is an outstanding setting update scheduled
  tais_desk_outstanding_setting_update:
    name: "Tai's Desk Outstanding Setting Update"
    initial: "off"

  kes_desk_outstanding_setting_update:
    name: "Ke's Desk Outstanding Setting Update"
    initial: "off"
        
###############################################
#
# Automations
# - Lighting automation based on motion sensors
# - Lighting automation based on buttons
#
###############################################  
automation:
# Tais Desk  
# Lighting Automation based on motion sensors
- alias: L-OD Tai's Desk light On If Person Present Sits In the Chair
  description: ""
  trigger:
    #- entity_id: sensor.tais_desk_chair_movement_sensor
    #  platform: state
    #  to: "vibration"
    #- entity_id: sensor.tais_desk_chair_movement_sensor
    #  platform: state
    #  to: "tilt"
    - entity_id: binary_sensor.tais_desk_motion_sensor_motion
      platform: state
      from: "off"
      to: "on"      
  action:
    - service: light.turn_on
      entity_id: light.tais_desk_lamps
      # Only turn on screen LED in daytime
    - condition: time
      after: "06:00:00"
      before: "20:00:00"
    - service: switch.turn_on
      entity_id: switch.tais_desk_screen_led


- alias: L-OD Tai's Desk light Off If Person Left the Chair
  description: ""
  trigger:
    - entity_id: 
        #- sensor.tais_desk_chair_movement_sensor
        - binary_sensor.tais_desk_motion_sensor_motion
      platform: state
      to: "off"
      for: 00:10:00
    - minutes: /5
      platform: time_pattern
  condition:
    - entity_id: 
        #- sensor.tais_desk_chair_movement_sensor
        - binary_sensor.tais_desk_motion_sensor_motion    
      condition: state
      state: "off"
      for: 00:10:00
  action:
    - service: switch.turn_off
      entity_id: switch.tais_desk_screen_led
    - service: light.turn_off
      entity_id: light.tais_desk_lamps


#- alias: L-OD Tai's Desk light Update Setting When Turned On
#  id: '1607918423060'
#  description: ""
#  trigger:
#    - entity_id: light.tais_desk_lamps
#      platform: state
#      from: "off"
#      to: "on"
#  condition:
#    - entity_id: input_boolean.office_desk_outstanding_setting_update
#      condition: state
#      state: "on"
#  action:
#  - choose:
#      # Daylight setting
#      - conditions:
#          - condition: time
#            after: input_datetime.early_daylight_start
#        sequence:
#          - service: light.turn_on
#            entity_id: light.tais_desk_lamps
#            data: 
#              brightness: 255
#              kelvin: 5000      
#      # Nighttime setting setting
#      - conditions:
#          - condition: time
#            after:  input_datetime.nighttime_start
#            before: input_datetime.midnight_start
#        sequence:
#          - service: light.turn_on
#            entity_id: light.tais_desk_lamps
#            data: 
#              brightness: 255
#              kelvin: 3000      
#    # ELSE - Midnight setting
#    default:
#      - service: light.turn_on
#        entity_id: light.tais_desk_lamps
#        data: 
#          brightness: 65
#          kelvin: 3000     

- alias: L-OD Tai's Desk light Update Setting When Turned On
  id: '1607918423060'
  description: ""
  use_blueprint:
    path: update_setting_when_on.yaml
    input:
      target_light_list:                        light.tais_desk_lamps
      input_boolean_outstanding_setting_update: input_boolean.tais_desk_outstanding_setting_update

- alias: L-OD Ke's Desk Lights On If Person Sits In The Desk
  id: "1603640030053"
  description: ""
  trigger:
    - entity_id: binary_sensor.kes_desk_motion_sensor_motion
      platform: state
      from: "off"
      to: "on"
  action:
    - service: light.turn_on
      entity_id: light.kes_desk_lamps
    # Only turn on screen LED in daytime
    - condition: time
      after: "06:00:00"
      before: "20:00:00"
    - service: switch.turn_on
      entity_id: switch.kes_desk_screen_led


- alias: L-OD Ke's Desk Lights Off If Person Left Desk
  id: "1603640030054"
  description: ""
  trigger:
    - entity_id: binary_sensor.kes_desk_motion_sensor_motion
      platform: state
      from: "on"
      to: "off"
      for: 00:10:00
    - minutes: /5
      platform: time_pattern
  condition:
    - entity_id: binary_sensor.kes_desk_motion_sensor_motion
      condition: state
      state: "off"
      for: 00:10:00
  action:
    - service: light.turn_off
      entity_id: light.kes_desk_lamps
    - service: switch.turn_off
      entity_id: switch.kes_desk_screen_led


- alias: L-OD Ke's Desk light Update Setting When Turned On
  id: '1607918427957'
  description: ""
  use_blueprint:
    path: update_setting_when_on.yaml
    input:
      target_light_list:                        light.kes_desk_lamps
      input_boolean_outstanding_setting_update: input_boolean.kes_desk_outstanding_setting_update



# Lighting Automation based on buttons
- alias: B-BR Guest Room Button Double Press - Toggle Tai's Desk Screen LED/Desk Lamps
  trigger:
    - platform: state
      entity_id: sensor.guest_room_button
      to: double
  action:
    - service: switch.toggle
      entity_id: switch.tais_desk_screen_led
    - service: light.toggle
      entity_id: light.tais_desk_lamps

- alias: B-ST Study Button - Double Press - Toggle Ke's Desk Screen LED/Desk Lamps
  trigger:
    - platform: state
      entity_id: sensor.study_button
      to: double
    #- platform: event
    #  event_type: xiaomi_aqara.click
    #  event_data:
    #    entity_id: binary_sensor.study_button
    #    click_type: double
    #- platform: state
    #  entity_id: sensor.study_ceiling_light_wall_button
    #  to: double
  action:
    - service: switch.toggle
      entity_id: switch.kes_desk_screen_led
    - service: light.toggle
      entity_id: light.kes_desk_lamps
