###########################################
#
# Custom Entities
#
###########################################
group:
  whole_home_tv_slideshow:
    name: Whole Home TV Slideshow
    entities:
      - input_boolean.living_room_slideshow_enable
      - input_boolean.master_room_slideshow_enable
      - input_boolean.kitchen_slideshow_enable

  corridor_appliances:
    name: Corridor Appliances
    entities:
    - light.corridor_ceiling_light
    - climate.corridor

input_boolean:
  home_alarm:
    name: "Home Alarm"




###############################################
#
# Automations:
# - Lighting/Heating/Hot Water automation based on motion sensors
# - Actions based on buttons
# - Sonos Speakers Grouping/Ungrouping Based On Motion Sensor
#
###############################################
automation:
  - alias: H-Downstairs Zone Heating On When Heating Required
    id: downstairs_zone_heating_on
    trigger:
      - platform: state
        entity_id: 
        - group.downstairs_heating_required
      - minutes: /5
        platform: time_pattern        
    condition:    
      - condition: state
        entity_id: group.downstairs_heating_required      
        state: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.downstairs_heating

  - alias: H-Downstairs Zone Heating Off When No Heating Required
    id: downstairs_zone_heating_off
    trigger:
      - platform: state
        entity_id: 
        - group.downstairs_heating_required
      - minutes: /5
        platform: time_pattern        
    condition:    
    - condition: and
      conditions:
      - condition: state
        entity_id: group.downstairs_heating_required      
        state: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.downstairs_heating
      # Reduce the frequency of turning off the valve - to increase lifetime of the valve
      - delay: "00:12:00"

  - alias: H-Upstairs Zone Heating On When Heating Required
    id: upstairs_zone_heating_on
    trigger:
      - platform: state
        entity_id: 
        - group.upstairs_heating_required
      - minutes: /5
        platform: time_pattern        
    condition:    
      - condition: state
        entity_id: group.upstairs_heating_required      
        state: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.upstairs_heating
      
  - alias: H-Upstairs Zone Heating Off When No Heating Required
    id: upstairs_zone_heating_off
    trigger:
      - platform: state
        entity_id: 
        - group.upstairs_heating_required
      - minutes: /5
        platform: time_pattern        
    condition:    
    - condition: and
      conditions:
      - condition: state
        entity_id: group.upstairs_heating_required      
        state: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.upstairs_heating
      # Reduce the frequency of turning off the valve - to increase lifetime of the valve
      - delay: "00:12:00"
      
  ###############################################
  # Water Heating Automation based on motion sensors
  ###############################################

  - alias: W-DS Water Heater Start For 2 Hour And Schedule On If People Back From Journey
    id: "1600016351670"
    description: "automation.water_heater_start_and_schedule_on_if_people_back_from_journey"
    trigger:
      - platform: state
        to: "on"
        entity_id: group.indoor_motion
    condition: []
    mode: single
    action:
      - service: automation.turn_off
        entity_id: automation.water_heater_start_and_schedule_on_if_people_back_from_journey
        data:
          stop_actions: false
      - service: switch.turn_on
        entity_id: switch.water_heater
      # Delay turning on the scheudle so the water heater
      # does not get turn off by schedule until the water
      # has been heated for 2 hours
      - delay: 02:00:00
      - service: switch.turn_on
        entity_id: switch.schedule_water_heater

  - alias: W-DS Water Heater Schedule Off If People On Journey
    id: "1600016351671"
    description: ""
    trigger:
      - minutes: /5
        platform: time_pattern
    condition:
      - condition: state
        state: "off"
        for: 24:00:00
        entity_id: group.indoor_motion
    action:
      - service: switch.turn_off
        entity_id: switch.schedule_water_heater
      - service: automation.turn_on
        entity_id: automation.water_heater_start_and_schedule_on_if_people_back_from_journey

  ###############################################
  # Lighting Automation based on motion sensors
  ###############################################

  - alias: L-GC Corridor Lights On If People Present
    description: ""
    trigger:
      - entity_id: group.corridor_motion_group
        platform: state
        from: "off"
        to: "on"
    action:
      - service: light.turn_on
        entity_id: light.corridor_ceiling_light
        
  - alias: L-GC Ground Corridor Lights Off If No Person For 2 Min
    description: ""
    trigger:
      - entity_id: group.corridor_motion_group
        platform: state
        from: "on"
        to: "off"
        for: 00:02:00
      - minutes: /5
        platform: time_pattern
    condition:
      - condition: state
        entity_id: group.corridor_motion_group
        for: 00:02:00
        state: "off"
    action:
      - service: light.turn_off
        entity_id: light.corridor_ceiling_light


  ###############################################
  # Actions based on buttons
  ###############################################

  - alias: B-GC Ground Corridor Wall Switch - Doulbe Press - Turn Off Ground Floor Lights
    trigger:
      - entity_id: 
          - sensor.ground_corrdior_switch_wall_button
        platform: state
        to:
          - double_left
          - double_center
          - double_right
          - button_1_double
          - button_2_double
          - button_3_double
    condition: []
    action:
      - service: script.living_room_all_lights_turn_off
      - service: script.kitchen_all_lights_and_appliances_turn_off
      - service: light.turn_off
        entity_id: light.ground_toilet_ceiling_light

  #################################################################
  # Sonos Speakers Grouping/Ungrouping Based On Motion Sensor
  #################################################################

  # - alias: S-FC First Corridor Group Its Speaker If People Present In Corridor
  #   trigger:
  #     - platform: state
  #       from: "off"
  #       to: "on"
  #       entity_id:
  #         - binary_sensor.ground_corridor_motion_sensor_motion
  #         - binary_sensor.first_corridor_motion_sensor_motion
  #   condition:
  #     - condition: state
  #       entity_id: input_boolean.follow_music
  #       state: "on"
  #     # The controller player must be playing music (not paused)
  #     - condition: template
  #       value_template: >
  #         {% if states('media_player.' + states('input_select.music_controller')) == 'playing' %}
  #           true
  #         {% else %}
  #           false
  #         {% endif %}
  #   action:
  #     # Add this room speaker into the group
  #     - service: script.add_sonos_into_speaker_group
  #       data:
  #         target_player: media_player.first_corridor_sonos

  # - alias: S-FC First Corridor Ungroup/Pause Its Speaker If No People in Corridor or First Floor Rooms
  #   trigger:
  #     - platform: state
  #       from: "on"
  #       to: "off"
  #       for: 00:10:00
  #       entity_id:
  #         - binary_sensor.ground_corridor_motion_sensor_motion
  #         - binary_sensor.first_corridor_motion_sensor_motion
  #         - binary_sensor.en_suite_room_motion_sensor_motion
  #         - binary_sensor.guest_room_radiator_motion_sensor_motion
  #         - binary_sensor.guest_room_bed_motion_sensor_motion
  #         - binary_sensor.study_motion_sensor_motion
  #     - minutes: /5
  #       platform: time_pattern
  #   condition:
  #     - condition: state
  #       entity_id:
  #         - binary_sensor.ground_corridor_motion_sensor_motion
  #         - binary_sensor.first_corridor_motion_sensor_motion
  #         - binary_sensor.en_suite_room_motion_sensor_motion
  #         - binary_sensor.guest_room_radiator_motion_sensor_motion
  #         - binary_sensor.guest_room_bed_motion_sensor_motion
  #         - binary_sensor.study_motion_sensor_motion
  #       for: 00:10:00
  #       state: "off"
  #   action:
  #     - choose:
  #         # IF - music follower is on
  #         - conditions:
  #             - condition: state
  #               entity_id: input_boolean.follow_music
  #               state: "on"
  #           sequence:
  #             # Remove this room speaker from the group
  #             - service: script.remove_sonos_from_speaker_group
  #               data:
  #                 target_player: media_player.first_corridor_sonos
  #     # Pause this room speaker in case it is the last item in the group
  #     # or music follower is off
  #     - service: script.pause_sonos_if_sole_speaker_group
  #       data:
  #         target_player: media_player.first_corridor_sonos

