###########################################
#
# Custom Entities
#
###########################################

timer:
  garden_occupancy_timer:
    name: "Garden Occupancy Timer"
    duration: "03:00:00"

####################
# Automations
####################
automation:
  # Linked Switches
  - alias: B-LR Garden Wall Lights ON Controls Floor Spotlights
    id: "1603641040170"
    trigger:
      - platform: state
        to: "on"
        entity_id:
          - switch.garden_ceiling_light
    action:
      - service: switch.turn_on
        entity_id: 
         - switch.garden_spotlight_1
         - switch.garden_spotlight_2
         - switch.garden_spotlight_3         

  - alias: B-LR Garden Wall Lights OFF Controls Floor Spotlights
    id: "1603641040171"
    trigger:
      - platform: state
        to: "off"
        entity_id:
          - switch.garden_ceiling_light
    action:
      - service: switch.turn_off
        entity_id:
         - switch.garden_spotlight_1
         - switch.garden_spotlight_2
         - switch.garden_spotlight_3         
        

  - alias: B-LR Garden Decro Wall Switch ON Controls Decro Lights
    id: "1603641040172"
    trigger:
      - platform: state
        to: "on"
        entity_id: switch.garden_decro_wall_switch
    action:
      - service: switch.turn_on
        entity_id:
          - switch.garden_extension_lead_switch_2
          - switch.garden_extension_lead_switch_3

  - alias: B-LR Garden Decro Wall Switch OFF Controls Decro Lights
    id: "1603641040173"
    trigger:
      - platform: state
        to: "off"
        entity_id: switch.garden_decro_wall_switch
    action:
      - service: switch.turn_off
        entity_id:
          - switch.garden_extension_lead_switch_2
          - switch.garden_extension_lead_switch_3
