###########################################
#
# Custom Entities
#
###########################################

timer:
  garden_occupancy_timer:
    name: "Garden Occupancy Timer"
    duration: "03:00:00"

####################
# Automations
####################
automation:
