###########################################
#
# Custom Entities
#
###########################################

###############################################
#
# Automations
# - Lighting automation based on motion sensors
# - Lighting automation based on buttons
#
###############################################
automation:

  # Lighting Automation based on buttons
  #  - alias: B-GR Guest Room Button Double Press - Toggle Tai's Desk Screen LED/Desk Lamps
  #    id: "1433066657725"
  #    trigger:
  #      - platform: state
  #        entity_id: sensor.guest_room_button
  #        to: double
  #    action:
  #      - service: switch.toggle
  #        entity_id: switch.tais_desk_screen_led
  #      - service: light.toggle
  #        entity_id: light.tais_desk_lamps

#  - alias: L-ER Turn on En-suite Room Ceiling Light if desk light is on
#    id: "1433079656045"
#    trigger:
#      - platform: state
#        entity_id: switch.tais_desk_screen_led
#        to: "on"
#    #      - platform: state
#    #        entity_id: switch.kes_desk_screen_led
#    #        to: "on"
#    action:
#      - service: light.turn_on
#        entity_id: light.en_suite_room_ceiling_light
