###########################################
#
# Custom Entities
#
###########################################

# Custom Variables
input_boolean:
  # First Time Presence in a Room
  study_short_presence:
    name: "Study Short Presence"
    initial: "off"

group:
  study_appliances:
    name: Study Appliances
    entities:
      - climate.study
      - light.kes_desk_lamps
      - switch.kes_desk_screen_led
      - light.study_ceiling_light

###############################################
#
# Scripts
#
###############################################
script:
  study_ceiling_light_turn_on:
    alias: Study Ceiling Light Turn On
    mode: parallel
    max: 100
    sequence:
      - entity_id: switch.study_light
        service: switch.turn_on

  study_ceiling_light_turn_off:
    alias: Study Ceiling Light Turn off
    mode: parallel
    max: 100
    sequence:
      - entity_id: switch.study_light
        service: switch.turn_off

###############################################
#
# Automations:
# - Lighting/Heating automation based on motion sensors
# - Actions based on buttons
# - Maintaince on bedroom automation based on presence
#
###############################################
automation:
  ###############################################
  # Heating Automation based on motion sensors
  ###############################################
#  - alias: H-ST Study Heating Off If No Person
#    id: "1600015749444"
#    description: "automation.study_heating_off_if_no_person"
#    trigger:
#      - entity_id: binary_sensor.study_motion
#        for: 00:05:00
#        from: "on"
#        platform: state
#        to: "off"
#      - minutes: /5
#        platform: time_pattern
#    condition:
#      - condition: state
#        entity_id: binary_sensor.study_motion
#        for: 00:05:00
#        state: "off"
#    action:
#      # Heating scheduler off and turn on entering automation
#      - service: automation.turn_off
#        entity_id: automation.study_heating_scheduler
#      - service: climate.set_hvac_mode
#        entity_id: climate.study
#        data:
#          hvac_mode: "off"
#      - entity_id: automation.study_turn_on_heating_schedule_if_people_present
#        service: automation.turn_on
#
#  - alias: H-ST Study Turn On Heating Schedule If People Present
#    id: "1600014331228"
#    description: "automation.study_turn_on_heating_schedule_if_people_present"
#    use_blueprint:
#      path: room_delayed_action.yaml
#      input:
#        binary_sensor_motion_sensors: binary_sensor.study_motion
#        input_boolean_short_presence: input_boolean.study_short_presence
#        automation_this_automation_entity: automation.study_turn_on_heating_schedule_if_people_present
#        automations_to_be_triggered_and_on: automation.study_heating_scheduler
#
#  - alias: H-ST Study Turn On Heating Schedule
#    id: "1600014331351"
#    description: "automation.study_heating_scheduler"
#    trigger:
#      # Never trigger
#    action:
#      - data:
#          hvac_mode: heat
#        entity_id: climate.study
#        service: climate.set_hvac_mode
#      - data:
#          temperature: 23
#        entity_id: climate.study
#        service: climate.set_temperature
#
#  ###############################################
#  # Lighting Automation based on motion sensors
#  ###############################################
#  - alias: L-ST Study Ceiling Light On If People Present
#    id: "1603640030051"
#    description: ""
#    trigger:
#      - entity_id: binary_sensor.study_motion_sensor_motion
#        platform: state
#        from: "off"
#        to: "on"
#    condition:
#      - condition: and
#        conditions:
#          - entity_id: binary_sensor.study_motion_sensor_motion
#            condition: state
#            state: "on"
#          - entity_id: sensor.study_motion_sensor_light
#            condition: numeric_state
#            below: '200'
#    action:
#      - service: light.turn_on
#        entity_id: light.study_ceiling_light
#
#  - alias: L-ST Study Lights Off If No People Present For 5 Min
#    id: "1603640030052"
#    description: ""
#    trigger:
#      - entity_id: binary_sensor.study_motion
#        platform: state
#        from: "on"
#        to: "off"
#        for: 00:10:00
#      - minutes: /5
#        platform: time_pattern
#    condition:
#      - entity_id: binary_sensor.study_motion
#        condition: state
#        state: "off"
#        for: 00:10:00
#    action:
#      - service: homeassistant.turn_off
#        entity_id: group.study_appliances
#
  ###############################################
  # Actions based on buttons
  ###############################################
#  - alias: B-ST Study Wall Switch - Single Press - Toggle Ceiling Light
#    trigger:
#      - platform: state
#        entity_id: sensor.study_wall_button
#        to: single
#    action:
#    - service: light.toggle
#      entity_id: light.study_ceiling_light
#    #  - choose:
    #      # IF - all lights off - turn on ceiling light
    #      - conditions:
    #          - condition: state
    #            entity_id: 
    #              - light.study_ceiling_light
    #              - light.kes_desk_lamps
    #              - switch.kes_desk_screen_led
    #            state: 'off'
    #        sequence:
    #          - service: light.turn_on
    #            entity_id: light.study_ceiling_light
    #    # ELSE - some lights on - turn off all lights
    #    default:
    #      - service: homeassistant.turn_off
    #        entity_id: group.study_appliances
#            
#  - alias: B-ST Study Button Long Press - Toggle Ceiling Lights
#    trigger:
#      - platform: state
#        entity_id: sensor.study_button
#        to: hold
#      #- platform: event
#      #  event_type: xiaomi_aqara.click
#      #  event_data:
#      #    entity_id: binary_sensor.study_button
#      #    click_type: single
#    action:
#      - service: light.toggle
#        entity_id: light.study_ceiling_light
#  

  ###############################################
  # Office Desk automations
  ###############################################
  - alias: L-OD Ke's Desk Lights On If Person Present
    id: "1603640030053"
    description: ""
    trigger:
      - entity_id: binary_sensor.kes_desk_motion_sensor_motion
        platform: state
        from: "off"
        to: "on"
    action:
      - service: light.turn_on
        entity_id: 
          - light.kes_desk_lamps
          - light.study_ceiling_light
      # Only turn on screen LED in daytime
      - condition: time
        after: "06:00:00"
        before: "20:00:00"
      - service: switch.turn_on
        entity_id: switch.kes_desk_screen_led

  - alias: L-OD Ke's Desk Lights Off If Person Left Desk
    id: "1603640030054"
    description: ""
    trigger:
      - entity_id: binary_sensor.kes_desk_motion_sensor_motion
        platform: state
        from: "on"
        to: "off"
        for: 00:10:00
      - minutes: /5
        platform: time_pattern
    condition:
      - entity_id: binary_sensor.kes_desk_motion_sensor_motion
        condition: state
        state: "off"
        for: 00:10:00
    action:
      - service: light.turn_off
        entity_id: light.kes_desk_lamps
      - service: switch.turn_off
        entity_id: switch.kes_desk_screen_led

  - alias: B-ST Study Button - Single Press - Toggle Ke's Desk Lamps
    id: automation.study_button_single_press_toggle_kes_desk_lamps
    trigger:
      - platform: state
        entity_id: sensor.study_button
        to: double
      #- platform: event
      #  event_type: xiaomi_aqara.click
      #  event_data:
      #    entity_id: binary_sensor.study_button
      #    click_type: double
    action:
      - service: light.toggle
        entity_id: light.kes_desk_lamps

  - alias: B-ST Study Button - Double Press - Toggle Ke's Desk Screen LED
    id: automation.study_button_double_press_toggle_kes_desk_screen_led
    trigger:
      - platform: state
        entity_id: sensor.study_button
        to: double
      #- platform: event
      #  event_type: xiaomi_aqara.click
      #  event_data:
      #    entity_id: binary_sensor.study_button
      #    click_type: double
    action:
      - service: switch.toggle
        entity_id: switch.kes_desk_screen_led
