homeassistant: true
mqtt:
  server: mqtt://core-mosquitto
  user: mqtt_user
  password: mqtt_pass
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_4e7c27d91f3bec1197309e957a0af07f-if00-port0
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: debug
device_options:
  legacy: false
devices:
  '0x00158d00045f640a':
    friendly_name: Upstairs Heating Wall Switch
  '0x00158d00052e2124':
    friendly_name: Master Room Entrance Wall Switch
  '0x001788010c4c1cc8':
    friendly_name: E27 HUE W Z2M 4
  '0x001788010c45edfc':
    friendly_name: E27 HUE W Z2M 3
  '0x001788010c45f13e':
    friendly_name: E27 HUE W Z2M 1
  '0x001788010c45f2d5':
    friendly_name: E27 HUE W Z2M 2
  '0x00158d00054750ca':
    friendly_name: Master Toilet Shower Motion Sensor
  '0x04cf8cdf3c7ad647':
    friendly_name: Kitchen Wall Switch
  '0x00158d0005210fa9':
    friendly_name: Kitchen Extractor Wall Switch
  '0x00158d000522e00e':
    friendly_name: Garden Light Wall Switch
  '0x00158d00048783e5':
    friendly_name: Ground Corridor Wall Switch
  '0x00158d0005210fcf':
    friendly_name: First Corridor Wall Switch
  '0x00158d00045245be':
    friendly_name: Study Wall Switch
  '0x00158d00047b69d2':
    friendly_name: Guest Room Wall Switch
  '0x00158d000487851a':
    friendly_name: Guest Toilet Wall Switch
  '0x00158d000424f995':
    friendly_name: Living Room Button
  '0x00158d0003140ea8':
    friendly_name: Living Room TV Motion Sensor
  '0x00158d00012262a5':
    friendly_name: Master Room Button 1
  '0x00158d000424f98c':
    friendly_name: Master Room Button 2
  '0x00158d00054a6f3a':
    friendly_name: Master Room Drawer Motion Sensor
  '0x00158d000460247b':
    friendly_name: Master Toilet Dressing Room Motion Sensor
  '0x00158d00054deda4':
    friendly_name: Master Room Stair Motion Sensor
  '0x00158d000122393b':
    friendly_name: Master Room Entrance Motion Sensor
  '0x00158d0004525183':
    friendly_name: First Corridor Motion Sensor
  '0x00158d00054a6eb9':
    friendly_name: Study Motion Sensor
  '0x00158d00052b35f7':
    friendly_name: Guest Toilet Motion Sensor
  '0x00158d00045019fd':
    friendly_name: Ground Corridor Motion Sensor
  '0x00158d00052d5691':
    friendly_name: Ground Toilet Door
  '0x00158d0005227632':
    friendly_name: Downstairs Heating Wall Switch
  '0x00158d0004501b0a':
    friendly_name: Living Room Sofa Motion Sensor
  '0x00158d0001212747':
    friendly_name: Boiler Room Door
  '0x00158d000548b8a5':
    friendly_name: Living Room Sliding Door Motion Sensor
  '0x00158d00057acaac':
    friendly_name: Kitchen Dining Motion Sensor
  '0x00158d0004660308':
    friendly_name: Kitchen Worktop Motion Sensor
  '0x00158d00053e96ae':
    friendly_name: Guest Toilet Door
  '0x00158d000171bd29':
    friendly_name: Master Room Dressing Table Motion Sensor
  '0x04cf8cdf3c7b36b1':
    friendly_name: Master Room Light Meter
  '0x04cf8cdf3c73a19b':
    friendly_name: Master Room Curtain
  '0x00158d00053e95f6':
    friendly_name: Master Room Balcony Door
  '0x00158d00053fdaa8':
    friendly_name: Master Toilet Door
  '0x00158d00057b2b4c':
    friendly_name: Master Toilet Basin Motion Sensor
  '0x00158d00023e6015':
    friendly_name: '0x00158d00023e6015'
