homeassistant: true
mqtt:
  server: mqtt://core-mosquitto
  user: mqtt_user
  password: mqtt_pass
  keepalive: 60
  reject_unauthorized: true
  version: 4
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_4e7c27d91f3bec1197309e957a0af07f-if00-port0
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_level: info
device_options:
  legacy: false
devices:
  '0x00158d00052e2124':
    friendly_name: Master Room Entrance Wall Switch
  '0x04cf8cdf3c7ad647':
    friendly_name: Kitchen Wall Switch
  '0x00158d00045245be':
    friendly_name: Study Wall Switch
  '0x00158d000487851a':
    friendly_name: Guest Toilet Wall Switch
  '0x00158d00012262a5':
    friendly_name: Master Room Button 1
  '0x00158d00054a6f3a':
    friendly_name: Master Room Drawer Motion Sensor
  '0x00158d00054deda4':
    friendly_name: Master Room Stair Motion Sensor
  '0x00158d000122393b':
    friendly_name: Master Room Entrance Motion Sensor
  '0x00158d00054a6eb9':
    friendly_name: Study Motion Sensor
  '0x00158d00052b35f7':
    friendly_name: Guest Toilet Motion Sensor
  '0x00158d0005227632':
    friendly_name: Downstairs Heating Wall Switch
  '0x00158d0004501b0a':
    friendly_name: Living Room Sofa Motion Sensor
  '0x00158d0001212747':
    friendly_name: Boiler Room Door
  '0x00158d00053e96ae':
    friendly_name: Guest Toilet Door
  '0x00158d000171bd29':
    friendly_name: Master Room Dressing Table Motion Sensor
  '0x04cf8cdf3c7b36b1':
    friendly_name: Master Room Light Meter
  '0x00158d00053e95f6':
    friendly_name: Master Room Balcony Door
  '0x00158d00054750ca':
    friendly_name: '0x00158d00054750ca'
  '0x00158d00057b2b4c':
    friendly_name: '0x00158d00057b2b4c'
  '0x00158d000460247b':
    friendly_name: '0x00158d000460247b'
  '0x90fd9ffffe8e24b6':
    friendly_name: '0x90fd9ffffe8e24b6'
  '0x000b57fffee8e6b4':
    friendly_name: '0x000b57fffee8e6b4'
  '0x842e14fffe60b64a':
    friendly_name: '0x842e14fffe60b64a'
  '0x00158d00052d5691':
    friendly_name: '0x00158d00052d5691'
  '0x00158d00045f640a':
    friendly_name: '0x00158d00045f640a'
  '0x00158d000424f98c':
    friendly_name: '0x00158d000424f98c'
  '0x54ef4410001f409c':
    friendly_name: '0x54ef4410001f409c'
  '0x00158d0005475079':
    friendly_name: '0x00158d0005475079'
  '0x04cf8cdf3c7976f8':
    friendly_name: '0x04cf8cdf3c7976f8'
  '0x04cf8cdf3c797717':
    friendly_name: '0x04cf8cdf3c797717'
groups:
  '123':
    friendly_name: ground_toilet_ceiling_light_z2m
    devices:
      - 0x000b57fffee8e6b4/1
      - 0x90fd9ffffe8e24b6/1
