#-------------------
# Last Alexa Sensor
#-------------------
group:
  all_echos:
    name: All Echos
    entities:
      - media_player.master_toilet_echo
      - media_player.master_room_echo
      - media_player.kitchen_echo
      - media_player.living_room_echo

template:
  - sensor:
      - name: Last Alexa
      # entity_id: last_alexa
        state: >
          {{ expand('group.all_echos') | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first | replace('media_player.','') | replace('_echo','') }}
        availability: >
          {{ expand('group.all_echos') | selectattr('attributes.last_called','eq',True) | first is defined }}

#----------------
# Emulated Hue
#----------------
emulated_hue:
  listen_port: 80
  expose_by_default: false
  # Make sure "hidden:false" is always attached - otherwise HA would not be found the devices
  # N.B.
  # As per Emulated Hue documentation, ONLY UP TO 49 DEVICES can be supported by this integration.
  # There are 31 devices now
  entities:
    ###################################
    # HA script - using a fake light brightness to call scripts - 1 devices
    ###################################
    light.emulated_hue_ha_script:
      name: "HA Scripts"
      hidden: false
    ###################################
    # Non-light Devices - 0 devices
    ###################################
    ###################################
    # Master Room  - 8 devices
    ###################################
    # Alexa, set the Master Room Thermostat to 23
    light.master_room_lamp_1:
      name: "Master Room Left Lamp"
      hidden: false
    light.master_room_lamp_2:
      name: "Master Room Right Lamp"
      hidden: false
    light.master_room_ceiling_lights:
      name: "Master Room Ceiling Light"
      hidden: false
    light.master_room_leds:
      name: "Master Room LED"
      hidden: false
    switch.master_room_dressing_table_light:
      name: "Master Room Dressing Table Light"
      hidden: false
    light.master_room_entrance_led_light:
      name: "Master Room Entrance Light"
      hidden: false
    ###################################
    # Master Toilet  - 2 devices
    ###################################
    light.master_toilet_ceiling_light:
      name: "Master Toilet Ceiling Light"
      hidden: false
    switch.master_toilet_floor_led:
      name: "Master Toilet Floor LED"
      hidden: false
    ###################################
    # Guest Room  - 1 devices
    ###################################
    light.guest_room_ceiling_light:
      name: "Guest Room Ceiling Light"
      hidden: false
    ###################################
    # Living Room - 4 devices
    ###################################
    light.living_room_led:
      name: "Living Room LED"
      hidden: false
    light.living_room_floor_light:
      name: "Living Room Floor Light"
      hidden: false
    # Boiler Room
    light.boiler_room_light:
      name: "Boiler Room Light"
      hidden: false
    # Garden
    switch.garden_wall_light:
      name: "Garden Light"
      hidden: false
    ###################################
    # Kitchen - 5 devices
    ###################################
    light.kitchen_ceiling_light:
      name: "Kitchen Ceiling Light"
      hidden: false
    light.kitchen_dining_light:
      name: "Kitchen Dining Light"
      hidden: false
    switch.kitchen_floor_led:
      name: "Kitchen Floor LED"
      hidden: false
    switch.kitchen_worktop_led_left:
      name: "Kitchen Worktop LED Left"
      hidden: false
    switch.kitchen_worktop_led_right:
      name: "Kitchen Worktop LED Right"
      hidden: false
    ###################################
    # Ground Toilet - 1 devices
    ###################################
    light.ground_toilet_ceiling_light:
      name: "Ground Toilet Ceiling Light"
      hidden: false
    ###################################
    # Study - 1 devices
    ###################################
    light.study_ceiling_light:
      name: "Study Ceiling Light"
      hidden: false
    ###################################
    # En-suite Room - 6 devices
    ###################################
    light.en_suite_room_ceiling_light:
      name: "En-suite Room Ceiling Light"
      hidden: false
    light.en_suite_room_bed_led:
      name: "En-suite Room Bed LED"
      hidden: false
    # Office
    light.kes_desk_lamps:
      name: "Kes Desk Lamp"
      hidden: false
    switch.kes_desk_screen_led:
      name: "Kes Desk Screen LED"
      hidden: false
    light.tais_desk_lamps:
      name: "Tais Desk Lamp"
      hidden: false
    switch.tais_desk_screen_led:
      name: "Tais Desk Screen LED"
      hidden: false

# Switches for Emulated Hue
switch emulated_hue:
  - platform: template
    switches:
      master_room_blind:
        value_template: "{{ is_state('cover.master_room_blind', 'open') }}"
        turn_on:
          service: cover.open_cover
          target:
            entity_id: cover.master_room_blind
        turn_off:
          service: cover.close_cover
          target:
            entity_id: cover.master_room_blind

      master_room_curtain:
        value_template: "{{ is_state('cover.master_room_curtain', 'open') }}"
        turn_on:
          service: cover.open_cover
          target:
            entity_id: cover.master_room_curtain
        turn_off:
          service: cover.close_cover
          target:
            entity_id: cover.master_room_curtain

# Fake Light - using its brightness to call scripts from Alexa
light:
  - platform: template
    lights:
      emulated_hue_ha_script:
        friendly_name: "Emulated Hue HA Script"
        turn_on:
          service: script.do_nothing
        turn_off:
          service: script.do_nothing
        set_level:
          service: script.do_nothing
          data:
            brightness: "{{ brightness }}"


script:
  alexa_set_tv_brightness_to_dynamic:
    sequence:
    - service: pyscript.alexa_set_tv_brightness
      data:
        brightness: 'Dynamic'

  alexa_set_tv_brightness_to_standard:
    sequence:
    - service: pyscript.alexa_set_tv_brightness
      data:
        brightness: 'Standard'

  alexa_set_tv_brightness_to_natural:
    sequence:
    - service: pyscript.alexa_set_tv_brightness
      data:
        brightness: 'Natural'

  alexa_set_tv_brightness_to_movie:
    sequence:
    - service: pyscript.alexa_set_tv_brightness
      data:
        brightness: 'Movie'

  turn_on_gaming_pc:
    sequence:
    - service: switch.turn_on
      entity_id: switch.gaming_pc

  turn_off_gaming_pc:
    sequence:
    - service: switch.turn_off
      entity_id: switch.gaming_pc

  turn_on_old_laptop:
    sequence:
    - service: switch.turn_on
      entity_id: switch.old_laptop

  turn_off_old_laptop:
    sequence:
    - service: switch.turn_off
      entity_id: switch.old_laptop

  doorbell_notify_ha_users:
    sequence:
    - service: script.do_nothing #TODO
   
automation:
  - alias: E- Emulated Hue HA Script
    id: "1939270046562"
    trigger:
      - platform: state
        entity_id: light.emulated_hue_ha_script
        to: "on"
      - platform: state
        entity_id: light.emulated_hue_ha_script
        attribute: brightness
    action:
      # Delay for a bit for the brightness value to be up-to-date
      - delay: "00:00:01"
      - service: >
            {% set script_brightness = ((state_attr('light.emulated_hue_ha_script', 'brightness')/255*100)|round) %}

            {% if   script_brightness == 1 %}
                script.do_nothing                

            {% elif script_brightness == 6 %}
                script.master_room_open_curtain                
                
            {% elif script_brightness == 7 %}
                script.master_room_close_curtain                 

            {% elif script_brightness == 8 %}
                script.master_room_open_blind                
                
            {% elif script_brightness == 9 %}
                script.master_room_close_blind
                
            {% elif script_brightness == 10 %}
                script.master_room_tv_sleep_timer_start

            {% elif script_brightness == 11 %}
                script.find_tais_iphone_13

            {% elif script_brightness == 12 %}
                script.find_tais_iphone_8

            {% elif script_brightness == 13 %}
                script.find_tais_iphone_6

            {% elif script_brightness == 14 %}
                script.find_tais_ipad

            {% elif script_brightness == 15 %}
                script.find_tais_macbook_air

            {% elif script_brightness == 16 %}
                script.find_kes_iphone_11

            {% elif script_brightness == 17 %}
                script.find_kes_iphone_8

            {% elif script_brightness == 18 %}
                script.find_kes_macbook_air

            {% elif script_brightness == 19 %}
                script.alexa_set_tv_brightness_to_dynamic

            {% elif script_brightness == 20 %}
                script.alexa_set_tv_brightness_to_standard

            {% elif script_brightness == 21 %}
                script.alexa_set_tv_brightness_to_natural

            {% elif script_brightness == 22 %}
                script.alexa_set_tv_brightness_to_movie

            {% elif script_brightness == 23 %}
                script.turn_on_gaming_pc

            {% elif script_brightness == 24 %}
                script.turn_off_gaming_pc

            {% elif script_brightness == 24 %}
                script.doorbell_notify_ha_users

            {% else %}
                script.do_nothing      
                
            {% endif %}
            
      # Restore the default value and delay for a bit
      - delay: "00:00:02"
      - service: light.turn_on
        entity_id: light.emulated_hue_ha_script
        data:
          brightness_pct: 1
      - service: light.turn_off
        entity_id: light.emulated_hue_ha_script


