###########################################
#
# Custom Entities
#
###########################################
group:
  corridor_motion:
    name: Corridor Motion
    entities:
      - binary_sensor.ground_corridor_motion_sensor_motion
      - binary_sensor.first_corridor_motion_sensor_motion

  whole_home_tv_slideshow:
    name: Whole Home TV Slideshow
    entities:
      - input_boolean.living_room_slideshow_enable
      - input_boolean.master_room_slideshow_enable
      - input_boolean.kitchen_slideshow_enable

  corridor_appliances:
    name: Corridor Appliances
    entities:
    - light.corridor_light
    - climate.ground_corridor

input_boolean:
  home_alarm:
    name: "Home Alarm"

# Helper sensors for detecting requirement for downstairs/upstairs heating
template:
  - binary_sensor:
      - name: "Upstairs Heating Required"
        state: >
          {{ ((states.climate.master_toilet.attributes.temperature         > 
               states.climate.master_toilet.attributes.current_temperature     )  and 
              (states.climate.master_toilet.state != 'off')                          ) or

             ((states.climate.master_room.attributes.temperature         > 
               states.climate.master_room.attributes.current_temperature     )  and 
              (states.climate.master_room.state != 'off')                          ) or
             
             ((states.climate.study.attributes.temperature         > 
               states.climate.study.attributes.current_temperature     )  and 
              (states.climate.study.state != 'off')                          ) or
              
             ((states.climate.guest_toilet.attributes.temperature         > 
               states.climate.guest_toilet.attributes.current_temperature     )  and 
              (states.climate.guest_toilet.state != 'off')                          ) or

             ((states.climate.guest_room.attributes.temperature         > 
               states.climate.guest_room.attributes.current_temperature     )  and 
              (states.climate.guest_room.state != 'off')                          ) or

             ((states.climate.en_suite_toilet.attributes.temperature         > 
               states.climate.en_suite_toilet.attributes.current_temperature     )  and 
              (states.climate.en_suite_toilet.state != 'off')                          ) or

             ((states.climate.en_suite_room.attributes.temperature         > 
               states.climate.en_suite_room.attributes.current_temperature     )  and 
              (states.climate.en_suite_room.state != 'off')                          ) 
          }}

  - binary_sensor:
      - name: "Downstairs Heating Required"
        state: >
          {{ ((states.climate.kitchen.attributes.temperature         > 
               states.climate.kitchen.attributes.current_temperature     )  and 
              (states.climate.kitchen.state != 'off')                          ) or

             ((states.climate.living_room.attributes.temperature         > 
               states.climate.living_room.attributes.current_temperature     )  and 
              (states.climate.living_room.state != 'off')                          ) or
             
             ((states.climate.ground_toilet.attributes.temperature         > 
               states.climate.ground_toilet.attributes.current_temperature     )  and 
              (states.climate.ground_toilet.state != 'off')                          ) or
              
             ((states.climate.ground_corridor.attributes.temperature         > 
               states.climate.ground_corridor.attributes.current_temperature     )  and 
              (states.climate.ground_corridor.state != 'off')                          ) 
          }}


###############################################
#
# Scripts
#
###############################################
script:
  corridor_lights_turn_on:
    alias: Corridor Lights Turn On
    max: 100
    mode: parallel
    sequence:
      - service: light.turn_on
        entity_id: light.corridor_light

  corridor_lights_turn_off:
    alias: Corridor Lights Turn Off
    max: 100
    mode: parallel
    sequence:
      - service: light.turn_off
        entity_id: light.corridor_light

###############################################
#
# Automations:
# - Lighting/Heating/Hot Water automation based on motion sensors
# - Actions based on buttons
# - Sonos Speakers Grouping/Ungrouping Based On Motion Sensor
#
###############################################
automation:
  ###############################################
  # Heating Automation based on motion sensors
  ###############################################
#  - alias: H-GC Ground Corrdior Heating Set to 20 If People Present
#    id: "1599611792932"
#    description: "automation.ground_corrdior_heating_on_if_people_present"
#    trigger:
#      - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
#        platform: state
#        from: "off"
#        to: "on"
#    condition: []
#    action:
#      - data:
#          hvac_mode: heat
#        entity_id: climate.ground_corridor
#        service: climate.set_hvac_mode
#      - data:
#          temperature: 20
#        entity_id: climate.ground_corridor
#        service: climate.set_temperature
#
#  - alias: H-GC Ground Corridor Heating Off If No Person For 20 Min
#    id: "1599611696918"
#    description: "automation.ground_corridor_heating_off_if_no_person"
#    trigger:
#      - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
#        platform: state
#        from: "on"
#        to: "off"
#        for: 00:20:00
#      - minutes: /5
#        platform: time_pattern
#    condition:
#      - condition: and
#        conditions:
#          - condition: state
#            entity_id: binary_sensor.ground_corridor_motion_sensor_motion
#            for: 00:20:00
#            state: "off"
#          - condition: state
#            entity_id: binary_sensor.first_corridor_motion_sensor_motion
#            for: 00:20:00
#            state: "off"
#    action:
#      - service: climate.set_hvac_mode
#        entity_id: climate.ground_corridor
#        data:
#          hvac_mode: "off"

  - alias: H-DS Downstairs Zone Heating On When Heating Required
    id: "1599612133872"
    trigger:
      - platform: state
        entity_id: binary_sensor.downstairs_heating_required
        to: "on"
      - minutes: /5
        platform: time_pattern        
    condition:    
      - condition: state
        entity_id: binary_sensor.downstairs_heating_required      
        state: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.downstairs_heating

  - alias: H-DS Downstairs Zone Heating Off When No Heating Required
    id: "1599653387645"
    trigger:
      - platform: state
        entity_id: binary_sensor.downstairs_heating_required
        to: "off"
      - minutes: /5
        platform: time_pattern        
    condition:    
      - condition: state
        entity_id: binary_sensor.downstairs_heating_required      
        state: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.downstairs_heating

  - alias: H-US Upstairs Zone Heating On When Heating Required
    id: "1600016150575"
    trigger:
      - platform: state
        entity_id: binary_sensor.upstairs_heating_required
        to: "on"
    # It's possible that the turn-on command is sent to Xiaomi gateway but 
    # the physical switch never takes the action. Make sure the command 
    # is sent repetively.
      - minutes: /5
        platform: time_pattern    
    condition:    
      - condition: state
        entity_id: binary_sensor.upstairs_heating_required      
        state: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.upstairs_heating

  - alias: H-US Upstairs Zone Heating Off When No Heating Required
    id: "1600017150562"
    trigger:
      - platform: state
        entity_id: binary_sensor.upstairs_heating_required
        to: "off"
      - minutes: /5
        platform: time_pattern        
    condition:    
      - condition: state
        entity_id: binary_sensor.upstairs_heating_required      
        state: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.upstairs_heating

  ###############################################
  # Water Heating Automation based on motion sensors
  ###############################################

  - alias: W-DS Water Heater Start For 2 Hour And Schedule On If People Back From Journey
    id: "1600016351670"
    description: "automation.water_heater_start_and_schedule_on_if_people_back_from_journey"
    trigger:
      - platform: state
        to: "on"
        entity_id: group.indoor_motion
    condition: []
    mode: single
    action:
      - service: automation.turn_off
        entity_id: automation.water_heater_start_and_schedule_on_if_people_back_from_journey
        data:
          stop_actions: false
      - service: switch.turn_on
        entity_id: switch.water_heater
      # Delay turning on the scheudle so the water heater
      # does not get turn off by schedule until the water
      # has been heated for 2 hours
      - delay: 02:00:00
      - service: switch.turn_on
        entity_id: switch.schedule_water_heater

  - alias: W-DS Water Heater Schedule Off If People On Journey
    id: "1600016351671"
    description: ""
    trigger:
      - minutes: /5
        platform: time_pattern
    condition:
      - condition: state
        state: "off"
        for: 24:00:00
        entity_id: group.indoor_motion
    action:
      - service: switch.turn_off
        entity_id: switch.schedule_water_heater
      - service: automation.turn_on
        entity_id: automation.water_heater_start_and_schedule_on_if_people_back_from_journey

  ###############################################
  # Lighting Automation based on motion sensors
  ###############################################

  - alias: L-GC Corridor Lights On If People Present
    description: ""
    trigger:
      - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
        platform: state
        from: "off"
        to: "on"
      - entity_id: binary_sensor.first_corridor_motion_sensor_motion
        platform: state
        from: "off"
        to: "on"
    condition:
      - condition: or
        conditions:
          - condition: and
            conditions:
              - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
                condition: state
                state: "on"
            #- entity_id: sensor.ground_corridor_motion_sensor_light
            #  condition: numeric_state
            #  below: '50'
          - condition: and
            conditions:
              - entity_id: binary_sensor.first_corridor_motion_sensor_motion
                condition: state
                state: "on"
            #- entity_id: sensor.first_corridor_motion_sensor_light
            #  condition: numeric_state
            #  below: '50'
    action:
      - service: script.corridor_lights_turn_on

  - alias: L-GC Ground Corridor Lights Off If No Person For 2 Min
    description: ""
    trigger:
      - entity_id: binary_sensor.ground_corridor_motion_sensor_motion
        platform: state
        from: "on"
        to: "off"
        for: 00:02:00
      - entity_id: binary_sensor.first_corridor_motion_sensor_motion
        platform: state
        from: "on"
        to: "off"
        for: 00:02:00
      - minutes: /5
        platform: time_pattern
    condition:
      - condition: state
        entity_id: binary_sensor.ground_corridor_motion_sensor_motion
        for: 00:02:00
        state: "off"
      - condition: state
        entity_id: binary_sensor.first_corridor_motion_sensor_motion
        for: 00:02:00
        state: "off"
    action:
      - service: script.corridor_lights_turn_off



  ###############################################
  # Actions based on buttons
  ###############################################

  - alias: B-GC Ground Corridor Wall Switch - Doulbe Press - Turn Off Ground Floor Lights
    trigger:
      - entity_id: sensor.ground_corrdior_switch_wall_button
        platform: state
        to:
          - double_left
          - double_center
          - double_right
          - button_1_double
          - button_2_double
          - button_3_double
    condition: []
    action:
      - service: script.living_room_all_lights_turn_off
      - service: script.kitchen_all_lights_and_appliances_turn_off
      - service: light.turn_off
        entity_id: light.ground_toilet_ceiling_light

  #################################################################
  # Sonos Speakers Grouping/Ungrouping Based On Motion Sensor
  #################################################################

  # - alias: S-FC First Corridor Group Its Speaker If People Present In Corridor
  #   trigger:
  #     - platform: state
  #       from: "off"
  #       to: "on"
  #       entity_id:
  #         - binary_sensor.ground_corridor_motion_sensor_motion
  #         - binary_sensor.first_corridor_motion_sensor_motion
  #   condition:
  #     - condition: state
  #       entity_id: input_boolean.follow_music
  #       state: "on"
  #     # The controller player must be playing music (not paused)
  #     - condition: template
  #       value_template: >
  #         {% if states('media_player.' + states('input_select.music_controller')) == 'playing' %}
  #           true
  #         {% else %}
  #           false
  #         {% endif %}
  #   action:
  #     # Add this room speaker into the group
  #     - service: script.add_sonos_into_speaker_group
  #       data:
  #         target_player: media_player.first_corridor_sonos

  # - alias: S-FC First Corridor Ungroup/Pause Its Speaker If No People in Corridor or First Floor Rooms
  #   trigger:
  #     - platform: state
  #       from: "on"
  #       to: "off"
  #       for: 00:10:00
  #       entity_id:
  #         - binary_sensor.ground_corridor_motion_sensor_motion
  #         - binary_sensor.first_corridor_motion_sensor_motion
  #         - binary_sensor.en_suite_room_motion_sensor_motion
  #         - binary_sensor.guest_room_radiator_motion_sensor_motion
  #         - binary_sensor.guest_room_bed_motion_sensor_motion
  #         - binary_sensor.study_motion_sensor_motion
  #     - minutes: /5
  #       platform: time_pattern
  #   condition:
  #     - condition: state
  #       entity_id:
  #         - binary_sensor.ground_corridor_motion_sensor_motion
  #         - binary_sensor.first_corridor_motion_sensor_motion
  #         - binary_sensor.en_suite_room_motion_sensor_motion
  #         - binary_sensor.guest_room_radiator_motion_sensor_motion
  #         - binary_sensor.guest_room_bed_motion_sensor_motion
  #         - binary_sensor.study_motion_sensor_motion
  #       for: 00:10:00
  #       state: "off"
  #   action:
  #     - choose:
  #         # IF - music follower is on
  #         - conditions:
  #             - condition: state
  #               entity_id: input_boolean.follow_music
  #               state: "on"
  #           sequence:
  #             # Remove this room speaker from the group
  #             - service: script.remove_sonos_from_speaker_group
  #               data:
  #                 target_player: media_player.first_corridor_sonos
  #     # Pause this room speaker in case it is the last item in the group
  #     # or music follower is off
  #     - service: script.pause_sonos_if_sole_speaker_group
  #       data:
  #         target_player: media_player.first_corridor_sonos

