################################
# Timeout
#
# 1. Aqara zigbee motion sensor
#    get to on state and will go to off state with timeout for 90 seconds
#
#
################################

################################
#
################################
group:
  second_floor_motion:
    name: Second Floor Motion
    entities:
      - group.master_room_motion
      - group.master_room_stair_motion
      - group.master_toilet_motion

  first_floor_motion:
    name: First Floor Motion
    entities:
      - group.en_suite_room_motion
      - group.en_suite_toilet_motion
      - group.study_motion
      - group.guest_room_motion
      - group.guest_toilet_motion
      - binary_sensor.first_corridor_motion_sensor_motion

  ground_floor_motion:
    name: Ground Floor Motion
    entities:
      - group.living_room_motion
      - group.kitchen_motion
      - group.ground_toilet_motion
      - binary_sensor.ground_corridor_motion_sensor_motion



################################
# Motion Sensor History
################################
# Have delay of 30s-60s
sensor:
  - platform: history_stats
    name: Master Toilet Motion On Ratio For Last 2x X Minutes
    entity_id: group.master_toilet_motion
    state: "on"
    type: ratio
    duration: 00:08:00
    end: "{{ (now() | as_timestamp) | as_datetime | as_local }}"

  # Have delay of 10s
  - platform: history_stats
    name: Master Toilet Motion On Ratio For Last X Minutes
    entity_id: group.master_toilet_motion
    state: "on"
    type: ratio
    duration: 00:04:00
    end: "{{ (now() | as_timestamp) | as_datetime | as_local }}"



################################
# Room Occupancy
#
#       outside --c0---> just_entered ----c2----> stayed
#           |<----c3---------|                      |
#           |<-------------------c5-----------------|
#          |c1|             |c4|                  |c6| 
#
# State machine changing conditions:
#
# c0. outside      -> just_entered:
#     currently on 
# c1. outside      -> outside: 
#     currently off for 5 Min & previously off in [0, 2x] 
#     OR all other condition
# c2. just_entered -> stayed:
#     currently on & previously largely on in [0,x]
#     OR previously fully on in [0,x] & currently on
# c3. just_entered -> outside:
#     (currently off for 5min) & largely off in [0,2x]
# c4. just_entered -> just_entered
#     all other conditions
# c5. stayed       -> outside:
#     (currently off for 5min) & largely off in [0,2x]
# c4. stayed       -> stayed:
#     all other condition
################################

#input_select:
#  master_toilet_occupancy:
#    name: Master Toilet Occupancy
#    options:
#      - outside
#      - just_entered
#      - stayed
      
#automation:
#  - alias: Oc-MT Master Toilet Occupancy Update
#    id: "automation.oc_mt_master_toilet_occupancy_update"
#    trigger:
#      - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
#        platform: state
#    mode: single
#    action:
#      - choose:
#          # IF
#          - conditions:
#              - condition: state
#                entity_id: input_select.master_toilet_room_occupancy
#                state: "outside"
#            sequence:
#          # ELSE IF bed lamp lights on - turn off bedside lights
#          - conditions:
#              - condition: state
#                entity_id: light.master_room_lamps
#                state: "on"
#            sequence:
#              - service: script.master_room_bedside_lights_turn_off
#              - service: light.turn_on
#                entity_id: light.master_room_leds
#          # ELSE IF bed LDE on - turn off bed LED
#          - conditions:
#              - condition: state
#                entity_id: light.master_room_leds
#                state: "on"
#            sequence:
#              - service: light.turn_off
#                entity_id: light.master_room_leds
#        # ELSE - (everything was off) turn on ceiling lights
#        default:
#          - service: script.master_room_ceiling_lights_turn_on

