################################
# Timeout
#
# 1. Aqara zigbee motion sensor
#    get to on state and will go to off state with timeout for 90 seconds
#
#
################################

################################
#
################################
group:
  second_floor_motion:
    name: Second Floor Motion
    entities:
      - group.master_room_motion
      - group.master_room_stair_motion
      - group.master_toilet_motion

  first_floor_motion:
    name: First Floor Motion
    entities:
      - group.en_suite_room_motion
      - group.en_suite_toilet_motion
      - group.study_motion
      - group.guest_room_motion
      - group.guest_toilet_motion
      - binary_sensor.first_corridor_motion_sensor_motion

  ground_floor_motion:
    name: Ground Floor Motion
    entities:
      - group.living_room_motion
      - group.kitchen_motion
      - group.ground_toilet_motion
      - binary_sensor.ground_corridor_motion_sensor_motion



################################
# Motion Sensor History
################################
sensor:
  - platform: history_stats
    name: Master Toilet Motion On Ratio 10 Sec Ago
    entity_id: group.master_toilet_motion
    state: "on"
    type: ratio
    duration: 00:01:00
    end: "{{ (now() | as_timestamp) | as_datetime | as_local }}"

################################
# Room Occupancy
#
#       outside --c1---> just_entered ----c2----> stayed
#           |<----c3---------|                      |
#           |<-------------------c4-----------------|
#
# State machine changing conditions:
#
# c1. outside      -> just_entered: motion sensor triggered once
# c2. just_entered -> stayed:       longer conditions
# c3. just_entered -> outside:      motion sensor only be on for 90s
# c4. stayed       -> outside:      motion sensor off state is longer than Room_Timeout
#
################################
input_select:
  gournd_toilet_room_occupancy:
    name: Ground Toilet Room Occupancy
    options:
      - outside
      - just_entered
      - stayed

  master_toilet_room_occupancy:
    name: Master Toilet Room Occupancy
    options:
      - outside
      - just_entered
      - stayed
#automation:
#  - alias: Oc-MT Master Toilet Occupancy Update
#    id: "automation.oc_mt_master_toilet_occupancy_update"
#    trigger:
#    #  - entity_id: binary_sensor.master_toilet_basin_motion_sensor_motion
#    #    platform: state
#    #mode: single
#    action:
#      - choose:
#          # IF
#          - conditions:
#              - condition: state
#                entity_id: input_select.master_toilet_room_occupancy
#                state: "outside"
#            sequence:
#
#          # ELSE IF bed lamp lights on - turn off bedside lights
#          - conditions:
#              - condition: state
#                entity_id: light.master_room_lamps
#                state: "on"
#            sequence:
#              - service: script.master_room_bedside_lights_turn_off
#              - service: light.turn_on
#                entity_id: light.master_room_leds
#          # ELSE IF bed LDE on - turn off bed LED
#          - conditions:
#              - condition: state
#                entity_id: light.master_room_leds
#                state: "on"
#            sequence:
#              - service: light.turn_off
#                entity_id: light.master_room_leds
#        # ELSE - (everything was off) turn on ceiling lights
#        default:
#          - service: script.master_room_ceiling_lights_turn_on
#
