###########################################
#
# Custom Entities
#
###########################################

###############################################
#
# Automations
# - Lighting automation based on motion sensors
# - Lighting automation based on buttons
#
###############################################
automation:
  # Tais Desk
  # Lighting Automation based on motion sensors
  - alias: L-OD Tai's Desk light On If People Present Sits In the Chair
    id: "1676066351420"
    trigger:
      #- entity_id: sensor.tais_desk_chair_movement_sensor
      #  platform: state
      #  to: "vibration"
      #- entity_id: sensor.tais_desk_chair_movement_sensor
      #  platform: state
      #  to: "tilt"
      - entity_id: binary_sensor.tais_desk_motion_sensor_motion
        platform: state
        from: "off"
        to: "on"
    action:
      - service: light.turn_on
        entity_id: 
          - light.tais_desk_lamps
          - light.living_room_3_head_lamp_2
          - light.living_room_3_head_lamp_3
        # Only turn on screen LED in daytime
      - condition: time
        after: "06:00:00"
        before: "20:00:00"
      - service: switch.turn_on
        entity_id: switch.tais_desk_screen_led

  - alias: L-OD Tai's Desk light Off If Person Left the Chair
    id: "1636063351125"
    trigger:
      - entity_id:
          #- sensor.tais_desk_chair_movement_sensor
          - binary_sensor.tais_desk_motion_sensor_motion
        platform: state
        to: "off"
        for: 00:10:00
      - minutes: /5
        platform: time_pattern
    condition:
      - entity_id:
          #- sensor.tais_desk_chair_movement_sensor
          - binary_sensor.tais_desk_motion_sensor_motion
        condition: state
        state: "off"
        for: 00:10:00
    action:
      - service: switch.turn_off
        entity_id: switch.tais_desk_screen_led
      - service: light.turn_off
        entity_id: light.tais_desk_lamps

  # Lighting Automation based on buttons
  #  - alias: B-GR Guest Room Button Double Press - Toggle Tai's Desk Screen LED/Desk Lamps
  #    id: "1433066657725"
  #    trigger:
  #      - platform: state
  #        entity_id: sensor.guest_room_button
  #        to: double
  #    action:
  #      - service: switch.toggle
  #        entity_id: switch.tais_desk_screen_led
  #      - service: light.toggle
  #        entity_id: light.tais_desk_lamps

  - alias: L-ER Turn on En-suite Room Ceiling Light if desk light is on
    id: "1433079656045"
    trigger:
      - platform: state
        entity_id: switch.tais_desk_screen_led
        to: "on"
    #      - platform: state
    #        entity_id: switch.kes_desk_screen_led
    #        to: "on"
    action:
      - service: light.turn_on
        entity_id: light.en_suite_room_ceiling_light
