automation:
- alias: ZL-MT Ceiling Lights On Or Open Curtains If Entering to Room-Master Toilet
  id: automation.zl_mt_ceiling_lights_on_or_open_curtains_if_entering_to_room_master_toilet
  trigger:
    entity_id:
    - group.master_toilet_motion
    platform: state
    to: 'on'
  action:
  - service: automation.turn_off
    entity_id: automation.zl_mt_ceiling_lights_on_or_open_curtains_if_entering_to_room_master_toilet
    data:
      stop_actions: false
  - choose:
    - conditions:
        condition: state
        entity_id: input_boolean.always_on_constant
        state: 'on'
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.master_toilet_scene
        data:
          option: Ceiling Light White
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - service: input_select.select_option
        target:
          entity_id: input_select.master_toilet_scene
        data:
          option: All White
    - conditions:
      - condition: state
        entity_id: input_boolean.always_off_constant
        state: 'on'
      - condition: state
        entity_id: input_select.indoor_brightness
        state: bright
      - condition: not
        conditions:
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.cambridge_city_airport_temperature
            above: '20'
          - condition: time
            after: '10:00:00'
            before: '13:00:00'
          - condition: template
            value_template: '{{ now().month > 4 and now().month < 9 }}'
      sequence:
        service: cover.open_cover
        entity_id: []
    - conditions:
      - condition: time
        after: '10:00:00'
        before: '22:00:00'
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.master_toilet_scene
        data:
          option: All White
    default:
      service: input_select.select_option
      target:
        entity_id: input_select.master_toilet_scene
      data:
        option: All White
- alias: ZL-MT Lights Off If No Person-Master Toilet
  id: automation.zl_mt_lights_off_if_no_person_master_toilet
  trigger:
  - platform: state
    entity_id: input_select.master_toilet_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: input_select.master_toilet_occupancy
    state: Outside
  - condition: state
    entity_id: group.master_toilet_motion
    state: 'off'
    for: 00:01:00
  action:
  - service: homeassistant.turn_on
    entity_id: automation.zl_mt_ceiling_lights_on_or_open_curtains_if_entering_to_room_master_toilet
  - service: input_select.select_option
    target:
      entity_id: input_select.master_toilet_scene
    data:
      option: All Off
  - service: homeassistant.turn_off
    entity_id:
    - switch.master_toilet_floor_led
    - light.master_toilet_ceiling_light
  - service: homeassistant.turn_off
    entity_id:
    - media_player.master_toilet_tv
  - service: cover.close_cover
    entity_id: []
- alias: ZH-MT Heating Schedule On If Staying In the Room-Master Toilet
  id: automation.zh_mt_heating_schedule_on_if_staying_in_the_room_master_toilet
  trigger:
  - platform: state
    entity_id: input_select.master_toilet_occupancy
    from:
    - Just Entered
    - Outside
    to: Stayed Inside
  action:
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.master_toilet
        state: heat
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.master_toilet
    - service: switch.turn_on
      target:
        entity_id: switch.schedule_master_toilet_temperature
- alias: ZH-MT Heating Schedule Off If People Left the Room-Master Toilet
  id: automation.zh_mt_heating_schedule_off_if_people_left_the_room_master_toilet
  trigger:
  - platform: state
    entity_id: input_select.master_toilet_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  action:
  - condition: state
    entity_id: input_select.master_toilet_occupancy
    state: Outside
  - condition: state
    entity_id: group.master_toilet_motion
    state: 'off'
    for: 00:01:00
  - condition: state
    entity_id: input_boolean.master_toilet_heating_override
    state: 'off'
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.master_toilet
  - service: switch.turn_off
    target:
      entity_id: switch.schedule_master_toilet_temperature
- alias: ZH-MT Heaeting Manual Override-Master Toilet
  trigger:
  - platform: state
    entity_id: input_boolean.master_toilet_heating_override
  action:
  - if:
    - condition: state
      entity_id: input_boolean.master_toilet_heating_override
      state: 'on'
    then:
    - service: automation.trigger
      entity_id:
      - automation.zh_mt_heating_schedule_on_if_staying_in_the_room_master_toilet
    else:
    - service: automation.trigger
      entity_id:
      - automation.zh_mt_heating_schedule_off_if_people_left_the_room_master_toilet
  id: automation.zh_mt_heaeting_manual_override_master_toilet
- alias: ZLB-MT Applies Different Scenes Based on Scene Selections (State Execution)-Master Toilet
  trigger:
  - platform: state
    entity_id: input_select.master_toilet_scene
  mode: queued
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.master_toilet_scene
        state: All White
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id:
          - light.master_toilet_ceiling_light
          - switch.master_toilet_floor_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.master_toilet_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.master_toilet_scene
        state: Ceiling Light White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - switch.master_toilet_floor_led
        - service: homeassistant.turn_on
          entity_id:
          - light.master_toilet_ceiling_light
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.master_toilet_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.master_toilet_scene
        state: Lamp LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.master_toilet_ceiling_light
        - service: homeassistant.turn_on
          entity_id:
          - switch.master_toilet_floor_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.master_toilet_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.master_toilet_scene
        state: LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.master_toilet_ceiling_light
        - service: homeassistant.turn_on
          entity_id:
          - switch.master_toilet_floor_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.master_toilet_tv
            picture_mode: Natural
    - conditions:
      - condition: state
        entity_id: input_select.master_toilet_scene
        state: Hue
      sequence:
      - service: light.turn_on
        entity_id:
        - switch.master_toilet_floor_led
        data:
          brightness_pct: 100
      - service: pyscript.set_rgb_light_list
        data:
          light_list:
          - light.master_toilet_ceiling_light
          - switch.master_toilet_floor_led
      - service: samsungtv_smart.select_picture_mode
        data:
          entity_id:
          - media_player.master_toilet_tv
          picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.master_toilet_scene
        state: Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.master_toilet_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.master_toilet_scene
        state: Dark Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.master_toilet_dark_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.master_toilet_scene
        state: All Off
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.master_toilet_ceiling_light
          - switch.master_toilet_floor_led
  id: automation.zlb_mt_applies_different_scenes_based_on_scene_selections_state_execution_master_toilet
- alias: ZLB-MT Wall Switch-Single Press - Toggle Ceiling Light-Master Toilet
  trigger:
  - platform: state
    entity_id:
    - sensor.master_toilet_wall_button
    to:
    - '1'
    - single
    - single_left
    - single_right
    - single_center
    - button_1_single
    - button_2_single
    - button_3_single
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.master_toilet_ceiling_light
  id: automation.zlb_mt_wall_switch_single_press_toggle_ceiling_light_master_toilet
- alias: ZLB-MT Wall Switch - Double Press - Leave Room and Turn Off Everything-Master Toilet
  trigger:
  - platform: state
    entity_id:
    - sensor.master_toilet_wall_button
    to:
    - '2'
    - double
    - double_left
    - double_right
    - double_center
  action:
  - service: automation.trigger
    entity_id:
    - automation.zl_mt_lights_off_if_no_person_master_toilet
    - automation.zh_mt_heating_schedule_off_if_people_left_the_room_master_toilet
  - service: input_select.select_option
    target:
      entity_id: input_select.master_toilet_occupancy
    data:
      option: Outside
  id: automation.zlb_mt_wall_switch_double_press_leave_room_and_turn_off_everything_master_toilet
- alias: ZOc-MT Occupancy Update-Master Toilet
  trigger:
  - entity_id: group.master_toilet_motion
    platform: state
    to: 'on'
  - entity_id: group.master_toilet_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.master_toilet_occupancy
      motion_str: group.master_toilet_motion
      motion_on_ratio_for_x_min_str: sensor.master_toilet_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.master_toilet_motion_on_ratio_for_last_8_minutes
      room_type: toilet
  id: automation.zoc_mt_occupancy_update_master_toilet
input_select:
  master_toilet_scene:
    name: Master Toilet Scene
    options:
    - LED White
    - All White
    - Ceiling Light White
    - All Off
  master_toilet_occupancy:
    name: Master Toilet Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Master Toilet Motion On Ratio For Last 4 Minutes
  entity_id: group.master_toilet_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Master Toilet Motion On Ratio For Last 8 Minutes
  entity_id: group.master_toilet_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
input_boolean:
  master_toilet_heating_override:
    name: Master Toilet Heating Override
    initial: 'off'
switch: []
template: []
group:
  master_toilet_occupancy_group:
    name: Master Toilet Occuapancy Group
    entities:
    - input_select.master_toilet_occupancy
    - group.master_toilet_motion
    - binary_sensor.master_toilet_basin_motion_sensor_motion
    - binary_sensor.master_toilet_shower_motion_sensor_motion
  master_toilet_motion:
    name: Master Toilet Motion
    entities:
    - binary_sensor.master_toilet_basin_motion_sensor_motion
    - binary_sensor.master_toilet_shower_motion_sensor_motion
  master_toilet_auto_gen_automations:
    name: Master Toilet Auto-gen Automations
    entities:
    - automation.zl_mt_ceiling_lights_on_or_open_curtains_if_entering_to_room_master_toilet
    - automation.zl_mt_lights_off_if_no_person_master_toilet
    - automation.zh_mt_heating_schedule_on_if_staying_in_the_room_master_toilet
    - automation.zh_mt_heating_schedule_off_if_people_left_the_room_master_toilet
    - automation.zh_mt_heaeting_manual_override_master_toilet
    - automation.zlb_mt_applies_different_scenes_based_on_scene_selections_state_execution_master_toilet
    - automation.zlb_mt_wall_switch_single_press_toggle_ceiling_light_master_toilet
    - automation.zlb_mt_wall_switch_double_press_leave_room_and_turn_off_everything_master_toilet
    - automation.zoc_mt_occupancy_update_master_toilet
