automation:
- alias: ZL-GT Ceiling Lights On Or Open Curtains If Entering to Room-Guest Toilet
  id: automation.zl_gt_ceiling_lights_on_or_open_curtains_if_entering_to_room_guest_toilet
  trigger:
    entity_id:
    - group.guest_toilet_motion
    platform: state
    to: 'on'
  action:
  - service: automation.turn_off
    entity_id: automation.zl_gt_ceiling_lights_on_or_open_curtains_if_entering_to_room_guest_toilet
    data:
      stop_actions: false
  - if:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    then:
    - if:
      - condition: state
        entity_id: input_boolean.always_off_constant
        state: 'on'
      then:
      - if:
        - condition: numeric_state
          entity_id: sensor.met_office_cambridge_city_airport_temperature_3_hourly
          above: '20'
        - condition: time
          after: '10:00:00'
          before: '13:00:00'
        - condition: template
          value_template: '{{ now().month > 4 and now().month < 9 }}'
        then:
          service: input_select.select_option
          target:
            entity_id: input_select.guest_toilet_scene
          data:
            option: Ceiling Light White
        else:
          parallel:
          - service: cover.open_cover
            entity_id: []
          - if:
            - condition: state
              entity_id: input_boolean.guest_toilet_light_in_daytime
              state: 'on'
            then:
              service: input_select.select_option
              target:
                entity_id: input_select.guest_toilet_scene
              data:
                option: Ceiling Light White
      else:
        service: input_select.select_option
        target:
          entity_id: input_select.guest_toilet_scene
        data:
          option: Ceiling Light White
    else:
      parallel:
      - service: input_select.select_option
        target:
          entity_id: input_select.guest_toilet_scene
        data:
          option: All White
      - if:
        - condition: state
          entity_id: input_boolean.guest_toilet_curtain_in_nighttime
          state: 'on'
        then:
          service: cover.open_cover
          entity_id: []
- alias: ZL-GT Lights Off If No Person-Guest Toilet
  id: automation.zl_gt_lights_off_if_no_person_guest_toilet
  trigger:
  - platform: state
    entity_id: input_select.guest_toilet_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: input_select.guest_toilet_occupancy
    state: Outside
  - condition: state
    entity_id: group.guest_toilet_motion
    state: 'off'
    for: 00:01:00
  action:
    parallel:
    - service: homeassistant.turn_on
      entity_id: automation.zl_gt_ceiling_lights_on_or_open_curtains_if_entering_to_room_guest_toilet
    - service: cover.close_cover
      entity_id: []
    - service: homeassistant.turn_off
      entity_id:
      - media_player.guest_toilet_tv
    - service: input_select.select_option
      target:
        entity_id: input_select.guest_toilet_scene
      data:
        option: All Off
- alias: ZH-GT Heating Schedule On If Staying In the Room-Guest Toilet
  id: automation.zh_gt_heating_schedule_on_if_staying_in_the_room_guest_toilet
  trigger:
  - platform: state
    entity_id: input_select.guest_toilet_occupancy
    from:
    - Just Entered
    - Outside
    to: Stayed Inside
  action:
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.guest_toilet
        state: heat
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.guest_toilet
    - service: switch.turn_on
      target:
        entity_id: switch.schedule_guest_toilet_temperature
- alias: ZH-GT Heating Schedule Off If People Left the Room-Guest Toilet
  id: automation.zh_gt_heating_schedule_off_if_people_left_the_room_guest_toilet
  trigger:
  - platform: state
    entity_id: input_select.guest_toilet_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  action:
  - condition: state
    entity_id: input_select.guest_toilet_occupancy
    state: Outside
  - condition: state
    entity_id: input_boolean.guest_toilet_heating_override
    state: 'off'
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.guest_toilet
  - service: switch.turn_off
    target:
      entity_id: switch.schedule_guest_toilet_temperature
- alias: ZH-GT Heating Manual Override-Guest Toilet
  mode: restart
  trigger:
  - platform: state
    entity_id: input_boolean.guest_toilet_heating_override
  action:
  - if:
    - condition: state
      entity_id: input_boolean.guest_toilet_heating_override
      state: 'on'
    then:
    - service: automation.trigger
      entity_id:
      - automation.zh_gt_heating_schedule_on_if_staying_in_the_room_guest_toilet
    else:
    - service: automation.trigger
      entity_id:
      - automation.zh_gt_heating_schedule_off_if_people_left_the_room_guest_toilet
  id: automation.zh_gt_heating_manual_override_guest_toilet
- alias: ZH-GT Heating Manual Override Timeout in Few Hours-Guest Toilet
  trigger:
  - platform: state
    entity_id: input_boolean.guest_toilet_heating_override
    from: 'off'
    to: 'on'
  action:
  - delay:
      hours: 3
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: homeassistant.turn_off
    entity_id: input_boolean.guest_toilet_heating_override
  id: automation.zh_gt_heating_manual_override_timeout_in_few_hours_guest_toilet
- alias: ZH-GT Valve Calibrate Temperature Using External Sensor-Guest Toilet
  use_blueprint:
    path: calibrate_valve_temperature.yaml
    input:
      tado_valve_entity: climate.guest_toilet
      external_temperature_sensor_entity: sensor.guest_toilet_temperature_sensor
  id: automation.zh_gt_valve_calibrate_temperature_using_external_sensor_guest_toilet
- alias: ZLB-GT Applies Different Scenes Based on Scene Selections (State Execution)-Guest Toilet
  trigger:
  - platform: state
    entity_id: input_select.guest_toilet_scene
  mode: queued
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.guest_toilet_scene
        state: All White
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id:
          - light.guest_toilet_ceiling_light
          - switch.guest_toilet_floor_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.guest_toilet_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.guest_toilet_scene
        state: Ceiling Light White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - switch.guest_toilet_floor_led
        - service: homeassistant.turn_on
          entity_id:
          - light.guest_toilet_ceiling_light
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.guest_toilet_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.guest_toilet_scene
        state: Lamp LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.guest_toilet_ceiling_light
        - service: homeassistant.turn_on
          entity_id:
          - switch.guest_toilet_floor_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.guest_toilet_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.guest_toilet_scene
        state: LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.guest_toilet_ceiling_light
        - service: homeassistant.turn_on
          entity_id:
          - switch.guest_toilet_floor_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.guest_toilet_tv
            picture_mode: Natural
    - conditions:
      - condition: state
        entity_id: input_select.guest_toilet_scene
        state: Hue
      sequence:
      - service: light.turn_on
        entity_id:
        - switch.guest_toilet_floor_led
        data:
          brightness_pct: 100
      - service: pyscript.set_rgb_light_list
        data:
          light_list:
          - light.guest_toilet_ceiling_light
          - switch.guest_toilet_floor_led
      - service: samsungtv_smart.select_picture_mode
        data:
          entity_id:
          - media_player.guest_toilet_tv
          picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.guest_toilet_scene
        state: Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.guest_toilet_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.guest_toilet_scene
        state: Dark Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.guest_toilet_dark_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.guest_toilet_scene
        state: All Off
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.guest_toilet_ceiling_light
          - switch.guest_toilet_floor_led
  id: automation.zlb_gt_applies_different_scenes_based_on_scene_selections_state_execution_guest_toilet
- alias: ZLB-GT Wall Switch-Single Left Press - Toggle Ceiling Light-Guest Toilet
  trigger:
  - platform: state
    entity_id:
    - sensor.guest_toilet_wall_button
    to:
    - single_left
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.guest_toilet_ceiling_light
  id: automation.zlb_gt_wall_switch_single_left_press_toggle_ceiling_light_guest_toilet
- alias: ZLB-GT Wall Switch-Single Right Press - Toggle Floor LEDs-Guest Toilet
  trigger:
  - platform: state
    entity_id:
    - sensor.guest_toilet_wall_button
    to:
    - single_right
  action:
  - service: homeassistant.toggle
    entity_id:
    - switch.guest_toilet_floor_led
  id: automation.zlb_gt_wall_switch_single_right_press_toggle_floor_leds_guest_toilet
- alias: ZLB-GT Wall Switch - Double Press - Leave Room and Turn Off Everything-Guest Toilet
  trigger:
  - platform: state
    entity_id:
    - sensor.guest_toilet_wall_button
    to:
    - '2'
    - double
    - double_left
    - double_right
    - double_center
  action:
  - service: automation.trigger
    entity_id:
    - automation.zl_gt_lights_off_if_no_person_guest_toilet
    - automation.zh_gt_heating_schedule_off_if_people_left_the_room_guest_toilet
  - service: input_select.select_option
    target:
      entity_id: input_select.guest_toilet_occupancy
    data:
      option: Outside
  id: automation.zlb_gt_wall_switch_double_press_leave_room_and_turn_off_everything_guest_toilet
- alias: ZOc-GT Occupancy Update-Guest Toilet
  trigger:
  - entity_id: group.guest_toilet_motion
    platform: state
    to: 'on'
  - entity_id: group.guest_toilet_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.guest_toilet_occupancy
      motion_str: group.guest_toilet_motion
      motion_on_ratio_for_x_min_str: sensor.guest_toilet_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.guest_toilet_motion_on_ratio_for_last_8_minutes
      room_type: toilet
  id: automation.zoc_gt_occupancy_update_guest_toilet
input_select:
  guest_toilet_scene:
    name: Guest Toilet Scene
    options:
    - LED White
    - All White
    - Ceiling Light White
    - All Off
  guest_toilet_occupancy:
    name: Guest Toilet Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Guest Toilet Motion On Ratio For Last 4 Minutes
  entity_id: group.guest_toilet_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Guest Toilet Motion On Ratio For Last 8 Minutes
  entity_id: group.guest_toilet_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
input_boolean:
  guest_toilet_heating_override:
    name: Guest Toilet Heating Override
    initial: 'off'
  guest_toilet_light_in_daytime:
    name: Guest Toilet Light in Daytime Enable
    initial: 'off'
  guest_toilet_curtain_in_nighttime:
    name: Guest Toilet Curtain In Nighttime Enable
    initial: 'off'
switch: []
template:
- sensor:
  - name: Guest Toilet Temperature Sensor
    unit_of_measurement: "\xB0C"
    state: '{{states.sensor["a4c1387a7b78_temperature"].state | float | round(1)}}'
binary_sensor: []
light: []
group:
  guest_toilet_occupancy_group:
    name: Guest Toilet Occuapancy Group
    entities:
    - input_select.guest_toilet_occupancy
    - group.guest_toilet_motion
    - binary_sensor.guest_toilet_motion_sensor_motion
  guest_toilet_motion:
    name: Guest Toilet Motion
    entities:
    - binary_sensor.guest_toilet_motion_sensor_motion
  guest_toilet_auto_gen_automations:
    name: Guest Toilet Auto-gen Automations
    entities:
    - automation.zl_gt_ceiling_lights_on_or_open_curtains_if_entering_to_room_guest_toilet
    - automation.zl_gt_lights_off_if_no_person_guest_toilet
    - automation.zh_gt_heating_schedule_on_if_staying_in_the_room_guest_toilet
    - automation.zh_gt_heating_schedule_off_if_people_left_the_room_guest_toilet
    - automation.zh_gt_heating_manual_override_guest_toilet
    - automation.zh_gt_heating_manual_override_timeout_in_few_hours_guest_toilet
    - automation.zh_gt_valve_calibrate_temperature_using_external_sensor_guest_toilet
    - automation.zlb_gt_applies_different_scenes_based_on_scene_selections_state_execution_guest_toilet
    - automation.zlb_gt_wall_switch_single_left_press_toggle_ceiling_light_guest_toilet
    - automation.zlb_gt_wall_switch_single_right_press_toggle_floor_leds_guest_toilet
    - automation.zlb_gt_wall_switch_double_press_leave_room_and_turn_off_everything_guest_toilet
    - automation.zoc_gt_occupancy_update_guest_toilet
