automation:
- alias: ZL-GR Ceiling Lights On Or Open Curtains If Entering to Room-Guest Room
  id: automation.zl_gr_ceiling_lights_on_or_open_curtains_if_entering_to_room_guest_room
  trigger:
    entity_id:
    - binary_sensor.guest_room_entrance_motion_sensor_motion
    platform: state
    to: 'on'
  action:
  - service: automation.turn_off
    entity_id: automation.zl_gr_ceiling_lights_on_or_open_curtains_if_entering_to_room_guest_room
    data:
      stop_actions: false
  - choose:
    - conditions:
        condition: state
        entity_id: input_boolean.always_off_constant
        state: 'on'
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.guest_room_scene
        data:
          option: Ceiling Light White
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - service: input_select.select_option
        target:
          entity_id: input_select.guest_room_scene
        data:
          option: All White
    - conditions:
      - condition: state
        entity_id: input_boolean.always_off_constant
        state: 'on'
      - condition: state
        entity_id: input_select.indoor_brightness
        state: bright
      - condition: not
        conditions:
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.cambridge_city_airport_temperature
            above: '20'
          - condition: time
            after: '10:00:00'
            before: '13:00:00'
          - condition: template
            value_template: '{{ now().month > 4 and now().month < 9 }}'
      sequence:
        service: cover.open_cover
        entity_id: []
    - conditions:
      - condition: time
        after: '10:00:00'
        before: '22:00:00'
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.guest_room_scene
        data:
          option: All White
    default:
      service: input_select.select_option
      target:
        entity_id: input_select.guest_room_scene
      data:
        option: All White
- alias: ZL-GR Lights Off If No Person-Guest Room
  id: automation.zl_gr_lights_off_if_no_person_guest_room
  trigger:
  - platform: state
    entity_id: input_select.guest_room_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: input_select.guest_room_occupancy
    state: Outside
  - condition: state
    entity_id: group.guest_room_motion
    state: 'off'
    for: 00:01:00
  action:
  - service: homeassistant.turn_on
    entity_id: automation.zl_gr_ceiling_lights_on_or_open_curtains_if_entering_to_room_guest_room
  - service: input_select.select_option
    target:
      entity_id: input_select.guest_room_scene
    data:
      option: All Off
  - service: homeassistant.turn_off
    entity_id:
    - light.guest_room_bed_led
    - light.guest_room_ceiling_light
  - service: homeassistant.turn_off
    entity_id:
    - media_player.guest_room_tv
  - service: cover.close_cover
    entity_id: []
- alias: ZH-GR Heating Schedule On If Staying In the Room-Guest Room
  id: automation.zh_gr_heating_schedule_on_if_staying_in_the_room_guest_room
  trigger:
  - platform: state
    entity_id: input_select.guest_room_occupancy
    from:
    - Just Entered
    - Outside
    to: Stayed Inside
  action:
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.guest_room
        state: heat
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.guest_room
    - service: switch.turn_on
      target:
        entity_id: switch.schedule_guest_room_temperature
- alias: ZH-GR Heating Schedule Off If People Left the Room-Guest Room
  id: automation.zh_gr_heating_schedule_off_if_people_left_the_room_guest_room
  trigger:
  - platform: state
    entity_id: input_select.guest_room_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  action:
  - condition: state
    entity_id: input_select.guest_room_occupancy
    state: Outside
  - condition: state
    entity_id: group.guest_room_motion
    state: 'off'
    for: 00:01:00
  - condition: state
    entity_id: input_boolean.guest_room_heating_override
    state: 'off'
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.guest_room
  - service: switch.turn_off
    target:
      entity_id: switch.schedule_guest_room_temperature
- alias: ZH-GR Heaeting Manual Override-Guest Room
  trigger:
  - platform: state
    entity_id: input_boolean.guest_room_heating_override
  action:
  - if:
    - condition: state
      entity_id: input_boolean.guest_room_heating_override
      state: 'on'
    then:
    - service: automation.trigger
      entity_id:
      - automation.zh_gr_heating_schedule_on_if_staying_in_the_room_guest_room
    else:
    - service: automation.trigger
      entity_id:
      - automation.zh_gr_heating_schedule_off_if_people_left_the_room_guest_room
  id: automation.zh_gr_heaeting_manual_override_guest_room
- alias: ZLB-GR Applies Different Scenes Based on Scene Selections (State Execution)-Guest Room
  trigger:
  - platform: state
    entity_id: input_select.guest_room_scene
  mode: queued
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.guest_room_scene
        state: All White
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id:
          - light.guest_room_ceiling_light
          - light.guest_room_bed_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.guest_room_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.guest_room_scene
        state: Ceiling Light White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.guest_room_bed_led
        - service: homeassistant.turn_on
          entity_id:
          - light.guest_room_ceiling_light
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.guest_room_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.guest_room_scene
        state: Lamp LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.guest_room_ceiling_light
        - service: homeassistant.turn_on
          entity_id:
          - light.guest_room_bed_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.guest_room_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.guest_room_scene
        state: LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.guest_room_ceiling_light
        - service: homeassistant.turn_on
          entity_id:
          - light.guest_room_bed_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.guest_room_tv
            picture_mode: Natural
    - conditions:
      - condition: state
        entity_id: input_select.guest_room_scene
        state: Hue
      sequence:
      - service: light.turn_on
        entity_id:
        - light.guest_room_bed_led
        data:
          brightness_pct: 100
      - service: pyscript.set_rgb_light_list
        data:
          light_list:
          - light.guest_room_ceiling_light
          - light.guest_room_bed_led
      - service: samsungtv_smart.select_picture_mode
        data:
          entity_id:
          - media_player.guest_room_tv
          picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.guest_room_scene
        state: Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.guest_room_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.guest_room_scene
        state: Dark Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.guest_room_dark_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.guest_room_scene
        state: All Off
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.guest_room_ceiling_light
          - light.guest_room_bed_led
  id: automation.zlb_gr_applies_different_scenes_based_on_scene_selections_state_execution_guest_room
- alias: ZLB-GR Wall Switch-Single Press - Toggle Ceiling Light-Guest Room
  trigger:
  - platform: state
    entity_id:
    - sensor.guest_room_wall_button
    to:
    - '1'
    - single
    - single_left
    - single_right
    - single_center
    - button_1_single
    - button_2_single
    - button_3_single
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.guest_room_ceiling_light
  id: automation.zlb_gr_wall_switch_single_press_toggle_ceiling_light_guest_room
- alias: ZLB-GR Wall Switch - Double Press - Leave Room and Turn Off Everything-Guest Room
  trigger:
  - platform: state
    entity_id:
    - sensor.guest_room_wall_button
    to:
    - '2'
    - double
    - double_left
    - double_right
    - double_center
  action:
  - service: automation.trigger
    entity_id:
    - automation.zl_gr_lights_off_if_no_person_guest_room
    - automation.zh_gr_heating_schedule_off_if_people_left_the_room_guest_room
  - service: input_select.select_option
    target:
      entity_id: input_select.guest_room_occupancy
    data:
      option: Outside
  id: automation.zlb_gr_wall_switch_double_press_leave_room_and_turn_off_everything_guest_room
- alias: ZOc-GR Occupancy Update-Guest Room
  trigger:
  - entity_id: group.guest_room_motion
    platform: state
    to: 'on'
  - entity_id: group.guest_room_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.guest_room_occupancy
      motion_str: group.guest_room_motion
      motion_on_ratio_for_x_min_str: sensor.guest_room_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.guest_room_motion_on_ratio_for_last_8_minutes
      room_type: bedroom
  id: automation.zoc_gr_occupancy_update_guest_room
input_select:
  guest_room_scene:
    name: Guest Room Scene
    options:
    - LED White
    - All White
    - Ceiling Light White
    - All Off
  guest_room_occupancy:
    name: Guest Room Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Guest Room Motion On Ratio For Last 4 Minutes
  entity_id: group.guest_room_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Guest Room Motion On Ratio For Last 8 Minutes
  entity_id: group.guest_room_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
input_boolean:
  guest_room_heating_override:
    name: Guest Room Heating Override
    initial: 'off'
switch: []
template: []
group:
  guest_room_occupancy_group:
    name: Guest Room Occuapancy Group
    entities:
    - input_select.guest_room_occupancy
    - group.guest_room_motion
    - binary_sensor.guest_room_door_motion_sensor_motion
    - binary_sensor.guest_room_bed_motion_sensor_motion
  guest_room_motion:
    name: Guest Room Motion
    entities:
    - binary_sensor.guest_room_door_motion_sensor_motion
    - binary_sensor.guest_room_bed_motion_sensor_motion
  guest_room_auto_gen_automations:
    name: Guest Room Auto-gen Automations
    entities:
    - automation.zl_gr_ceiling_lights_on_or_open_curtains_if_entering_to_room_guest_room
    - automation.zl_gr_lights_off_if_no_person_guest_room
    - automation.zh_gr_heating_schedule_on_if_staying_in_the_room_guest_room
    - automation.zh_gr_heating_schedule_off_if_people_left_the_room_guest_room
    - automation.zh_gr_heaeting_manual_override_guest_room
    - automation.zlb_gr_applies_different_scenes_based_on_scene_selections_state_execution_guest_room
    - automation.zlb_gr_wall_switch_single_press_toggle_ceiling_light_guest_room
    - automation.zlb_gr_wall_switch_double_press_leave_room_and_turn_off_everything_guest_room
    - automation.zoc_gr_occupancy_update_guest_room
