input_select:
  garden_occupancy:
    name: Garden Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Garden Motion On Ratio For Last 4 Minutes
  entity_id: group.garden_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Garden Motion On Ratio For Last 8 Minutes
  entity_id: group.garden_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
automation:
- alias: ZOc-GD Occupancy Update-Garden
  trigger:
  - entity_id: group.garden_motion
    platform: state
    to: 'on'
  - entity_id: group.garden_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.garden_occupancy
      motion_str: group.garden_motion
      motion_on_ratio_for_x_min_str: sensor.garden_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.garden_motion_on_ratio_for_last_8_minutes
      room_type: common_area
  id: automation.zoc_gd_occupancy_update_garden
group:
  garden_auto_gen_automations:
    name: Garden Auto-gen Automations
    entities:
    - automation.zoc_gd_occupancy_update_garden
