automation:
- alias: ZL-0T Ceiling Lights On Or Open Curtains If Entering to Room-Ground Toilet
  id: automation.zl_0t_ceiling_lights_on_or_open_curtains_if_entering_to_room_ground_toilet
  trigger:
    entity_id:
    - group.ground_toilet_motion
    platform: state
    to: 'on'
  action:
  - service: automation.turn_off
    entity_id: automation.zl_0t_ceiling_lights_on_or_open_curtains_if_entering_to_room_ground_toilet
    data:
      stop_actions: false
  - if:
    - condition: numeric_state
      entity_id: sensor.met_office_cambridge_city_airport_temperature_3_hourly
      above: '20'
    - condition: time
      after: '10:00:00'
      before: '13:00:00'
    - condition: template
      value_template: '{{ now().month > 4 and now().month < 9 }}'
    - condition: state
      entity_id: input_boolean.always_off_constant
      state: 'on'
    then:
      service: script.call_room_scene
      data:
        room_scene_select: input_select.ground_toilet_scene
        scene: Lights on in hot sunshine
    else:
      if:
      - condition: state
        entity_id: sun.sun
        state: above_horizon
      then:
        service: script.call_room_scene
        data:
          room_scene_select: input_select.ground_toilet_scene
          scene: Lights on when bright outdoor
      else:
        service: script.call_room_scene
        data:
          room_scene_select: input_select.ground_toilet_scene
          scene: Lights on when dark outdoor
- alias: ZL-0T Lights Off If No Person-Ground Toilet
  id: automation.zl_0t_lights_off_if_no_person_ground_toilet
  trigger:
  - platform: state
    entity_id: input_select.ground_toilet_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: input_select.ground_toilet_occupancy
    state: Outside
  - condition: state
    entity_id: group.ground_toilet_motion
    state: 'off'
    for: 00:01:00
  action:
    parallel:
    - service: homeassistant.turn_on
      entity_id: automation.zl_0t_ceiling_lights_on_or_open_curtains_if_entering_to_room_ground_toilet
    - service: cover.close_cover
      entity_id: []
    - service: cover.close_cover
      entity_id: []
    - service: script.call_room_scene
      data:
        room_scene_select: input_select.ground_toilet_scene
        scene: All Off
- alias: ZH-0T Heating Schedule On If Staying In the Room-Ground Toilet
  id: automation.zh_0t_heating_schedule_on_if_staying_in_the_room_ground_toilet
  trigger:
  - platform: state
    entity_id: input_select.ground_toilet_occupancy
    from:
    - Just Entered
    - Outside
    to: Stayed Inside
  action:
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.ground_toilet
        state: heat
    then:
      if:
        condition: state
        entity_id: input_boolean.always_on_constant
        state: 'on'
      then:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        entity_id: climate.ground_toilet
      - service: homeassistant.turn_on
        entity_id: switch.schedule_ground_toilet_temperature
- alias: ZH-0T Heating Schedule Off If People Left the Room-Ground Toilet
  id: automation.zh_0t_heating_schedule_off_if_people_left_the_room_ground_toilet
  trigger:
  - platform: state
    entity_id: input_select.ground_toilet_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  action:
  - condition: state
    entity_id: input_select.ground_toilet_occupancy
    state: Outside
  - condition: state
    entity_id: input_boolean.ground_toilet_heating_override
    state: 'off'
  - if:
      condition: state
      entity_id: input_boolean.always_on_constant
      state: 'on'
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: 'off'
      entity_id: climate.ground_toilet
    - service: homeassistant.turn_off
      entity_id: switch.schedule_ground_toilet_temperature
- alias: ZH-0T Heating Manual Override-Ground Toilet
  mode: restart
  trigger:
  - platform: state
    entity_id: input_boolean.ground_toilet_heating_override
  action:
  - if:
    - condition: state
      entity_id: input_boolean.ground_toilet_heating_override
      state: 'on'
    then:
    - service: automation.trigger
      entity_id:
      - automation.zh_0t_heating_schedule_on_if_staying_in_the_room_ground_toilet
    else:
    - service: automation.trigger
      entity_id:
      - automation.zh_0t_heating_schedule_off_if_people_left_the_room_ground_toilet
  id: automation.zh_0t_heating_manual_override_ground_toilet
- alias: ZH-0T Heating Manual Override Timeout in Few Hours-Ground Toilet
  trigger:
  - platform: state
    entity_id: input_boolean.ground_toilet_heating_override
    from: 'off'
    to: 'on'
  action:
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: homeassistant.turn_off
    entity_id: input_boolean.ground_toilet_heating_override
  id: automation.zh_0t_heating_manual_override_timeout_in_few_hours_ground_toilet
- alias: ZH-0T Valve Calibrate Temperature Using External Sensor-Ground Toilet
  use_blueprint:
    path: calibrate_valve_temperature.yaml
    input:
      tado_valve_entity: climate.ground_toilet
      external_temperature_sensor_entity: sensor.ground_toilet_temperature_sensor
  id: automation.zh_0t_valve_calibrate_temperature_using_external_sensor_ground_toilet
- alias: ZL-0T Applies Different Scenes Based on Scene Selections (State Execution)-Ground Toilet
  trigger:
  - platform: state
    entity_id: input_select.ground_toilet_scene
  mode: queued
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: All White
      sequence:
      - parallel:
        - service: cover.open_cover
          entity_id: []
        - service: homeassistant.turn_on
          entity_id:
          - light.ground_toilet_ceiling_light
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id: []
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: Ceiling Light White
      sequence:
      - parallel:
        - service: cover.close_cover
          entity_id: []
        - service: homeassistant.turn_on
          entity_id:
          - light.ground_toilet_ceiling_light
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id: []
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: Lamp LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.ground_toilet_ceiling_light
        - service: cover.open_cover
          entity_id: []
        - service: cover.open_cover
          entity_id: []
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id: []
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.ground_toilet_ceiling_light
        - service: cover.open_cover
          entity_id: []
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id: []
            picture_mode: Natural
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: Hue
      sequence:
      - service: cover.open_cover
        entity_id: []
      - service: light.turn_on
        entity_id: []
        data:
          brightness_pct: 100
      - service: pyscript.set_rgb_light_list
        data:
          light_list:
          - light.ground_toilet_ceiling_light
      - service: samsungtv_smart.select_picture_mode
        data:
          entity_id: []
          picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.ground_toilet_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: Dark Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.ground_toilet_dark_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: All Off
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.ground_toilet_ceiling_light
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: Lights on in hot sunshine
      sequence:
      - parallel:
        - parallel:
          - if:
              condition: state
              entity_id: input_boolean.ceiling_light_control_in_hot_sunshine_ground_toilet
              state: 'on'
            then:
              service: homeassistant.turn_on
              entity_id:
              - light.ground_toilet_ceiling_light
          - if:
              condition: state
              entity_id: input_boolean.lamp_control_in_hot_sunshine_ground_toilet
              state: 'on'
            then:
              service: cover.open_cover
              entity_id: []
          - if:
              condition: state
              entity_id: input_boolean.led_control_in_hot_sunshine_ground_toilet
              state: 'on'
            then:
              service: cover.open_cover
              entity_id: []
          - if:
              condition: state
              entity_id: input_boolean.curtain_control_in_hot_sunshine_ground_toilet
              state: 'on'
            then:
              service: cover.open_cover
              entity_id: []
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: Lights on when bright outdoor
      sequence:
      - parallel:
        - parallel:
          - if:
              condition: state
              entity_id: input_boolean.ceiling_light_control_when_bright_outdoor_ground_toilet
              state: 'on'
            then:
              service: homeassistant.turn_on
              entity_id:
              - light.ground_toilet_ceiling_light
          - if:
              condition: state
              entity_id: input_boolean.lamp_control_when_bright_outdoor_ground_toilet
              state: 'on'
            then:
              service: cover.open_cover
              entity_id: []
          - if:
              condition: state
              entity_id: input_boolean.led_control_when_bright_outdoor_ground_toilet
              state: 'on'
            then:
              service: cover.open_cover
              entity_id: []
          - if:
              condition: state
              entity_id: input_boolean.curtain_control_when_bright_outdoor_ground_toilet
              state: 'on'
            then:
              service: cover.open_cover
              entity_id: []
    - conditions:
      - condition: state
        entity_id: input_select.ground_toilet_scene
        state: Lights on when dark outdoor
      sequence:
      - parallel:
        - parallel:
          - if:
              condition: state
              entity_id: input_boolean.ceiling_light_control_when_dark_outdoor_ground_toilet
              state: 'on'
            then:
              service: homeassistant.turn_on
              entity_id:
              - light.ground_toilet_ceiling_light
          - if:
              condition: state
              entity_id: input_boolean.lamp_control_when_dark_outdoor_ground_toilet
              state: 'on'
            then:
              service: cover.open_cover
              entity_id: []
          - if:
              condition: state
              entity_id: input_boolean.led_control_when_dark_outdoor_ground_toilet
              state: 'on'
            then:
              service: cover.open_cover
              entity_id: []
          - if:
              condition: state
              entity_id: input_boolean.curtain_control_when_dark_outdoor_ground_toilet
              state: 'on'
            then:
              service: cover.open_cover
              entity_id: []
  id: automation.zl_0t_applies_different_scenes_based_on_scene_selections_state_execution_ground_toilet
- alias: ZLB-0T Wall Switch-Single Press - Toggle Ceiling Light-Ground Toilet
  trigger:
  - platform: state
    entity_id:
    - sensor.ground_toilet_wall_button
    to:
    - '1'
    - single
    - single_left
    - single_right
    - single_center
    - button_1_single
    - button_2_single
    - button_3_single
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.ground_toilet_ceiling_light
  id: automation.zlb_0t_wall_switch_single_press_toggle_ceiling_light_ground_toilet
- alias: ZLB-0T Wall Switch - Double Press - Leave Room and Turn Off Everything-Ground Toilet
  trigger:
  - platform: state
    entity_id:
    - sensor.ground_toilet_wall_button
    to:
    - '2'
    - double
    - double_left
    - double_right
    - double_center
  action:
  - service: automation.trigger
    entity_id:
    - automation.zl_0t_lights_off_if_no_person_ground_toilet
    - automation.zh_0t_heating_schedule_off_if_people_left_the_room_ground_toilet
  - service: input_select.select_option
    target:
      entity_id: input_select.ground_toilet_occupancy
    data:
      option: Outside
  id: automation.zlb_0t_wall_switch_double_press_leave_room_and_turn_off_everything_ground_toilet
- alias: ZOc-0T Occupancy Update-Ground Toilet
  trigger:
  - entity_id: group.ground_toilet_motion
    platform: state
    to: 'on'
  - entity_id: group.ground_toilet_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.ground_toilet_occupancy
      motion_str: group.ground_toilet_motion
      motion_on_ratio_for_x_min_str: sensor.ground_toilet_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.ground_toilet_motion_on_ratio_for_last_8_minutes
      room_type: toilet
  id: automation.zoc_0t_occupancy_update_ground_toilet
input_select:
  ground_toilet_scene:
    name: Ground Toilet Scene
    options:
    - Idle
    - All White
    - Ceiling Light White
    - All Off
    - Lights on in hot sunshine
    - Lights on when bright outdoor
    - Lights on when dark outdoor
  ground_toilet_occupancy:
    name: Ground Toilet Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Ground Toilet Motion On Ratio For Last 4 Minutes
  entity_id: group.ground_toilet_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Ground Toilet Motion On Ratio For Last 8 Minutes
  entity_id: group.ground_toilet_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
input_boolean:
  ground_toilet_heating_override:
    name: Ground Toilet Heating Override
    initial: 'off'
  ceiling_light_control_in_hot_sunshine_ground_toilet:
    name: Ceiling Light Control In Hot Sunshine Ground Toilet
    initial: 'off'
  lamp_control_in_hot_sunshine_ground_toilet:
    name: Lamp Control In Hot Sunshine Ground Toilet
    initial: 'off'
  led_control_in_hot_sunshine_ground_toilet:
    name: Led Control In Hot Sunshine Ground Toilet
    initial: 'off'
  curtain_control_in_hot_sunshine_ground_toilet:
    name: Curtain Control In Hot Sunshine Ground Toilet
    initial: 'off'
  ceiling_light_control_when_bright_outdoor_ground_toilet:
    name: Ceiling Light Control When Bright Outdoor Ground Toilet
  lamp_control_when_bright_outdoor_ground_toilet:
    name: Lamp Control When Bright Outdoor Ground Toilet
    initial: 'off'
  led_control_when_bright_outdoor_ground_toilet:
    name: Led Control When Bright Outdoor Ground Toilet
    initial: 'off'
  curtain_control_when_bright_outdoor_ground_toilet:
    name: Curtain Control When Bright Outdoor Ground Toilet
    initial: 'off'
  ceiling_light_control_when_dark_outdoor_ground_toilet:
    name: Ceiling Light Control When Dark Outdoor Ground Toilet
  lamp_control_when_dark_outdoor_ground_toilet:
    name: Lamp Control When Dark Outdoor Ground Toilet
    initial: 'off'
  led_control_when_dark_outdoor_ground_toilet:
    name: Led Control When Dark Outdoor Ground Toilet
    initial: 'off'
  curtain_control_when_dark_outdoor_ground_toilet:
    name: Curtain Control When Dark Outdoor Ground Toilet
    initial: 'off'
switch: []
template:
- sensor:
  - name: Ground Toilet Temperature Sensor
    unit_of_measurement: "\xB0C"
    state: '{{states.sensor["a4c1387c09bd_temperature"].state | float | round(1)}}'
binary_sensor: []
light: []
group:
  ground_toilet_occupancy_group:
    name: Ground Toilet Occuapancy Group
    entities:
    - input_select.ground_toilet_occupancy
    - group.ground_toilet_motion
    - binary_sensor.ground_toilet_motion_sensor_motion
  ground_toilet_motion:
    name: Ground Toilet Motion
    entities:
    - binary_sensor.ground_toilet_motion_sensor_motion
  ground_toilet_lights_and_tvs:
    name: Ground Toilet Lights And Tvs
    entities:
    - light.ground_toilet_ceiling_light
  ground_toilet_auto_gen_automations:
    name: Ground Toilet Auto-gen Automations
    entities:
    - input_boolean.ceiling_light_control_when_bright_outdoor_ground_toilet
    - input_boolean.ceiling_light_control_when_dark_outdoor_ground_toilet
    - automation.zl_0t_ceiling_lights_on_or_open_curtains_if_entering_to_room_ground_toilet
    - automation.zl_0t_lights_off_if_no_person_ground_toilet
    - automation.zh_0t_heating_schedule_on_if_staying_in_the_room_ground_toilet
    - automation.zh_0t_heating_schedule_off_if_people_left_the_room_ground_toilet
    - automation.zh_0t_heating_manual_override_ground_toilet
    - automation.zh_0t_heating_manual_override_timeout_in_few_hours_ground_toilet
    - automation.zh_0t_valve_calibrate_temperature_using_external_sensor_ground_toilet
    - automation.zl_0t_applies_different_scenes_based_on_scene_selections_state_execution_ground_toilet
    - automation.zlb_0t_wall_switch_single_press_toggle_ceiling_light_ground_toilet
    - automation.zlb_0t_wall_switch_double_press_leave_room_and_turn_off_everything_ground_toilet
    - automation.zoc_0t_occupancy_update_ground_toilet
