input_select:
  living_room_scene:
    name: Living Room Scene
    options:
    - All White
    - Lamp LED White
    - LED White
    - Night Mode
    - Dark Night Mode
    - All Off
  living_room_occupancy:
    name: Living Room Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
sensor:
- platform: history_stats
  name: Living Room Motion On Ratio For Last 4 Minutes
  entity_id: group.living_room_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Living Room Motion On Ratio For Last 8 Minutes
  entity_id: group.living_room_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
group:
  living_room_auto_gen_automations:
    name: Living Room Auto-gen Automations
    entities:
    - automation.l_lr_living_room_ceiling_lights_on_or_open_curtains_if_entering_to_room
    - automation.l_lr_living_room_lights_off_if_no_person
    - automation.lb_lr_living_room_remote_button_single_applies_different_scenes_state_execution
    - automation.lb_lr_living_room_remote_button_single_applies_different_scenes_execution
    - automation.lb_lr_living_room_remote_button_double_toggle_lamps
    - automation.lb_lr_living_room_remote_button_triple_set_scene
    - automation.lb_lr_living_room_remote_button_long_toggle_leds
    - automation.lb_lr_living_room_wall_switch_single_press_toggle_ceiling_light
    - automation.lb_lr_living_room_wall_switch_double_press_leave_room_and_turn_off_everything
    - automation.oc_lr_living_room_occupancy_update
automation:
- alias: L-LR Living Room Ceiling Lights On Or Open Curtains If Entering to Room
  id: automation.l_lr_living_room_ceiling_lights_on_or_open_curtains_if_entering_to_room
  trigger:
  - entity_id:
    - group.living_room_motion
    platform: state
    to: 'on'
  action:
  - service: automation.turn_off
    entity_id: automation.l_lr_living_room_ceiling_lights_on_or_open_curtains_if_entering_to_room
    data:
      stop_actions: false
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.indoor_brightness
        state: bright
      - condition: not
        conditions:
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id:
            - sensor.cambridge_city_airport_temperature
            above: '20'
          - condition: time
            after: '10:00:00'
            before: '13:00:00'
          - condition: template
            value_template: '{{ now().month > 4 and now().month < 9 }}'
      sequence:
        service: script.do_nothing
    default:
    - choose:
      - conditions:
        - condition: time
          after: '10:00:00'
          before: '22:00:00'
        sequence:
          service: input_select.select_option
          target:
            entity_id: input_select.living_room_scene
          data:
            option: All White
      default:
        service: input_select.select_option
        target:
          entity_id: input_select.living_room_scene
        data:
          option: All White


- alias: L-LR Living Room Lights Off If No Person
  id: automation.l_lr_living_room_lights_off_if_no_person
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    for: 00:15:00
    entity_id: group.living_room_motion
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - after: '10:00:00'
        before: '22:00:00'
        condition: time
      - condition: state
        entity_id: group.living_room_motion
        for: 00:15:00
        state: 'off'
    - condition: and
      conditions:
      - after: '22:00:00'
        before: '10:00:00'
        condition: time
      - condition: state
        entity_id: group.living_room_motion
        for: 00:15:00
        state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: automation.l_lr_living_room_ceiling_lights_on_or_open_curtains_if_entering_to_room
  - service: input_select.select_option
    target:
      entity_id: input_select.living_room_scene
    data:
      option: All Off
  - service: homeassistant.turn_off
    entity_id:
    - light.living_room_tv_led
    - light.living_room_sofa_led
    - light.living_room_ceiling_light
    - light.living_room_floor_light_1
    - light.living_room_3_head_lamp_1
    - light.living_room_3_head_lamp_2
    - light.living_room_3_head_lamp_3
    - switch.living_room_floor_light_3
  - service: homeassistant.turn_off
    entity_id:
    - media_player.living_room_tv
  - service: script.do_nothing


- alias: LB-LR Living Room Remote Button - Single - Applies Different Scenes (State Execution)
  trigger:
  - platform: state
    entity_id:
    - sensor.living_room_button
    to: single
  mode: queued
  action:
  - choose:
    - conditions:
        condition: state
        entity_id: input_select.living_room_scene
        state: All Off
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.living_room_scene
        data:
          option: All White
    - conditions:
        condition: state
        entity_id: input_select.living_room_scene
        state: All White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.living_room_scene
        data:
          option: Lamp LED White
    - conditions:
        condition: state
        entity_id: input_select.living_room_scene
        state: Lamp LED White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.living_room_scene
        data:
          option: LED White
    - conditions:
        condition: state
        entity_id: input_select.living_room_scene
        state: LED White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.living_room_scene
        data:
          option: All Off
    default:
      service: input_select.select_option
      target:
        entity_id: input_select.living_room_scene
      data:
        option: Lamp LED White
  id: automation.lb_lr_living_room_remote_button_single_applies_different_scenes_state_execution


- alias: LB-LR Living Room Remote Button - Single - Applies Different Scenes (Execution)
  trigger:
  - platform: state
    entity_id: input_select.living_room_scene
  mode: queued
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.living_room_scene
        state: All White
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id:
          - light.living_room_floor_light_1
          - light.living_room_3_head_lamp_1
          - light.living_room_3_head_lamp_2
          - light.living_room_3_head_lamp_3
          - switch.living_room_floor_light_3
          - light.living_room_ceiling_light
          - light.living_room_tv_led
          - light.living_room_sofa_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.living_room_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.living_room_scene
        state: Lamp LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.living_room_ceiling_light
        - service: homeassistant.turn_on
          entity_id:
          - light.living_room_floor_light_1
          - light.living_room_3_head_lamp_1
          - light.living_room_3_head_lamp_2
          - light.living_room_3_head_lamp_3
          - switch.living_room_floor_light_3
          - light.living_room_tv_led
          - light.living_room_sofa_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.living_room_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.living_room_scene
        state: LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.living_room_ceiling_light
          - light.living_room_floor_light_1
          - light.living_room_3_head_lamp_1
          - light.living_room_3_head_lamp_2
          - light.living_room_3_head_lamp_3
          - switch.living_room_floor_light_3
        - service: homeassistant.turn_on
          entity_id:
          - light.living_room_tv_led
          - light.living_room_sofa_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.living_room_tv
            picture_mode: Natural
    - conditions:
      - condition: state
        entity_id: input_select.living_room_scene
        state: Hue
      sequence:
      - service: light.turn_on
        entity_id:
        - light.living_room_floor_light_1
        - light.living_room_3_head_lamp_1
        - light.living_room_3_head_lamp_2
        - light.living_room_3_head_lamp_3
        - switch.living_room_floor_light_3
        - light.living_room_tv_led
        - light.living_room_sofa_led
        data:
          brightness_pct: 100
      - service: pyscript.set_rgb_light_list
        data:
          light_list:
          - light.living_room_floor_light_1
          - light.living_room_3_head_lamp_1
          - light.living_room_3_head_lamp_2
          - light.living_room_3_head_lamp_3
          - switch.living_room_floor_light_3
          - light.living_room_ceiling_light
          - light.living_room_tv_led
          - light.living_room_sofa_led
      - service: samsungtv_smart.select_picture_mode
        data:
          entity_id:
          - media_player.living_room_tv
          picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.living_room_scene
        state: Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.living_room_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.living_room_scene
        state: Dark Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.living_room_dark_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.living_room_scene
        state: All Off
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.living_room_floor_light_1
          - light.living_room_3_head_lamp_1
          - light.living_room_3_head_lamp_2
          - light.living_room_3_head_lamp_3
          - switch.living_room_floor_light_3
          - light.living_room_ceiling_light
          - light.living_room_tv_led
          - light.living_room_sofa_led
  id: automation.lb_lr_living_room_remote_button_single_applies_different_scenes_execution


- alias: LB-LR Living Room Remote Button - Double - Toggle Lamps
  trigger:
  - platform: state
    entity_id:
    - sensor.living_room_button
    to: double
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.living_room_floor_light_1
    - light.living_room_3_head_lamp_1
    - light.living_room_3_head_lamp_2
    - light.living_room_3_head_lamp_3
    - switch.living_room_floor_light_3
  id: automation.lb_lr_living_room_remote_button_double_toggle_lamps


- alias: LB-LR Living Room Remote Button - Triple - Set Scene
  trigger:
  - platform: state
    entity_id:
    - sensor.living_room_button
    to: triple
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.living_room_floor_light_1
    - light.living_room_3_head_lamp_1
    - light.living_room_3_head_lamp_2
    - light.living_room_3_head_lamp_3
    - switch.living_room_floor_light_3
  id: automation.lb_lr_living_room_remote_button_triple_set_scene


- alias: LB-LR Living Room Remote Button - Long - Toggle LEDs
  trigger:
  - platform: state
    entity_id:
    - sensor.living_room_button
    to: hold
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.living_room_tv_led
    - light.living_room_sofa_led
  id: automation.lb_lr_living_room_remote_button_long_toggle_leds


- alias: LB-LR Living Room Wall Switch - Single Press - Toggle Ceiling Light
  trigger:
  - platform: state
    entity_id:
    - sensor.living_room_wall_button
    to: single
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.living_room_ceiling_light
  id: automation.lb_lr_living_room_wall_switch_single_press_toggle_ceiling_light


- alias: LB-LR Living Room Wall Switch - Double Press - Leave Room and Turn Off Everything
  trigger:
  - platform: state
    entity_id:
    - sensor.living_room_wall_button
    to: double
  action:
  - service: automation.trigger
    entity_id: automation.l_lr_living_room_lights_off_if_no_person
  id: automation.lb_lr_living_room_wall_switch_double_press_leave_room_and_turn_off_everything


- alias: Oc-LR Living Room Occupancy Update
  trigger:
  - entity_id: group.living_room_motion
    platform: state
    to: 'on'
  - entity_id: group.living_room_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: living_room_occupancy
      motion_str: group.living_room_motion
      motion_ratio_for_x_min_str: sensor.living_room_motion_on_ratio_for_last_4_minutes
      motion_ratio_for_2x_min_str: sensor.living_room_motion_on_ratio_for_last_8_minutes
  id: automation.oc_lr_living_room_occupancy_update


