automation:
- alias: ZH-CR Heating Schedule On If Staying In the Room-Corridor
  id: automation.zh_cr_heating_schedule_on_if_staying_in_the_room_corridor
  trigger:
  - platform: state
    entity_id: input_select.corridor_occupancy
    from:
    - Just Entered
    - Outside
    to: Stayed Inside
  action:
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.corridor
        state: heat
    then:
      alias: ''
      if:
        condition: state
        entity_id: input_boolean.always_on_constant
        state: 'on'
      then:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: heat
        entity_id: climate.corridor
      - service: homeassistant.turn_on
        entity_id: switch.schedule_corridor_temperature
- alias: ZH-CR Heating Schedule Off If People Left the Room-Corridor
  id: automation.zh_cr_heating_schedule_off_if_people_left_the_room_corridor
  trigger:
  - platform: state
    entity_id: input_select.corridor_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  action:
  - condition: state
    entity_id: input_select.corridor_occupancy
    state: Outside
  - condition: state
    entity_id: input_boolean.corridor_heating_override
    state: 'off'
  - alias: ''
    if:
      condition: state
      entity_id: input_boolean.always_on_constant
      state: 'on'
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: 'off'
      entity_id: climate.corridor
    - service: homeassistant.turn_off
      entity_id: switch.schedule_corridor_temperature
- alias: ZH-CR Heating Manual Override-Corridor
  mode: restart
  trigger:
  - platform: state
    entity_id: input_boolean.corridor_heating_override
  action:
  - if:
    - condition: state
      entity_id: input_boolean.corridor_heating_override
      state: 'on'
    then:
    - service: automation.trigger
      entity_id:
      - automation.zh_cr_heating_schedule_on_if_staying_in_the_room_corridor
    else:
    - service: automation.trigger
      entity_id:
      - automation.zh_cr_heating_schedule_off_if_people_left_the_room_corridor
  id: automation.zh_cr_heating_manual_override_corridor
- alias: ZH-CR Heating Manual Override Timeout in Few Hours-Corridor
  trigger:
  - platform: state
    entity_id: input_boolean.corridor_heating_override
    from: 'off'
    to: 'on'
  action:
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: homeassistant.turn_off
    entity_id: input_boolean.corridor_heating_override
  id: automation.zh_cr_heating_manual_override_timeout_in_few_hours_corridor
- alias: ZLB-CR Wall Switch-Single Press - Toggle Ceiling Light-Corridor
  trigger:
  - platform: state
    entity_id:
    - sensor.ground_corridor_wall_button
    - sensor.first_corridor_wall_button
    to:
    - '1'
    - single
    - single_left
    - single_right
    - single_center
    - button_1_single
    - button_2_single
    - button_3_single
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.corridor_ceiling_light
  id: automation.zlb_cr_wall_switch_single_press_toggle_ceiling_light_corridor
- alias: ZLB-CR Wall Switch - Double Press - Leave Room and Turn Off Everything-Corridor
  trigger:
  - platform: state
    entity_id:
    - sensor.ground_corridor_wall_button
    - sensor.first_corridor_wall_button
    to:
    - '2'
    - double
    - double_left
    - double_right
    - double_center
  action:
  - service: automation.trigger
    entity_id:
    - automation.zl_cr_lights_off_if_no_person_corridor
    - automation.zh_cr_heating_schedule_off_if_people_left_the_room_corridor
  - service: input_select.select_option
    target:
      entity_id: input_select.corridor_occupancy
    data:
      option: Outside
  id: automation.zlb_cr_wall_switch_double_press_leave_room_and_turn_off_everything_corridor
- alias: ZOc-CR Occupancy Update-Corridor
  trigger:
  - entity_id: group.corridor_motion
    platform: state
    to: 'on'
  - entity_id: group.corridor_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.corridor_occupancy
      motion_str: group.corridor_motion
      motion_on_ratio_for_x_min_str: sensor.corridor_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.corridor_motion_on_ratio_for_last_8_minutes
      room_type: landing
  id: automation.zoc_cr_occupancy_update_corridor
input_select:
  corridor_occupancy:
    name: Corridor Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Corridor Motion On Ratio For Last 4 Minutes
  entity_id: group.corridor_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Corridor Motion On Ratio For Last 8 Minutes
  entity_id: group.corridor_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
input_boolean:
  corridor_heating_override:
    name: Corridor Heating Override
    initial: 'off'
  ceiling_light_control_in_hot_sunshine_corridor:
    name: Ceiling Light Control In Hot Sunshine Corridor
    initial: 'off'
  lamp_control_in_hot_sunshine_corridor:
    name: Lamp Control In Hot Sunshine Corridor
    initial: 'off'
  led_control_in_hot_sunshine_corridor:
    name: Led Control In Hot Sunshine Corridor
    initial: 'off'
  curtain_control_in_hot_sunshine_corridor:
    name: Curtain Control In Hot Sunshine Corridor
    initial: 'off'
  ceiling_light_control_when_bright_outdoor_corridor:
    name: Ceiling Light Control When Bright Outdoor Corridor
  lamp_control_when_bright_outdoor_corridor:
    name: Lamp Control When Bright Outdoor Corridor
    initial: 'off'
  led_control_when_bright_outdoor_corridor:
    name: Led Control When Bright Outdoor Corridor
    initial: 'off'
  curtain_control_when_bright_outdoor_corridor:
    name: Curtain Control When Bright Outdoor Corridor
    initial: 'off'
  ceiling_light_control_when_dark_outdoor_corridor:
    name: Ceiling Light Control When Dark Outdoor Corridor
  lamp_control_when_dark_outdoor_corridor:
    name: Lamp Control When Dark Outdoor Corridor
    initial: 'off'
  led_control_when_dark_outdoor_corridor:
    name: Led Control When Dark Outdoor Corridor
    initial: 'off'
  curtain_control_when_dark_outdoor_corridor:
    name: Curtain Control When Dark Outdoor Corridor
    initial: 'off'
switch: []
cover: []
template:
- sensor:
  - name: Ground Corridor Motion Sensor Light
    unit_of_measurement: lx
    state: '{{states.sensor["0x00158d00045019fd_illuminance_lux"].state}}'
- sensor:
  - name: Ground Corridor Motion Sensor Battery
    unit_of_measurement: '%'
    state: '{{states.sensor["0x00158d00045019fd_battery"].state}}'
binary_sensor:
- platform: group
  name: Ground Corridor Motion Sensor Motion
  entities: binary_sensor.0x00158d00045019fd_occupancy
light:
- platform: group
  name: First Corridor BLE Light
  entities: light.50ec50ded70f_light
- platform: group
  name: Ground Corridor BLE Light
  entities: light.50ec50df9323_light
group:
  corridor_occupancy_group:
    name: Corridor Occuapancy Group
    entities:
    - input_select.corridor_occupancy
    - group.corridor_motion
    - binary_sensor.ground_corridor_motion_sensor_motion
    - binary_sensor.first_corridor_motion_sensor_motion
  corridor_motion:
    name: Corridor Motion
    entities:
    - binary_sensor.ground_corridor_motion_sensor_motion
    - binary_sensor.first_corridor_motion_sensor_motion
  corridor_lights_and_tvs:
    name: Corridor Lights And Tvs
    entities:
    - light.corridor_ceiling_light
  corridor_auto_gen_automations:
    name: Corridor Auto-gen Automations
    entities:
    - input_boolean.ceiling_light_control_when_bright_outdoor_corridor
    - input_boolean.ceiling_light_control_when_dark_outdoor_corridor
    - automation.zh_cr_heating_schedule_on_if_staying_in_the_room_corridor
    - automation.zh_cr_heating_schedule_off_if_people_left_the_room_corridor
    - automation.zh_cr_heating_manual_override_corridor
    - automation.zh_cr_heating_manual_override_timeout_in_few_hours_corridor
    - automation.zlb_cr_wall_switch_single_press_toggle_ceiling_light_corridor
    - automation.zlb_cr_wall_switch_double_press_leave_room_and_turn_off_everything_corridor
    - automation.zoc_cr_occupancy_update_corridor
