input_select:
  study_occupancy:
    name: Study Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Study Motion On Ratio For Last 4 Minutes
  entity_id: group.study_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Study Motion On Ratio For Last 8 Minutes
  entity_id: group.study_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
automation:
- alias: ZOc-ST Occupancy Update-Study
  trigger:
  - entity_id: group.study_motion
    platform: state
    to: 'on'
  - entity_id: group.study_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.study_occupancy
      motion_str: group.study_motion
      motion_on_ratio_for_x_min_str: sensor.study_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.study_motion_on_ratio_for_last_8_minutes
      room_type: common_area
  id: automation.zoc_st_occupancy_update_study
- alias: ZH-ST Heating Schedule On If Staying In the Room-Study
  trigger:
  - platform: state
    entity_id: input_select.study_occupancy
    from:
    - Just Entered
    - Outside
    to: Stayed Inside
  action:
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.study
        state: heat
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.study
    - service: switch.turn_on
      target:
        entity_id: switch.schedule_study_temperature
  id: automation.zh_st_heating_schedule_on_if_staying_in_the_room_study
- alias: ZH-ST Heating Schedule Off If People Left the Room-Study
  trigger:
  - platform: state
    entity_id: input_select.study_occupancy
    to: Outside
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.study
  - service: switch.turn_off
    target:
      entity_id: switch.schedule_study_temperature
  id: automation.zh_st_heating_schedule_off_if_people_left_the_room_study
group:
  study_auto_gen_automations:
    name: Study Auto-gen Automations
    entities:
    - automation.zoc_st_occupancy_update_study
    - automation.zh_st_heating_schedule_on_if_staying_in_the_room_study
    - automation.zh_st_heating_schedule_off_if_people_left_the_room_study
