automation:
- alias: ZOc-GD Occupancy Update-Garden
  trigger:
  - entity_id: group.garden_motion
    platform: state
    to: 'on'
  - entity_id: group.garden_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.garden_occupancy
      motion_str: group.garden_motion
      motion_on_ratio_for_x_min_str: sensor.garden_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.garden_motion_on_ratio_for_last_8_minutes
      room_type: common_area
  id: automation.zoc_gd_occupancy_update_garden
input_select:
  garden_occupancy:
    name: Garden Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Garden Motion On Ratio For Last 4 Minutes
  entity_id: group.garden_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Garden Motion On Ratio For Last 8 Minutes
  entity_id: group.garden_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
input_boolean:
  ceiling_light_control_in_hot_sunshine_garden:
    name: Ceiling Light Control In Hot Sunshine Garden
    initial: 'off'
  lamp_control_in_hot_sunshine_garden:
    name: Lamp Control In Hot Sunshine Garden
    initial: 'off'
  led_control_in_hot_sunshine_garden:
    name: Led Control In Hot Sunshine Garden
    initial: 'off'
  curtain_control_in_hot_sunshine_garden:
    name: Curtain Control In Hot Sunshine Garden
    initial: 'off'
  ceiling_light_control_when_bright_outdoor_garden:
    name: Ceiling Light Control When Bright Outdoor Garden
  lamp_control_when_bright_outdoor_garden:
    name: Lamp Control When Bright Outdoor Garden
    initial: 'off'
  led_control_when_bright_outdoor_garden:
    name: Led Control When Bright Outdoor Garden
    initial: 'off'
  curtain_control_when_bright_outdoor_garden:
    name: Curtain Control When Bright Outdoor Garden
    initial: 'off'
  ceiling_light_control_when_dark_outdoor_garden:
    name: Ceiling Light Control When Dark Outdoor Garden
  lamp_control_when_dark_outdoor_garden:
    name: Lamp Control When Dark Outdoor Garden
    initial: 'off'
  led_control_when_dark_outdoor_garden:
    name: Led Control When Dark Outdoor Garden
    initial: 'off'
  curtain_control_when_dark_outdoor_garden:
    name: Curtain Control When Dark Outdoor Garden
    initial: 'off'
switch: []
template:
- sensor:
  - name: Study Temperature Sensor
    unit_of_measurement: "\xB0C"
    state: '{{states.sensor["a4c138e25da9_temperature"].state | float | round(1)}}'
binary_sensor: []
light: []
group:
  garden_occupancy_group:
    name: Garden Occuapancy Group
    entities:
    - input_select.garden_occupancy
    - group.garden_motion
    - binary_sensor.garden_sliding_door_motion_sensor_motion
    - binary_sensor.garden_bike_shed_motion_sensor_motion
  garden_motion:
    name: Garden Motion
    entities:
    - binary_sensor.garden_sliding_door_motion_sensor_motion
    - binary_sensor.garden_bike_shed_motion_sensor_motion
  garden_lights_and_tvs:
    name: Garden Lights And Tvs
    entities:
    - light.garden_ceiling_light
    - media_player.garden_tv
  garden_auto_gen_automations:
    name: Garden Auto-gen Automations
    entities:
    - input_boolean.ceiling_light_control_when_bright_outdoor_garden
    - input_boolean.ceiling_light_control_when_dark_outdoor_garden
    - automation.zoc_gd_occupancy_update_garden
