input_select:
  whole_home_occupancy:
    name: Whole Home Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Whole Home Motion On Ratio For Last 4 Minutes
  entity_id: group.whole_home_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Whole Home Motion On Ratio For Last 8 Minutes
  entity_id: group.whole_home_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
automation:
- alias: ZOc-WH Occupancy Update-Whole Home
  trigger:
  - entity_id: group.whole_home_motion
    platform: state
    to: 'on'
  - entity_id: group.whole_home_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.whole_home_occupancy
      motion_str: group.whole_home_motion
      motion_on_ratio_for_x_min_str: sensor.whole_home_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.whole_home_motion_on_ratio_for_last_8_minutes
      room_type: common_area
  id: automation.zoc_wh_occupancy_update_whole_home
