automation:
- alias: L-ER En-suite Room Ceiling Lights On Or Open Curtains If Entering to Room
  id: automation.l_er_en_suite_room_ceiling_lights_on_or_open_curtains_if_entering_to_room
  trigger:
  - entity_id:
    - binary_sensor.en_suite_room_entrance_motion_sensor_motion
    platform: state
    to: 'on'
  action:
  - service: automation.turn_off
    entity_id: automation.l_er_en_suite_room_ceiling_lights_on_or_open_curtains_if_entering_to_room
    data:
      stop_actions: false
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.indoor_brightness
        state: bright
      - condition: not
        conditions:
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id:
            - sensor.cambridge_city_airport_temperature
            above: '20'
          - condition: time
            after: '13:00:00'
            before: '22:00:00'
          - condition: template
            value_template: '{{ now().month > 4 and now().month < 9 }}'
      sequence:
        service: script.do_nothing
    default:
    - choose:
      - conditions:
        - condition: time
          after: '10:00:00'
          before: '22:00:00'
        sequence:
          service: input_select.select_option
          target:
            entity_id: input_select.en_suite_room_scene
          data:
            option: All White
      default:
        service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: Lamp LED White


- alias: L-ER En-suite Room Lights Off If No Person
  id: automation.l_er_en_suite_room_lights_off_if_no_person
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    for: 00:15:00
    entity_id:
    - group.en_suite_room_motion
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - after: '10:00:00'
        before: '22:00:00'
        condition: time
      - condition: state
        entity_id:
        - group.en_suite_room_motion
        for: 00:15:00
        state: 'off'
    - condition: and
      conditions:
      - after: '22:00:00'
        before: '10:00:00'
        condition: time
      - condition: state
        entity_id:
        - group.en_suite_room_motion
        for: 02:00:00
        state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: automation.l_er_en_suite_room_ceiling_lights_on_or_open_curtains_if_entering_to_room
  - service: homeassistant.turn_off
    entity_id:
    - light.en_suite_room_bed_led
    - light.en_suite_room_lamp_1
    - light.en_suite_room_lamp_2
    - light.en_suite_room_ceiling_light
  - service: homeassistant.turn_off
    entity_id:
    - media_player.portable_tv
  - service: script.do_nothing


- alias: LB-ER En-suite Room Remote Button - Single - Applies Different Scenes (State Execution)
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_button
    to: single
  mode: queued
  action:
  - choose:
    - conditions:
        condition: state
        entity_id: input_select.en_suite_room_scene
        state: All Off
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: All White
    - conditions:
        condition: state
        entity_id: input_select.en_suite_room_scene
        state: All White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: Lamp LED White
    - conditions:
        condition: state
        entity_id: input_select.en_suite_room_scene
        state: Lamp LED White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: LED White
    - conditions:
        condition: state
        entity_id: input_select.en_suite_room_scene
        state: LED White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: All Off
    default:
      service: input_select.select_option
      target:
        entity_id: input_select.en_suite_room_scene
      data:
        option: Lamp LED White
  id: automation.lb_er_en_suite_room_remote_button_single_applies_different_scenes_(state_execution)


- alias: LB-ER En-suite Room Remote Button - Single - Applies Different Scenes (Execution)
  trigger:
  - platform: state
    entity_id: input_select.en_suite_room_scene
  mode: queued
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: All White
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id:
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
          - light.en_suite_room_ceiling_light
          - light.en_suite_room_bed_led
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: Lamp LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.en_suite_room_ceiling_light
        - service: homeassistant.turn_on
          entity_id:
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
          - light.en_suite_room_bed_led
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.en_suite_room_ceiling_light
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
        - service: homeassistant.turn_on
          entity_id:
          - light.en_suite_room_bed_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.portable_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: Hue
      sequence:
      - service: light.turn_on
        entity_id:
        - light.en_suite_room_lamp_1
        - light.en_suite_room_lamp_2
        - light.en_suite_room_bed_led
        data:
          brightness_pct: 100
      - service: pyscript.set_rgb_light_list
        data:
          light_list:
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
          - light.en_suite_room_ceiling_light
          - light.en_suite_room_bed_led
      - service: samsungtv_smart.select_picture_mode
        data:
          entity_id:
          - media_player.portable_tv
          picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.en_suite_room_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: Dark Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.en_suite_room_dark_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: All Off
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
          - light.en_suite_room_ceiling_light
          - light.en_suite_room_bed_led
  id: automation.lb_er_en_suite_room_remote_button_single_applies_different_scenes_(execution)


- alias: LB-ER En-suite Room Remote Button - Double - Toggle Lamps
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_button
    to: double
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.en_suite_room_lamp_1
    - light.en_suite_room_lamp_2
  id: automation.lb_er_en_suite_room_remote_button_double_toggle_lamps


- alias: LB-ER En-suite Room Remote Button - Triple - Set Scene
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_button
    to: triple
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.en_suite_room_lamp_1
    - light.en_suite_room_lamp_2
  id: automation.lb_er_en_suite_room_remote_button_triple_set_scene


- alias: LB-ER En-suite Room Remote Button - Long - Toggle LEDs
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_button
    to: hold
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.en_suite_room_bed_led
  id: automation.lb_er_en_suite_room_remote_button_long_toggle_leds


- alias: LB-ER En-suite Room Wall Switch - Single Press - Toggle Ceiling Light
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_ceiling_light_wall_button
    to: single
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.en_suite_room_ceiling_light
  id: automation.lb_er_en_suite_room_wall_switch_single_press_toggle_ceiling_light


- alias: LB-ER En-suite Room Wall Switch - Double Press - Leave Room and Turn Off Everything
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_ceiling_light_wall_button
    to: double
  action:
  - service: automation.trigger
    entity_id: automation.l_er_en_suite_room_lights_off_if_no_person
  id: automation.lb_er_en_suite_room_wall_switch_double_press_leave_room_and_turn_off_everything


input_select:
  en_suite_room_scene:
    name: En-suite Room Scene
    options:
    - Hue
    - Night Mode
    - Dark Night Mode
    - All White
    - Lamp LED White
    - LED White
    - All Off
