automation:
- alias: ZH-CR Heating Schedule On If Staying In the Room-Corridor
  id: automation.zh_cr_heating_schedule_on_if_staying_in_the_room_corridor
  trigger:
  - platform: state
    entity_id: input_select.corridor_occupancy
    from:
    - Just Entered
    - Outside
    to: Stayed Inside
  action:
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.corridor
        state: heat
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.corridor
    - service: switch.turn_on
      target:
        entity_id: switch.schedule_corridor_temperature
- alias: ZH-CR Heating Schedule Off If People Left the Room-Corridor
  id: automation.zh_cr_heating_schedule_off_if_people_left_the_room_corridor
  trigger:
  - platform: state
    entity_id: input_select.corridor_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  action:
  - condition: state
    entity_id: input_select.corridor_occupancy
    state: Outside
  - condition: state
    entity_id: group.corridor_motion
    state: 'off'
    for: 00:01:00
  - condition: state
    entity_id: input_boolean.corridor_heating_override
    state: 'off'
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.corridor
  - service: switch.turn_off
    target:
      entity_id: switch.schedule_corridor_temperature
- alias: ZH-CR Heaeting Manual Override-Corridor
  trigger:
  - platform: state
    entity_id: input_boolean.corridor_heating_override
  action:
  - if:
    - condition: state
      entity_id: input_boolean.corridor_heating_override
      state: 'on'
    then:
    - service: automation.trigger
      entity_id:
      - automation.zh_cr_heating_schedule_on_if_staying_in_the_room_corridor
    else:
    - service: automation.trigger
      entity_id:
      - automation.zh_cr_heating_schedule_off_if_people_left_the_room_corridor
  id: automation.zh_cr_heaeting_manual_override_corridor
- alias: ZOc-CR Occupancy Update-Corridor
  trigger:
  - entity_id: group.corridor_motion
    platform: state
    to: 'on'
  - entity_id: group.corridor_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.corridor_occupancy
      motion_str: group.corridor_motion
      motion_on_ratio_for_x_min_str: sensor.corridor_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.corridor_motion_on_ratio_for_last_8_minutes
      room_type: common_area
  id: automation.zoc_cr_occupancy_update_corridor
input_select:
  corridor_occupancy:
    name: Corridor Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Corridor Motion On Ratio For Last 4 Minutes
  entity_id: group.corridor_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Corridor Motion On Ratio For Last 8 Minutes
  entity_id: group.corridor_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
input_boolean:
  corridor_heating_override:
    name: Corridor Heating Override
    initial: 'off'
switch: []
template: []
group:
  corridor_occupancy_group:
    name: Corridor Occuapancy Group
    entities:
    - input_select.corridor_occupancy
    - group.corridor_motion
    - binary_sensor.ground_corridor_motion_sensor_motion
    - binary_sensor.first_corridor_motion_sensor_motion
  corridor_motion:
    name: Corridor Motion
    entities:
    - binary_sensor.ground_corridor_motion_sensor_motion
    - binary_sensor.first_corridor_motion_sensor_motion
  corridor_auto_gen_automations:
    name: Corridor Auto-gen Automations
    entities:
    - automation.zh_cr_heating_schedule_on_if_staying_in_the_room_corridor
    - automation.zh_cr_heating_schedule_off_if_people_left_the_room_corridor
    - automation.zh_cr_heaeting_manual_override_corridor
    - automation.zoc_cr_occupancy_update_corridor
