automation:
- alias: ZL-ST Ceiling Lights On Or Open Curtains If Entering to Room-Study
  id: automation.zl_st_ceiling_lights_on_or_open_curtains_if_entering_to_room_study
  trigger:
    entity_id:
    - group.study_motion
    platform: state
    to: 'on'
  action:
  - service: automation.turn_off
    entity_id: automation.zl_st_ceiling_lights_on_or_open_curtains_if_entering_to_room_study
    data:
      stop_actions: false
  - choose:
    - conditions:
        condition: state
        entity_id: input_boolean.always_on_constant
        state: 'on'
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.study_scene
        data:
          option: Ceiling Light White
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - service: input_select.select_option
        target:
          entity_id: input_select.study_scene
        data:
          option: All White
    - conditions:
      - condition: state
        entity_id: input_boolean.always_off_constant
        state: 'on'
      - condition: state
        entity_id: input_select.indoor_brightness
        state: bright
      - condition: not
        conditions:
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.cambridge_city_airport_temperature
            above: '20'
          - condition: time
            after: '10:00:00'
            before: '13:00:00'
          - condition: template
            value_template: '{{ now().month > 4 and now().month < 9 }}'
      sequence:
        service: cover.open_cover
        entity_id: []
    - conditions:
      - condition: time
        after: '10:00:00'
        before: '22:00:00'
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.study_scene
        data:
          option: All White
    default:
      service: input_select.select_option
      target:
        entity_id: input_select.study_scene
      data:
        option: All White
- alias: ZL-ST Lights Off If No Person-Study
  id: automation.zl_st_lights_off_if_no_person_study
  trigger:
  - platform: state
    entity_id: input_select.study_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: input_select.study_occupancy
    state: Outside
  - condition: state
    entity_id: group.study_motion
    state: 'off'
    for: 00:01:00
  action:
  - service: homeassistant.turn_on
    entity_id: automation.zl_st_ceiling_lights_on_or_open_curtains_if_entering_to_room_study
  - service: input_select.select_option
    target:
      entity_id: input_select.study_scene
    data:
      option: All Off
  - service: homeassistant.turn_off
    entity_id:
    - light.study_ceiling_light
  - service: homeassistant.turn_off
    entity_id:
    - media_player.study_tv
  - service: cover.close_cover
    entity_id: []
- alias: ZH-ST Heating Schedule On If Staying In the Room-Study
  id: automation.zh_st_heating_schedule_on_if_staying_in_the_room_study
  trigger:
  - platform: state
    entity_id: input_select.study_occupancy
    from:
    - Just Entered
    - Outside
    to: Stayed Inside
  action:
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.study
        state: heat
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.study
    - service: switch.turn_on
      target:
        entity_id: switch.schedule_study_temperature
- alias: ZH-ST Heating Schedule Off If People Left the Room-Study
  id: automation.zh_st_heating_schedule_off_if_people_left_the_room_study
  trigger:
  - platform: state
    entity_id: input_select.study_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  action:
  - condition: state
    entity_id: input_select.study_occupancy
    state: Outside
  - condition: state
    entity_id: group.study_motion
    state: 'off'
    for: 00:01:00
  - condition: state
    entity_id: input_boolean.study_heating_override
    state: 'off'
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.study
  - service: switch.turn_off
    target:
      entity_id: switch.schedule_study_temperature
- alias: ZH-ST Heaeting Manual Override-Study
  trigger:
  - platform: state
    entity_id: input_boolean.study_heating_override
  action:
  - if:
    - condition: state
      entity_id: input_boolean.study_heating_override
      state: 'on'
    then:
    - service: automation.trigger
      entity_id:
      - automation.zh_st_heating_schedule_on_if_staying_in_the_room_study
    else:
    - service: automation.trigger
      entity_id:
      - automation.zh_st_heating_schedule_off_if_people_left_the_room_study
  id: automation.zh_st_heaeting_manual_override_study
- alias: ZLB-ST Applies Different Scenes Based on Scene Selections (State Execution)-Study
  trigger:
  - platform: state
    entity_id: input_select.study_scene
  mode: queued
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.study_scene
        state: All White
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id:
          - light.study_ceiling_light
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.study_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.study_scene
        state: Ceiling Light White
      sequence:
      - parallel:
        - service: cover.close_cover
          entity_id: []
        - service: homeassistant.turn_on
          entity_id:
          - light.study_ceiling_light
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.study_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.study_scene
        state: Lamp LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.study_ceiling_light
        - service: cover.open_cover
          entity_id: []
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.study_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.study_scene
        state: LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.study_ceiling_light
        - service: cover.open_cover
          entity_id: []
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.study_tv
            picture_mode: Natural
    - conditions:
      - condition: state
        entity_id: input_select.study_scene
        state: Hue
      sequence:
      - service: light.turn_on
        entity_id: []
        data:
          brightness_pct: 100
      - service: pyscript.set_rgb_light_list
        data:
          light_list:
          - light.study_ceiling_light
      - service: samsungtv_smart.select_picture_mode
        data:
          entity_id:
          - media_player.study_tv
          picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.study_scene
        state: Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.study_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.study_scene
        state: Dark Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.study_dark_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.study_scene
        state: All Off
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.study_ceiling_light
  id: automation.zlb_st_applies_different_scenes_based_on_scene_selections_state_execution_study
- alias: ZLB-ST Wall Switch-Single Press - Toggle Ceiling Light-Study
  trigger:
  - platform: state
    entity_id:
    - sensor.study_wall_button
    to:
    - '1'
    - single
    - single_left
    - single_right
    - single_center
    - button_1_single
    - button_2_single
    - button_3_single
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.study_ceiling_light
  id: automation.zlb_st_wall_switch_single_press_toggle_ceiling_light_study
- alias: ZLB-ST Wall Switch - Double Press - Leave Room and Turn Off Everything-Study
  trigger:
  - platform: state
    entity_id:
    - sensor.study_wall_button
    to:
    - '2'
    - double
    - double_left
    - double_right
    - double_center
  action:
  - service: automation.trigger
    entity_id:
    - automation.zl_st_lights_off_if_no_person_study
    - automation.zh_st_heating_schedule_off_if_people_left_the_room_study
  - service: input_select.select_option
    target:
      entity_id: input_select.study_occupancy
    data:
      option: Outside
  id: automation.zlb_st_wall_switch_double_press_leave_room_and_turn_off_everything_study
- alias: ZOc-ST Occupancy Update-Study
  trigger:
  - entity_id: group.study_motion
    platform: state
    to: 'on'
  - entity_id: group.study_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.study_occupancy
      motion_str: group.study_motion
      motion_on_ratio_for_x_min_str: sensor.study_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.study_motion_on_ratio_for_last_8_minutes
      room_type: common_area
  id: automation.zoc_st_occupancy_update_study
input_select:
  study_scene:
    name: Study Scene
    options:
    - All White
    - Ceiling Light White
    - All Off
  study_occupancy:
    name: Study Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Study Motion On Ratio For Last 4 Minutes
  entity_id: group.study_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Study Motion On Ratio For Last 8 Minutes
  entity_id: group.study_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
input_boolean:
  study_heating_override:
    name: Study Heating Override
    initial: 'off'
switch: []
template: []
group:
  study_occupancy_group:
    name: Study Occuapancy Group
    entities:
    - input_select.study_occupancy
    - group.study_motion
    - binary_sensor.study_motion_sensor_motion
    - binary_sensor.kes_desk_motion_sensor_motion
  study_motion:
    name: Study Motion
    entities:
    - binary_sensor.study_motion_sensor_motion
    - binary_sensor.kes_desk_motion_sensor_motion
  study_auto_gen_automations:
    name: Study Auto-gen Automations
    entities:
    - automation.zl_st_ceiling_lights_on_or_open_curtains_if_entering_to_room_study
    - automation.zl_st_lights_off_if_no_person_study
    - automation.zh_st_heating_schedule_on_if_staying_in_the_room_study
    - automation.zh_st_heating_schedule_off_if_people_left_the_room_study
    - automation.zh_st_heaeting_manual_override_study
    - automation.zlb_st_applies_different_scenes_based_on_scene_selections_state_execution_study
    - automation.zlb_st_wall_switch_single_press_toggle_ceiling_light_study
    - automation.zlb_st_wall_switch_double_press_leave_room_and_turn_off_everything_study
    - automation.zoc_st_occupancy_update_study
