input_select:
  master_room_scene:
    name: Master Room Scene
    options:
    - Hue
    - All White
    - Lamp LED White
    - LED White
    - Night Mode
    - Dark Night Mode
    - All Off
  master_room_occupancy:
    name: Master Room Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Master Room Motion On Ratio For Last 4 Minutes
  entity_id: group.master_room_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Master Room Motion On Ratio For Last 8 Minutes
  entity_id: group.master_room_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
automation:
- alias: ZL-MR Ceiling Lights On Or Open Curtains If Entering to Room-Master Room
  id: automation.zl_mr_ceiling_lights_on_or_open_curtains_if_entering_to_room_master_room
  trigger:
  - entity_id:
    - binary_sensor.master_room_entrance_motion_sensor_motion
    platform: state
    to: 'on'
  action:
  - service: automation.turn_off
    entity_id: automation.zl_mr_ceiling_lights_on_or_open_curtains_if_entering_to_room_master_room
    data:
      stop_actions: false
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.indoor_brightness
        state: bright
      - condition: not
        conditions:
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.cambridge_city_airport_temperature
            above: '20'
          - condition: time
            after: '13:00:00'
            before: '22:00:00'
          - condition: template
            value_template: '{{ now().month > 4 and now().month < 9 }}'
      sequence:
        service: cover.open_cover
        entity_id:
        - cover.master_room_blind
        - cover.master_room_curtain
    default:
    - choose:
      - conditions:
        - condition: time
          after: '10:00:00'
          before: '22:00:00'
        sequence:
          service: input_select.select_option
          target:
            entity_id: input_select.master_room_scene
          data:
            option: All White
      default:
        service: input_select.select_option
        target:
          entity_id: input_select.master_room_scene
        data:
          option: Lamp LED White
- alias: ZL-MR Lights Off If No Person-Master Room
  id: automation.zl_mr_lights_off_if_no_person_master_room
  trigger:
  - platform: state
    from: 'on'
    to: 'off'
    for: 00:15:00
    entity_id: group.master_room_motion
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: or
    conditions:
    - condition: and
      conditions:
      - after: '10:00:00'
        before: '22:00:00'
        condition: time
      - condition: state
        entity_id: group.master_room_motion
        for: 00:15:00
        state: 'off'
    - condition: and
      conditions:
      - after: '22:00:00'
        before: '10:00:00'
        condition: time
      - condition: state
        entity_id: group.master_room_motion
        for: 02:00:00
        state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: automation.zl_mr_ceiling_lights_on_or_open_curtains_if_entering_to_room_master_room
  - service: input_select.select_option
    target:
      entity_id: input_select.master_room_scene
    data:
      option: All Off
  - service: homeassistant.turn_off
    entity_id:
    - light.master_room_drawer_led
    - light.master_room_tv_led
    - light.master_room_bed_led
    - light.master_room_ceiling_light
    - light.master_room_lamp_1
    - light.master_room_lamp_2
  - service: homeassistant.turn_off
    entity_id:
    - media_player.master_room_tv
  - service: cover.close_cover
    entity_id:
    - cover.master_room_blind
    - cover.master_room_curtain
- alias: ZLB-MR Remote Button - Single - Applies Different Scenes (State Execution)-Master Room
  trigger:
  - platform: state
    entity_id:
    - sensor.master_room_button_1
    - sensor.master_room_button_2
    to: single
  mode: queued
  action:
  - choose:
    - conditions:
        condition: state
        entity_id: input_select.master_room_scene
        state: All Off
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.master_room_scene
        data:
          option: All White
    - conditions:
        condition: state
        entity_id: input_select.master_room_scene
        state: All White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.master_room_scene
        data:
          option: Lamp LED White
    - conditions:
        condition: state
        entity_id: input_select.master_room_scene
        state: Lamp LED White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.master_room_scene
        data:
          option: LED White
    - conditions:
        condition: state
        entity_id: input_select.master_room_scene
        state: LED White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.master_room_scene
        data:
          option: Hue
    - conditions:
        condition: state
        entity_id: input_select.master_room_scene
        state: Hue
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.master_room_scene
        data:
          option: Night Mode
    - conditions:
        condition: state
        entity_id: input_select.master_room_scene
        state: Night Mode
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.master_room_scene
        data:
          option: Dark Night Mode
    - conditions:
        condition: state
        entity_id: input_select.master_room_scene
        state: Dark Night Mode
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.master_room_scene
        data:
          option: All Off
    default:
      service: input_select.select_option
      target:
        entity_id: input_select.master_room_scene
      data:
        option: Lamp LED White
  id: automation.zlb_mr_remote_button_single_applies_different_scenes_state_execution_master_room
- alias: ZLB-MR Applies Different Scenes Based on Scene Selections-Master Room
  trigger:
  - platform: state
    entity_id: input_select.master_room_scene
  mode: queued
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.master_room_scene
        state: All White
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id:
          - light.master_room_lamp_1
          - light.master_room_lamp_2
          - light.master_room_ceiling_light
          - light.master_room_drawer_led
          - light.master_room_tv_led
          - light.master_room_bed_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.master_room_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.master_room_scene
        state: Lamp LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.master_room_ceiling_light
        - service: homeassistant.turn_on
          entity_id:
          - light.master_room_lamp_1
          - light.master_room_lamp_2
          - light.master_room_drawer_led
          - light.master_room_tv_led
          - light.master_room_bed_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.master_room_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.master_room_scene
        state: LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.master_room_ceiling_light
          - light.master_room_lamp_1
          - light.master_room_lamp_2
        - service: homeassistant.turn_on
          entity_id:
          - light.master_room_drawer_led
          - light.master_room_tv_led
          - light.master_room_bed_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.master_room_tv
            picture_mode: Natural
    - conditions:
      - condition: state
        entity_id: input_select.master_room_scene
        state: Hue
      sequence:
      - service: light.turn_on
        entity_id:
        - light.master_room_lamp_1
        - light.master_room_lamp_2
        - light.master_room_drawer_led
        - light.master_room_tv_led
        - light.master_room_bed_led
        data:
          brightness_pct: 100
      - service: pyscript.set_rgb_light_list
        data:
          light_list:
          - light.master_room_lamp_1
          - light.master_room_lamp_2
          - light.master_room_ceiling_light
          - light.master_room_drawer_led
          - light.master_room_tv_led
          - light.master_room_bed_led
      - service: samsungtv_smart.select_picture_mode
        data:
          entity_id:
          - media_player.master_room_tv
          picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.master_room_scene
        state: Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.master_room_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.master_room_scene
        state: Dark Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.master_room_dark_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.master_room_scene
        state: All Off
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.master_room_lamp_1
          - light.master_room_lamp_2
          - light.master_room_ceiling_light
          - light.master_room_drawer_led
          - light.master_room_tv_led
          - light.master_room_bed_led
  id: automation.zlb_mr_applies_different_scenes_based_on_scene_selections_master_room
- alias: ZLB-MR Remote Button - Double - Toggle Lamps-Master Room
  trigger:
  - platform: state
    entity_id:
    - sensor.master_room_button_1
    - sensor.master_room_button_2
    to: double
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.master_room_lamp_1
    - light.master_room_lamp_2
  id: automation.zlb_mr_remote_button_double_toggle_lamps_master_room
- alias: ZLB-MR Remote Button - Triple - Set Scene-Master Room
  trigger:
  - platform: state
    entity_id:
    - sensor.master_room_button_1
    - sensor.master_room_button_2
    to: triple
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.master_room_lamp_1
    - light.master_room_lamp_2
  id: automation.zlb_mr_remote_button_triple_set_scene_master_room
- alias: ZLB-MR Remote Button - Long - Toggle LEDs-Master Room
  trigger:
  - platform: state
    entity_id:
    - sensor.master_room_button_1
    - sensor.master_room_button_2
    to: hold
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.master_room_drawer_led
    - light.master_room_tv_led
    - light.master_room_bed_led
  id: automation.zlb_mr_remote_button_long_toggle_leds_master_room
- alias: ZLB-MR Wall Switch - Single Press - Toggle Ceiling Light-Master Room
  trigger:
  - platform: state
    entity_id:
    - sensor.master_room_entrance_wall_button
    to: single
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.master_room_ceiling_light
  id: automation.zlb_mr_wall_switch_single_press_toggle_ceiling_light_master_room
- alias: ZLB-MR Wall Switch - Double Press - Leave Room and Turn Off Everything-Master Room
  trigger:
  - platform: state
    entity_id:
    - sensor.master_room_entrance_wall_button
    to: double
  action:
  - service: automation.trigger
    entity_id: automation.zl_mr_lights_off_if_no_person_master_room
  id: automation.zlb_mr_wall_switch_double_press_leave_room_and_turn_off_everything_master_room
- alias: ZOc-MR Occupancy Update-Master Room
  trigger:
  - entity_id: group.master_room_motion
    platform: state
    to: 'on'
  - entity_id: group.master_room_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.master_room_occupancy
      motion_str: group.master_room_motion
      motion_on_ratio_for_x_min_str: sensor.master_room_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.master_room_motion_on_ratio_for_last_8_minutes
      room_type: bedroom
  id: automation.zoc_mr_occupancy_update_master_room
- alias: ZH-MR Heating Schedule On If Staying In the Room-Master Room
  trigger:
  - platform: state
    entity_id: input_select.master_room_occupancy
    from:
    - Just Entered
    - Outside
    to: Stayed Inside
  action:
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.master_room
        state: heat
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.master_room
    - service: switch.turn_on
      target:
        entity_id: switch.schedule_master_room_temperature
  id: automation.zh_mr_heating_schedule_on_if_staying_in_the_room_master_room
- alias: ZH-MR Heating Schedule Off If People Left the Room-Master Room
  trigger:
  - platform: state
    entity_id: input_select.master_room_occupancy
    to: Outside
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.master_room
  - service: switch.turn_off
    target:
      entity_id: switch.schedule_master_room_temperature
  id: automation.zh_mr_heating_schedule_off_if_people_left_the_room_master_room
group:
  master_room_auto_gen_automations:
    name: Master Room Auto-gen Automations
    entities:
    - automation.zl_mr_ceiling_lights_on_or_open_curtains_if_entering_to_room_master_room
    - automation.zl_mr_lights_off_if_no_person_master_room
    - automation.zlb_mr_remote_button_single_applies_different_scenes_state_execution_master_room
    - automation.zlb_mr_applies_different_scenes_based_on_scene_selections_master_room
    - automation.zlb_mr_remote_button_double_toggle_lamps_master_room
    - automation.zlb_mr_remote_button_triple_set_scene_master_room
    - automation.zlb_mr_remote_button_long_toggle_leds_master_room
    - automation.zlb_mr_wall_switch_single_press_toggle_ceiling_light_master_room
    - automation.zlb_mr_wall_switch_double_press_leave_room_and_turn_off_everything_master_room
    - automation.zoc_mr_occupancy_update_master_room
    - automation.zh_mr_heating_schedule_on_if_staying_in_the_room_master_room
    - automation.zh_mr_heating_schedule_off_if_people_left_the_room_master_room
