automation:
- alias: ZL-ER Ceiling Lights On Or Open Curtains If Entering to Room-En-suite Room
  id: automation.zl_er_ceiling_lights_on_or_open_curtains_if_entering_to_room_en_suite_room
  trigger:
    entity_id:
    - binary_sensor.en_suite_room_entrance_motion_sensor_motion
    platform: state
    to: 'on'
  action:
  - service: automation.turn_off
    entity_id: automation.zl_er_ceiling_lights_on_or_open_curtains_if_entering_to_room_en_suite_room
    data:
      stop_actions: false
  - choose:
    - conditions:
        condition: state
        entity_id: input_boolean.always_on_constant
        state: 'on'
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: Ceiling Light White
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: All White
    - conditions:
      - condition: state
        entity_id: input_boolean.always_off_constant
        state: 'on'
      - condition: state
        entity_id: input_select.indoor_brightness
        state: bright
      - condition: not
        conditions:
        - condition: and
          conditions:
          - condition: numeric_state
            entity_id: sensor.cambridge_city_airport_temperature
            above: '20'
          - condition: time
            after: '13:00:00'
            before: '22:00:00'
          - condition: template
            value_template: '{{ now().month > 4 and now().month < 9 }}'
      sequence:
      - service: cover.open_cover
        entity_id: []
      - condition: state
        entity_id: input_boolean.always_off_constant
        state: 'on'
      - service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: Ceiling Light White with Curtain Open
    - conditions:
      - condition: time
        after: '10:00:00'
        before: '22:00:00'
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: All White
    default:
      service: input_select.select_option
      target:
        entity_id: input_select.en_suite_room_scene
      data:
        option: Lamp LED White
- alias: ZL-ER Lights Off If No Person-En-suite Room
  id: automation.zl_er_lights_off_if_no_person_en_suite_room
  trigger:
  - platform: state
    entity_id: input_select.en_suite_room_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  condition:
  - condition: state
    entity_id: input_select.en_suite_room_occupancy
    state: Outside
  - condition: state
    entity_id: group.en_suite_room_motion
    state: 'off'
    for: 00:01:00
  action:
  - service: homeassistant.turn_on
    entity_id: automation.zl_er_ceiling_lights_on_or_open_curtains_if_entering_to_room_en_suite_room
  - service: input_select.select_option
    target:
      entity_id: input_select.en_suite_room_scene
    data:
      option: All Off
  - service: homeassistant.turn_off
    entity_id:
    - light.en_suite_room_bed_led
    - light.en_suite_room_ceiling_light
    - light.en_suite_room_lamp_1
    - light.en_suite_room_lamp_2
  - service: homeassistant.turn_off
    entity_id:
    - media_player.portable_tv
  - service: cover.close_cover
    entity_id: []
- alias: ZL-ER LED On for 3 Min if Walking In the Dark-En-suite Room
  mode: restart
  trigger:
  - entity_id: binary_sensor.en_suite_room_floor_motion_sensor_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_select.indoor_brightness
    state: dark
  - entity_id:
    - light.en_suite_room_bed_led
    - light.en_suite_room_ceiling_light
    - light.en_suite_room_lamp_1
    - light.en_suite_room_lamp_2
    condition: state
    state: 'off'
  action:
  - service: light.turn_on
    entity_id:
    - light.en_suite_room_bed_led
    data:
      brightness_pct: 40
  - delay: 00:03:00
  - service: homeassistant.turn_off
    entity_id:
    - light.en_suite_room_bed_led
  id: automation.zl_er_led_on_for_3_min_if_walking_in_the_dark_en_suite_room
- alias: ZH-ER Heating Schedule On If Staying In the Room-En-suite Room
  id: automation.zh_er_heating_schedule_on_if_staying_in_the_room_en_suite_room
  trigger:
  - platform: state
    entity_id: input_select.en_suite_room_occupancy
    from:
    - Just Entered
    - Outside
    to: Stayed Inside
  action:
  - if:
    - condition: not
      conditions:
      - condition: state
        entity_id: climate.en_suite_room
        state: heat
    then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.en_suite_room
    - service: switch.turn_on
      target:
        entity_id: switch.schedule_en_suite_room_temperature
- alias: ZH-ER Heating Schedule Off If People Left the Room-En-suite Room
  id: automation.zh_er_heating_schedule_off_if_people_left_the_room_en_suite_room
  trigger:
  - platform: state
    entity_id: input_select.en_suite_room_occupancy
    to: Outside
  - minutes: /5
    platform: time_pattern
  action:
  - condition: state
    entity_id: input_select.en_suite_room_occupancy
    state: Outside
  - condition: state
    entity_id: input_boolean.en_suite_room_heating_override
    state: 'off'
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.en_suite_room
  - service: switch.turn_off
    target:
      entity_id: switch.schedule_en_suite_room_temperature
- alias: ZH-ER Heaeting Manual Override-En-suite Room
  trigger:
  - platform: state
    entity_id: input_boolean.en_suite_room_heating_override
  action:
  - if:
    - condition: state
      entity_id: input_boolean.en_suite_room_heating_override
      state: 'on'
    then:
    - service: automation.trigger
      entity_id:
      - automation.zh_er_heating_schedule_on_if_staying_in_the_room_en_suite_room
    else:
    - service: automation.trigger
      entity_id:
      - automation.zh_er_heating_schedule_off_if_people_left_the_room_en_suite_room
  id: automation.zh_er_heaeting_manual_override_en_suite_room
- alias: ZH-ER Valve Calibrate Temperature Using External Sensor-En-suite Room
  use_blueprint:
    path: calibrate_valve_temperature.yaml
    input:
      tado_valve_entity: climate.en_suite_room
      external_temperature_sensor_entity: sensor.en_suite_room_temperature_sensor
  id: automation.zh_er_valve_calibrate_temperature_using_external_sensor_en_suite_room
- alias: ZLB-ER Remote Button - Single - Applies Different Scenes (State Machine)-En-suite Room
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_button
    to:
    - single
    - '1'
  mode: queued
  action:
  - choose:
    - conditions:
        condition: state
        entity_id: input_select.en_suite_room_scene
        state: All Off
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: All White
    - conditions:
        condition: state
        entity_id: input_select.en_suite_room_scene
        state: All White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: Lamp LED White
    - conditions:
        condition: state
        entity_id: input_select.en_suite_room_scene
        state: Lamp LED White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: LED White
    - conditions:
        condition: state
        entity_id: input_select.en_suite_room_scene
        state: LED White
      sequence:
        service: input_select.select_option
        target:
          entity_id: input_select.en_suite_room_scene
        data:
          option: All Off
    default:
      service: input_select.select_option
      target:
        entity_id: input_select.en_suite_room_scene
      data:
        option: All Off
  id: automation.zlb_er_remote_button_single_applies_different_scenes_state_machine_en_suite_room
- alias: ZLB-ER Applies Different Scenes Based on Scene Selections (State Execution)-En-suite Room
  trigger:
  - platform: state
    entity_id: input_select.en_suite_room_scene
  mode: queued
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: All White
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id:
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
          - light.en_suite_room_ceiling_light
          - light.en_suite_room_bed_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.portable_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: Ceiling Light White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.en_suite_room_bed_led
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
        - service: homeassistant.turn_on
          entity_id:
          - light.en_suite_room_ceiling_light
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.portable_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: Lamp LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.en_suite_room_ceiling_light
        - service: homeassistant.turn_on
          entity_id:
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
          - light.en_suite_room_bed_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.portable_tv
            picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: Ceiling Light White with Curtain Open
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.en_suite_room_bed_led
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
        - service: homeassistant.turn_on
          entity_id:
          - light.en_suite_room_ceiling_light
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.portable_tv
            picture_mode: Standard
        - service: cover.open_cover
          entity_id: []
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: LED White
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.en_suite_room_ceiling_light
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
        - service: homeassistant.turn_on
          entity_id:
          - light.en_suite_room_bed_led
        - service: samsungtv_smart.select_picture_mode
          data:
            entity_id:
            - media_player.portable_tv
            picture_mode: Natural
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: Hue
      sequence:
      - service: light.turn_on
        entity_id:
        - light.en_suite_room_lamp_1
        - light.en_suite_room_lamp_2
        - light.en_suite_room_bed_led
        data:
          brightness_pct: 100
      - service: pyscript.set_rgb_light_list
        data:
          light_list:
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
          - light.en_suite_room_ceiling_light
          - light.en_suite_room_bed_led
      - service: samsungtv_smart.select_picture_mode
        data:
          entity_id:
          - media_player.portable_tv
          picture_mode: Standard
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.en_suite_room_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: Dark Night Mode
      sequence:
      - parallel:
        - service: homeassistant.turn_on
          entity_id: scene.en_suite_room_dark_night_mode
    - conditions:
      - condition: state
        entity_id: input_select.en_suite_room_scene
        state: All Off
      sequence:
      - parallel:
        - service: homeassistant.turn_off
          entity_id:
          - light.en_suite_room_lamp_1
          - light.en_suite_room_lamp_2
          - light.en_suite_room_ceiling_light
          - light.en_suite_room_bed_led
        - service: cover.close_cover
          entity_id: []
  id: automation.zlb_er_applies_different_scenes_based_on_scene_selections_state_execution_en_suite_room
- alias: ZLB-ER Remote Button - Double - Toggle Lamps-En-suite Room
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_button
    to:
    - double
    - '2'
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.en_suite_room_lamp_1
    - light.en_suite_room_lamp_2
  id: automation.zlb_er_remote_button_double_toggle_lamps_en_suite_room
- alias: ZLB-ER Remote Button - Triple - Toggle Ceiling Lights-En-suite Room
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_button
    to:
    - triple
    - '3'
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.en_suite_room_ceiling_light
  id: automation.zlb_er_remote_button_triple_toggle_ceiling_lights_en_suite_room
- alias: ZLB-ER Remote Button - Long - Toggle LEDs-En-suite Room
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_button
    to: hold
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.en_suite_room_bed_led
  id: automation.zlb_er_remote_button_long_toggle_leds_en_suite_room
- alias: ZLB-ER Wall Switch-Single Press - Toggle Ceiling Light-En-suite Room
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_wall_button
    to:
    - '1'
    - single
    - single_left
    - single_right
    - single_center
    - button_1_single
    - button_2_single
    - button_3_single
  action:
  - service: homeassistant.toggle
    entity_id:
    - light.en_suite_room_ceiling_light
  id: automation.zlb_er_wall_switch_single_press_toggle_ceiling_light_en_suite_room
- alias: ZLB-ER Wall Switch - Double Press - Leave Room and Turn Off Everything-En-suite Room
  trigger:
  - platform: state
    entity_id:
    - sensor.en_suite_room_wall_button
    to:
    - '2'
    - double
    - double_left
    - double_right
    - double_center
  action:
  - service: automation.trigger
    entity_id:
    - automation.zl_er_lights_off_if_no_person_en_suite_room
    - automation.zh_er_heating_schedule_off_if_people_left_the_room_en_suite_room
  - service: input_select.select_option
    target:
      entity_id: input_select.en_suite_room_occupancy
    data:
      option: Outside
  id: automation.zlb_er_wall_switch_double_press_leave_room_and_turn_off_everything_en_suite_room
- alias: ZOc-ER Occupancy Update-En-suite Room
  trigger:
  - entity_id: group.en_suite_room_motion
    platform: state
    to: 'on'
  - entity_id: group.en_suite_room_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.en_suite_room_occupancy
      motion_str: group.en_suite_room_motion
      motion_on_ratio_for_x_min_str: sensor.en_suite_room_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.en_suite_room_motion_on_ratio_for_last_8_minutes
      room_type: bedroom
  id: automation.zoc_er_occupancy_update_en_suite_room
input_select:
  en_suite_room_scene:
    name: En-suite Room Scene
    options:
    - Lamp LED White
    - LED White
    - All White
    - Ceiling Light White
    - All Off
  en_suite_room_occupancy:
    name: En-suite Room Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: En-suite Room Motion On Ratio For Last 4 Minutes
  entity_id: group.en_suite_room_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: En-suite Room Motion On Ratio For Last 8 Minutes
  entity_id: group.en_suite_room_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
input_boolean:
  en_suite_room_heating_override:
    name: En-suite Room Heating Override
    initial: 'off'
switch: []
template: []
binary_sensor: []
light: []
group:
  en_suite_room_occupancy_group:
    name: En-suite Room Occuapancy Group
    entities:
    - input_select.en_suite_room_occupancy
    - group.en_suite_room_motion
    - binary_sensor.en_suite_room_bed_motion_sensor_motion
    - binary_sensor.en_suite_room_entrance_motion_sensor_motion
    - binary_sensor.en_suite_room_floor_motion_sensor_motion
  en_suite_room_motion:
    name: En-suite Room Motion
    entities:
    - binary_sensor.en_suite_room_bed_motion_sensor_motion
    - binary_sensor.en_suite_room_entrance_motion_sensor_motion
    - binary_sensor.en_suite_room_floor_motion_sensor_motion
  en_suite_room_auto_gen_automations:
    name: En-suite Room Auto-gen Automations
    entities:
    - automation.zl_er_ceiling_lights_on_or_open_curtains_if_entering_to_room_en_suite_room
    - automation.zl_er_lights_off_if_no_person_en_suite_room
    - automation.zl_er_led_on_for_3_min_if_walking_in_the_dark_en_suite_room
    - automation.zh_er_heating_schedule_on_if_staying_in_the_room_en_suite_room
    - automation.zh_er_heating_schedule_off_if_people_left_the_room_en_suite_room
    - automation.zh_er_heaeting_manual_override_en_suite_room
    - automation.zh_er_valve_calibrate_temperature_using_external_sensor_en_suite_room
    - automation.zlb_er_remote_button_single_applies_different_scenes_state_machine_en_suite_room
    - automation.zlb_er_applies_different_scenes_based_on_scene_selections_state_execution_en_suite_room
    - automation.zlb_er_remote_button_double_toggle_lamps_en_suite_room
    - automation.zlb_er_remote_button_triple_toggle_ceiling_lights_en_suite_room
    - automation.zlb_er_remote_button_long_toggle_leds_en_suite_room
    - automation.zlb_er_wall_switch_single_press_toggle_ceiling_light_en_suite_room
    - automation.zlb_er_wall_switch_double_press_leave_room_and_turn_off_everything_en_suite_room
    - automation.zoc_er_occupancy_update_en_suite_room
