automation:
- alias: ZOc-WH Occupancy Update-Whole Home
  trigger:
  - entity_id: group.whole_home_motion
    platform: state
    to: 'on'
  - entity_id: group.whole_home_motion
    platform: state
    to: 'off'
    for: 05:00:00
  - minutes: /5
    platform: time_pattern
  action:
  - service: pyscript.room_occupancy_state_machine
    data:
      occupancy_entity_str: input_select.whole_home_occupancy
      motion_str: group.whole_home_motion
      motion_on_ratio_for_x_min_str: sensor.whole_home_motion_on_ratio_for_last_4_minutes
      motion_on_ratio_for_2x_min_str: sensor.whole_home_motion_on_ratio_for_last_8_minutes
      room_type: common_area
  id: automation.zoc_wh_occupancy_update_whole_home
input_select:
  whole_home_occupancy:
    name: Whole Home Occupancy
    options:
    - Outside
    - Just Entered
    - Stayed Inside
    - In Sleep
sensor:
- platform: history_stats
  name: Whole Home Motion On Ratio For Last 4 Minutes
  entity_id: group.whole_home_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '4'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
- platform: history_stats
  name: Whole Home Motion On Ratio For Last 8 Minutes
  entity_id: group.whole_home_motion
  state: 'on'
  type: ratio
  duration:
    minutes: '8'
  end: '{{ (now() | as_timestamp) | as_datetime | as_local }}'
input_boolean:
  ceiling_light_control_in_hot_sunshine_whole_home:
    name: Ceiling Light Control In Hot Sunshine Whole Home
    initial: 'off'
  lamp_control_in_hot_sunshine_whole_home:
    name: Lamp Control In Hot Sunshine Whole Home
    initial: 'off'
  led_control_in_hot_sunshine_whole_home:
    name: Led Control In Hot Sunshine Whole Home
    initial: 'off'
  curtain_control_in_hot_sunshine_whole_home:
    name: Curtain Control In Hot Sunshine Whole Home
    initial: 'off'
  ceiling_light_control_when_bright_outdoor_whole_home:
    name: Ceiling Light Control When Bright Outdoor Whole Home
  lamp_control_when_bright_outdoor_whole_home:
    name: Lamp Control When Bright Outdoor Whole Home
    initial: 'off'
  led_control_when_bright_outdoor_whole_home:
    name: Led Control When Bright Outdoor Whole Home
    initial: 'off'
  curtain_control_when_bright_outdoor_whole_home:
    name: Curtain Control When Bright Outdoor Whole Home
    initial: 'off'
  ceiling_light_control_when_dark_outdoor_whole_home:
    name: Ceiling Light Control When Dark Outdoor Whole Home
  lamp_control_when_dark_outdoor_whole_home:
    name: Lamp Control When Dark Outdoor Whole Home
    initial: 'off'
  led_control_when_dark_outdoor_whole_home:
    name: Led Control When Dark Outdoor Whole Home
    initial: 'off'
  curtain_control_when_dark_outdoor_whole_home:
    name: Curtain Control When Dark Outdoor Whole Home
    initial: 'off'
switch: []
template: []
binary_sensor: []
light: []
group:
  whole_home_occupancy_group:
    name: Whole Home Occuapancy Group
    entities:
    - input_select.whole_home_occupancy
    - group.whole_home_motion
    - group.living_room_motion
    - group.kitchen_motion
    - group.corridor_motion
    - group.study_motion
    - group.ground_toilet_motion
    - group.master_room_motion
    - group.master_toilet_motion
    - group.en_suite_room_motion
    - group.en_suite_toilet_motion
    - group.guest_room_motion
    - group.guest_toilet_motion
  whole_home_motion:
    name: Whole Home Motion
    entities:
    - group.living_room_motion
    - group.kitchen_motion
    - group.corridor_motion
    - group.study_motion
    - group.ground_toilet_motion
    - group.master_room_motion
    - group.master_toilet_motion
    - group.en_suite_room_motion
    - group.en_suite_toilet_motion
    - group.guest_room_motion
    - group.guest_toilet_motion
  whole_home_lights_and_tvs:
    name: Whole Home Lights And Tvs
    entities:
    - light.whole_home_ceiling_light
